
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `LogicalModel` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model LogicalModel
 * 
 */
export type LogicalModelModel = runtime.Types.Result.DefaultSelection<Prisma.$LogicalModelPayload>

export type AggregateLogicalModel = {
  _count: LogicalModelCountAggregateOutputType | null
  _avg: LogicalModelAvgAggregateOutputType | null
  _sum: LogicalModelSumAggregateOutputType | null
  _min: LogicalModelMinAggregateOutputType | null
  _max: LogicalModelMaxAggregateOutputType | null
}

export type LogicalModelAvgAggregateOutputType = {
  createdTime: number | null
  updatedTime: number | null
  deletedTime: number | null
}

export type LogicalModelSumAggregateOutputType = {
  createdTime: bigint | null
  updatedTime: bigint | null
  deletedTime: bigint | null
}

export type LogicalModelMinAggregateOutputType = {
  id: string | null
  name: string | null
  description: string | null
  enabled: boolean | null
  createdTime: bigint | null
  updatedTime: bigint | null
  deletedTime: bigint | null
}

export type LogicalModelMaxAggregateOutputType = {
  id: string | null
  name: string | null
  description: string | null
  enabled: boolean | null
  createdTime: bigint | null
  updatedTime: bigint | null
  deletedTime: bigint | null
}

export type LogicalModelCountAggregateOutputType = {
  id: number
  name: number
  description: number
  enabled: number
  createdTime: number
  updatedTime: number
  deletedTime: number
  _all: number
}


export type LogicalModelAvgAggregateInputType = {
  createdTime?: true
  updatedTime?: true
  deletedTime?: true
}

export type LogicalModelSumAggregateInputType = {
  createdTime?: true
  updatedTime?: true
  deletedTime?: true
}

export type LogicalModelMinAggregateInputType = {
  id?: true
  name?: true
  description?: true
  enabled?: true
  createdTime?: true
  updatedTime?: true
  deletedTime?: true
}

export type LogicalModelMaxAggregateInputType = {
  id?: true
  name?: true
  description?: true
  enabled?: true
  createdTime?: true
  updatedTime?: true
  deletedTime?: true
}

export type LogicalModelCountAggregateInputType = {
  id?: true
  name?: true
  description?: true
  enabled?: true
  createdTime?: true
  updatedTime?: true
  deletedTime?: true
  _all?: true
}

export type LogicalModelAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which LogicalModel to aggregate.
   */
  where?: Prisma.LogicalModelWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of LogicalModels to fetch.
   */
  orderBy?: Prisma.LogicalModelOrderByWithRelationInput | Prisma.LogicalModelOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.LogicalModelWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` LogicalModels from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` LogicalModels.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned LogicalModels
  **/
  _count?: true | LogicalModelCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: LogicalModelAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: LogicalModelSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: LogicalModelMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: LogicalModelMaxAggregateInputType
}

export type GetLogicalModelAggregateType<T extends LogicalModelAggregateArgs> = {
      [P in keyof T & keyof AggregateLogicalModel]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateLogicalModel[P]>
    : Prisma.GetScalarType<T[P], AggregateLogicalModel[P]>
}




export type LogicalModelGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.LogicalModelWhereInput
  orderBy?: Prisma.LogicalModelOrderByWithAggregationInput | Prisma.LogicalModelOrderByWithAggregationInput[]
  by: Prisma.LogicalModelScalarFieldEnum[] | Prisma.LogicalModelScalarFieldEnum
  having?: Prisma.LogicalModelScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: LogicalModelCountAggregateInputType | true
  _avg?: LogicalModelAvgAggregateInputType
  _sum?: LogicalModelSumAggregateInputType
  _min?: LogicalModelMinAggregateInputType
  _max?: LogicalModelMaxAggregateInputType
}

export type LogicalModelGroupByOutputType = {
  id: string
  name: string
  description: string
  enabled: boolean
  createdTime: bigint
  updatedTime: bigint
  deletedTime: bigint | null
  _count: LogicalModelCountAggregateOutputType | null
  _avg: LogicalModelAvgAggregateOutputType | null
  _sum: LogicalModelSumAggregateOutputType | null
  _min: LogicalModelMinAggregateOutputType | null
  _max: LogicalModelMaxAggregateOutputType | null
}

export type GetLogicalModelGroupByPayload<T extends LogicalModelGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<LogicalModelGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof LogicalModelGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], LogicalModelGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], LogicalModelGroupByOutputType[P]>
      }
    >
  >



export type LogicalModelWhereInput = {
  AND?: Prisma.LogicalModelWhereInput | Prisma.LogicalModelWhereInput[]
  OR?: Prisma.LogicalModelWhereInput[]
  NOT?: Prisma.LogicalModelWhereInput | Prisma.LogicalModelWhereInput[]
  id?: Prisma.StringFilter<"LogicalModel"> | string
  name?: Prisma.StringFilter<"LogicalModel"> | string
  description?: Prisma.StringFilter<"LogicalModel"> | string
  enabled?: Prisma.BoolFilter<"LogicalModel"> | boolean
  createdTime?: Prisma.BigIntFilter<"LogicalModel"> | bigint | number
  updatedTime?: Prisma.BigIntFilter<"LogicalModel"> | bigint | number
  deletedTime?: Prisma.BigIntNullableFilter<"LogicalModel"> | bigint | number | null
  bindings?: Prisma.ModelBindingListRelationFilter
}

export type LogicalModelOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  enabled?: Prisma.SortOrder
  createdTime?: Prisma.SortOrder
  updatedTime?: Prisma.SortOrder
  deletedTime?: Prisma.SortOrderInput | Prisma.SortOrder
  bindings?: Prisma.ModelBindingOrderByRelationAggregateInput
}

export type LogicalModelWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.LogicalModelWhereInput | Prisma.LogicalModelWhereInput[]
  OR?: Prisma.LogicalModelWhereInput[]
  NOT?: Prisma.LogicalModelWhereInput | Prisma.LogicalModelWhereInput[]
  name?: Prisma.StringFilter<"LogicalModel"> | string
  description?: Prisma.StringFilter<"LogicalModel"> | string
  enabled?: Prisma.BoolFilter<"LogicalModel"> | boolean
  createdTime?: Prisma.BigIntFilter<"LogicalModel"> | bigint | number
  updatedTime?: Prisma.BigIntFilter<"LogicalModel"> | bigint | number
  deletedTime?: Prisma.BigIntNullableFilter<"LogicalModel"> | bigint | number | null
  bindings?: Prisma.ModelBindingListRelationFilter
}, "id">

export type LogicalModelOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  enabled?: Prisma.SortOrder
  createdTime?: Prisma.SortOrder
  updatedTime?: Prisma.SortOrder
  deletedTime?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.LogicalModelCountOrderByAggregateInput
  _avg?: Prisma.LogicalModelAvgOrderByAggregateInput
  _max?: Prisma.LogicalModelMaxOrderByAggregateInput
  _min?: Prisma.LogicalModelMinOrderByAggregateInput
  _sum?: Prisma.LogicalModelSumOrderByAggregateInput
}

export type LogicalModelScalarWhereWithAggregatesInput = {
  AND?: Prisma.LogicalModelScalarWhereWithAggregatesInput | Prisma.LogicalModelScalarWhereWithAggregatesInput[]
  OR?: Prisma.LogicalModelScalarWhereWithAggregatesInput[]
  NOT?: Prisma.LogicalModelScalarWhereWithAggregatesInput | Prisma.LogicalModelScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"LogicalModel"> | string
  name?: Prisma.StringWithAggregatesFilter<"LogicalModel"> | string
  description?: Prisma.StringWithAggregatesFilter<"LogicalModel"> | string
  enabled?: Prisma.BoolWithAggregatesFilter<"LogicalModel"> | boolean
  createdTime?: Prisma.BigIntWithAggregatesFilter<"LogicalModel"> | bigint | number
  updatedTime?: Prisma.BigIntWithAggregatesFilter<"LogicalModel"> | bigint | number
  deletedTime?: Prisma.BigIntNullableWithAggregatesFilter<"LogicalModel"> | bigint | number | null
}

export type LogicalModelCreateInput = {
  id: string
  name: string
  description?: string
  enabled?: boolean
  createdTime: bigint | number
  updatedTime: bigint | number
  deletedTime?: bigint | number | null
  bindings?: Prisma.ModelBindingCreateNestedManyWithoutLogicalModelInput
}

export type LogicalModelUncheckedCreateInput = {
  id: string
  name: string
  description?: string
  enabled?: boolean
  createdTime: bigint | number
  updatedTime: bigint | number
  deletedTime?: bigint | number | null
  bindings?: Prisma.ModelBindingUncheckedCreateNestedManyWithoutLogicalModelInput
}

export type LogicalModelUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  enabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdTime?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  updatedTime?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  deletedTime?: Prisma.NullableBigIntFieldUpdateOperationsInput | bigint | number | null
  bindings?: Prisma.ModelBindingUpdateManyWithoutLogicalModelNestedInput
}

export type LogicalModelUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  enabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdTime?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  updatedTime?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  deletedTime?: Prisma.NullableBigIntFieldUpdateOperationsInput | bigint | number | null
  bindings?: Prisma.ModelBindingUncheckedUpdateManyWithoutLogicalModelNestedInput
}

export type LogicalModelCreateManyInput = {
  id: string
  name: string
  description?: string
  enabled?: boolean
  createdTime: bigint | number
  updatedTime: bigint | number
  deletedTime?: bigint | number | null
}

export type LogicalModelUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  enabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdTime?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  updatedTime?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  deletedTime?: Prisma.NullableBigIntFieldUpdateOperationsInput | bigint | number | null
}

export type LogicalModelUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  enabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdTime?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  updatedTime?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  deletedTime?: Prisma.NullableBigIntFieldUpdateOperationsInput | bigint | number | null
}

export type LogicalModelCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  enabled?: Prisma.SortOrder
  createdTime?: Prisma.SortOrder
  updatedTime?: Prisma.SortOrder
  deletedTime?: Prisma.SortOrder
}

export type LogicalModelAvgOrderByAggregateInput = {
  createdTime?: Prisma.SortOrder
  updatedTime?: Prisma.SortOrder
  deletedTime?: Prisma.SortOrder
}

export type LogicalModelMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  enabled?: Prisma.SortOrder
  createdTime?: Prisma.SortOrder
  updatedTime?: Prisma.SortOrder
  deletedTime?: Prisma.SortOrder
}

export type LogicalModelMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  enabled?: Prisma.SortOrder
  createdTime?: Prisma.SortOrder
  updatedTime?: Prisma.SortOrder
  deletedTime?: Prisma.SortOrder
}

export type LogicalModelSumOrderByAggregateInput = {
  createdTime?: Prisma.SortOrder
  updatedTime?: Prisma.SortOrder
  deletedTime?: Prisma.SortOrder
}

export type LogicalModelScalarRelationFilter = {
  is?: Prisma.LogicalModelWhereInput
  isNot?: Prisma.LogicalModelWhereInput
}

export type LogicalModelCreateNestedOneWithoutBindingsInput = {
  create?: Prisma.XOR<Prisma.LogicalModelCreateWithoutBindingsInput, Prisma.LogicalModelUncheckedCreateWithoutBindingsInput>
  connectOrCreate?: Prisma.LogicalModelCreateOrConnectWithoutBindingsInput
  connect?: Prisma.LogicalModelWhereUniqueInput
}

export type LogicalModelUpdateOneRequiredWithoutBindingsNestedInput = {
  create?: Prisma.XOR<Prisma.LogicalModelCreateWithoutBindingsInput, Prisma.LogicalModelUncheckedCreateWithoutBindingsInput>
  connectOrCreate?: Prisma.LogicalModelCreateOrConnectWithoutBindingsInput
  upsert?: Prisma.LogicalModelUpsertWithoutBindingsInput
  connect?: Prisma.LogicalModelWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.LogicalModelUpdateToOneWithWhereWithoutBindingsInput, Prisma.LogicalModelUpdateWithoutBindingsInput>, Prisma.LogicalModelUncheckedUpdateWithoutBindingsInput>
}

export type LogicalModelCreateWithoutBindingsInput = {
  id: string
  name: string
  description?: string
  enabled?: boolean
  createdTime: bigint | number
  updatedTime: bigint | number
  deletedTime?: bigint | number | null
}

export type LogicalModelUncheckedCreateWithoutBindingsInput = {
  id: string
  name: string
  description?: string
  enabled?: boolean
  createdTime: bigint | number
  updatedTime: bigint | number
  deletedTime?: bigint | number | null
}

export type LogicalModelCreateOrConnectWithoutBindingsInput = {
  where: Prisma.LogicalModelWhereUniqueInput
  create: Prisma.XOR<Prisma.LogicalModelCreateWithoutBindingsInput, Prisma.LogicalModelUncheckedCreateWithoutBindingsInput>
}

export type LogicalModelUpsertWithoutBindingsInput = {
  update: Prisma.XOR<Prisma.LogicalModelUpdateWithoutBindingsInput, Prisma.LogicalModelUncheckedUpdateWithoutBindingsInput>
  create: Prisma.XOR<Prisma.LogicalModelCreateWithoutBindingsInput, Prisma.LogicalModelUncheckedCreateWithoutBindingsInput>
  where?: Prisma.LogicalModelWhereInput
}

export type LogicalModelUpdateToOneWithWhereWithoutBindingsInput = {
  where?: Prisma.LogicalModelWhereInput
  data: Prisma.XOR<Prisma.LogicalModelUpdateWithoutBindingsInput, Prisma.LogicalModelUncheckedUpdateWithoutBindingsInput>
}

export type LogicalModelUpdateWithoutBindingsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  enabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdTime?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  updatedTime?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  deletedTime?: Prisma.NullableBigIntFieldUpdateOperationsInput | bigint | number | null
}

export type LogicalModelUncheckedUpdateWithoutBindingsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  enabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdTime?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  updatedTime?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  deletedTime?: Prisma.NullableBigIntFieldUpdateOperationsInput | bigint | number | null
}


/**
 * Count Type LogicalModelCountOutputType
 */

export type LogicalModelCountOutputType = {
  bindings: number
}

export type LogicalModelCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  bindings?: boolean | LogicalModelCountOutputTypeCountBindingsArgs
}

/**
 * LogicalModelCountOutputType without action
 */
export type LogicalModelCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LogicalModelCountOutputType
   */
  select?: Prisma.LogicalModelCountOutputTypeSelect<ExtArgs> | null
}

/**
 * LogicalModelCountOutputType without action
 */
export type LogicalModelCountOutputTypeCountBindingsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ModelBindingWhereInput
}


export type LogicalModelSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  description?: boolean
  enabled?: boolean
  createdTime?: boolean
  updatedTime?: boolean
  deletedTime?: boolean
  bindings?: boolean | Prisma.LogicalModel$bindingsArgs<ExtArgs>
  _count?: boolean | Prisma.LogicalModelCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["logicalModel"]>

export type LogicalModelSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  description?: boolean
  enabled?: boolean
  createdTime?: boolean
  updatedTime?: boolean
  deletedTime?: boolean
}, ExtArgs["result"]["logicalModel"]>

export type LogicalModelSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  description?: boolean
  enabled?: boolean
  createdTime?: boolean
  updatedTime?: boolean
  deletedTime?: boolean
}, ExtArgs["result"]["logicalModel"]>

export type LogicalModelSelectScalar = {
  id?: boolean
  name?: boolean
  description?: boolean
  enabled?: boolean
  createdTime?: boolean
  updatedTime?: boolean
  deletedTime?: boolean
}

export type LogicalModelOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "description" | "enabled" | "createdTime" | "updatedTime" | "deletedTime", ExtArgs["result"]["logicalModel"]>
export type LogicalModelInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  bindings?: boolean | Prisma.LogicalModel$bindingsArgs<ExtArgs>
  _count?: boolean | Prisma.LogicalModelCountOutputTypeDefaultArgs<ExtArgs>
}
export type LogicalModelIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type LogicalModelIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $LogicalModelPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "LogicalModel"
  objects: {
    bindings: Prisma.$ModelBindingPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    name: string
    description: string
    enabled: boolean
    createdTime: bigint
    updatedTime: bigint
    deletedTime: bigint | null
  }, ExtArgs["result"]["logicalModel"]>
  composites: {}
}

export type LogicalModelGetPayload<S extends boolean | null | undefined | LogicalModelDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$LogicalModelPayload, S>

export type LogicalModelCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<LogicalModelFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: LogicalModelCountAggregateInputType | true
  }

export interface LogicalModelDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['LogicalModel'], meta: { name: 'LogicalModel' } }
  /**
   * Find zero or one LogicalModel that matches the filter.
   * @param {LogicalModelFindUniqueArgs} args - Arguments to find a LogicalModel
   * @example
   * // Get one LogicalModel
   * const logicalModel = await prisma.logicalModel.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends LogicalModelFindUniqueArgs>(args: Prisma.SelectSubset<T, LogicalModelFindUniqueArgs<ExtArgs>>): Prisma.Prisma__LogicalModelClient<runtime.Types.Result.GetResult<Prisma.$LogicalModelPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one LogicalModel that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {LogicalModelFindUniqueOrThrowArgs} args - Arguments to find a LogicalModel
   * @example
   * // Get one LogicalModel
   * const logicalModel = await prisma.logicalModel.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends LogicalModelFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, LogicalModelFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__LogicalModelClient<runtime.Types.Result.GetResult<Prisma.$LogicalModelPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first LogicalModel that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LogicalModelFindFirstArgs} args - Arguments to find a LogicalModel
   * @example
   * // Get one LogicalModel
   * const logicalModel = await prisma.logicalModel.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends LogicalModelFindFirstArgs>(args?: Prisma.SelectSubset<T, LogicalModelFindFirstArgs<ExtArgs>>): Prisma.Prisma__LogicalModelClient<runtime.Types.Result.GetResult<Prisma.$LogicalModelPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first LogicalModel that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LogicalModelFindFirstOrThrowArgs} args - Arguments to find a LogicalModel
   * @example
   * // Get one LogicalModel
   * const logicalModel = await prisma.logicalModel.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends LogicalModelFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, LogicalModelFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__LogicalModelClient<runtime.Types.Result.GetResult<Prisma.$LogicalModelPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more LogicalModels that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LogicalModelFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all LogicalModels
   * const logicalModels = await prisma.logicalModel.findMany()
   * 
   * // Get first 10 LogicalModels
   * const logicalModels = await prisma.logicalModel.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const logicalModelWithIdOnly = await prisma.logicalModel.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends LogicalModelFindManyArgs>(args?: Prisma.SelectSubset<T, LogicalModelFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$LogicalModelPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a LogicalModel.
   * @param {LogicalModelCreateArgs} args - Arguments to create a LogicalModel.
   * @example
   * // Create one LogicalModel
   * const LogicalModel = await prisma.logicalModel.create({
   *   data: {
   *     // ... data to create a LogicalModel
   *   }
   * })
   * 
   */
  create<T extends LogicalModelCreateArgs>(args: Prisma.SelectSubset<T, LogicalModelCreateArgs<ExtArgs>>): Prisma.Prisma__LogicalModelClient<runtime.Types.Result.GetResult<Prisma.$LogicalModelPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many LogicalModels.
   * @param {LogicalModelCreateManyArgs} args - Arguments to create many LogicalModels.
   * @example
   * // Create many LogicalModels
   * const logicalModel = await prisma.logicalModel.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends LogicalModelCreateManyArgs>(args?: Prisma.SelectSubset<T, LogicalModelCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many LogicalModels and returns the data saved in the database.
   * @param {LogicalModelCreateManyAndReturnArgs} args - Arguments to create many LogicalModels.
   * @example
   * // Create many LogicalModels
   * const logicalModel = await prisma.logicalModel.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many LogicalModels and only return the `id`
   * const logicalModelWithIdOnly = await prisma.logicalModel.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends LogicalModelCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, LogicalModelCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$LogicalModelPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a LogicalModel.
   * @param {LogicalModelDeleteArgs} args - Arguments to delete one LogicalModel.
   * @example
   * // Delete one LogicalModel
   * const LogicalModel = await prisma.logicalModel.delete({
   *   where: {
   *     // ... filter to delete one LogicalModel
   *   }
   * })
   * 
   */
  delete<T extends LogicalModelDeleteArgs>(args: Prisma.SelectSubset<T, LogicalModelDeleteArgs<ExtArgs>>): Prisma.Prisma__LogicalModelClient<runtime.Types.Result.GetResult<Prisma.$LogicalModelPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one LogicalModel.
   * @param {LogicalModelUpdateArgs} args - Arguments to update one LogicalModel.
   * @example
   * // Update one LogicalModel
   * const logicalModel = await prisma.logicalModel.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends LogicalModelUpdateArgs>(args: Prisma.SelectSubset<T, LogicalModelUpdateArgs<ExtArgs>>): Prisma.Prisma__LogicalModelClient<runtime.Types.Result.GetResult<Prisma.$LogicalModelPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more LogicalModels.
   * @param {LogicalModelDeleteManyArgs} args - Arguments to filter LogicalModels to delete.
   * @example
   * // Delete a few LogicalModels
   * const { count } = await prisma.logicalModel.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends LogicalModelDeleteManyArgs>(args?: Prisma.SelectSubset<T, LogicalModelDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more LogicalModels.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LogicalModelUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many LogicalModels
   * const logicalModel = await prisma.logicalModel.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends LogicalModelUpdateManyArgs>(args: Prisma.SelectSubset<T, LogicalModelUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more LogicalModels and returns the data updated in the database.
   * @param {LogicalModelUpdateManyAndReturnArgs} args - Arguments to update many LogicalModels.
   * @example
   * // Update many LogicalModels
   * const logicalModel = await prisma.logicalModel.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more LogicalModels and only return the `id`
   * const logicalModelWithIdOnly = await prisma.logicalModel.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends LogicalModelUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, LogicalModelUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$LogicalModelPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one LogicalModel.
   * @param {LogicalModelUpsertArgs} args - Arguments to update or create a LogicalModel.
   * @example
   * // Update or create a LogicalModel
   * const logicalModel = await prisma.logicalModel.upsert({
   *   create: {
   *     // ... data to create a LogicalModel
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the LogicalModel we want to update
   *   }
   * })
   */
  upsert<T extends LogicalModelUpsertArgs>(args: Prisma.SelectSubset<T, LogicalModelUpsertArgs<ExtArgs>>): Prisma.Prisma__LogicalModelClient<runtime.Types.Result.GetResult<Prisma.$LogicalModelPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of LogicalModels.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LogicalModelCountArgs} args - Arguments to filter LogicalModels to count.
   * @example
   * // Count the number of LogicalModels
   * const count = await prisma.logicalModel.count({
   *   where: {
   *     // ... the filter for the LogicalModels we want to count
   *   }
   * })
  **/
  count<T extends LogicalModelCountArgs>(
    args?: Prisma.Subset<T, LogicalModelCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], LogicalModelCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a LogicalModel.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LogicalModelAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends LogicalModelAggregateArgs>(args: Prisma.Subset<T, LogicalModelAggregateArgs>): Prisma.PrismaPromise<GetLogicalModelAggregateType<T>>

  /**
   * Group by LogicalModel.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LogicalModelGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends LogicalModelGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: LogicalModelGroupByArgs['orderBy'] }
      : { orderBy?: LogicalModelGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, LogicalModelGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetLogicalModelGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the LogicalModel model
 */
readonly fields: LogicalModelFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for LogicalModel.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__LogicalModelClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  bindings<T extends Prisma.LogicalModel$bindingsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.LogicalModel$bindingsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ModelBindingPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the LogicalModel model
 */
export interface LogicalModelFieldRefs {
  readonly id: Prisma.FieldRef<"LogicalModel", 'String'>
  readonly name: Prisma.FieldRef<"LogicalModel", 'String'>
  readonly description: Prisma.FieldRef<"LogicalModel", 'String'>
  readonly enabled: Prisma.FieldRef<"LogicalModel", 'Boolean'>
  readonly createdTime: Prisma.FieldRef<"LogicalModel", 'BigInt'>
  readonly updatedTime: Prisma.FieldRef<"LogicalModel", 'BigInt'>
  readonly deletedTime: Prisma.FieldRef<"LogicalModel", 'BigInt'>
}
    

// Custom InputTypes
/**
 * LogicalModel findUnique
 */
export type LogicalModelFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LogicalModel
   */
  select?: Prisma.LogicalModelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LogicalModel
   */
  omit?: Prisma.LogicalModelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LogicalModelInclude<ExtArgs> | null
  /**
   * Filter, which LogicalModel to fetch.
   */
  where: Prisma.LogicalModelWhereUniqueInput
}

/**
 * LogicalModel findUniqueOrThrow
 */
export type LogicalModelFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LogicalModel
   */
  select?: Prisma.LogicalModelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LogicalModel
   */
  omit?: Prisma.LogicalModelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LogicalModelInclude<ExtArgs> | null
  /**
   * Filter, which LogicalModel to fetch.
   */
  where: Prisma.LogicalModelWhereUniqueInput
}

/**
 * LogicalModel findFirst
 */
export type LogicalModelFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LogicalModel
   */
  select?: Prisma.LogicalModelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LogicalModel
   */
  omit?: Prisma.LogicalModelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LogicalModelInclude<ExtArgs> | null
  /**
   * Filter, which LogicalModel to fetch.
   */
  where?: Prisma.LogicalModelWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of LogicalModels to fetch.
   */
  orderBy?: Prisma.LogicalModelOrderByWithRelationInput | Prisma.LogicalModelOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for LogicalModels.
   */
  cursor?: Prisma.LogicalModelWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` LogicalModels from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` LogicalModels.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of LogicalModels.
   */
  distinct?: Prisma.LogicalModelScalarFieldEnum | Prisma.LogicalModelScalarFieldEnum[]
}

/**
 * LogicalModel findFirstOrThrow
 */
export type LogicalModelFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LogicalModel
   */
  select?: Prisma.LogicalModelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LogicalModel
   */
  omit?: Prisma.LogicalModelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LogicalModelInclude<ExtArgs> | null
  /**
   * Filter, which LogicalModel to fetch.
   */
  where?: Prisma.LogicalModelWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of LogicalModels to fetch.
   */
  orderBy?: Prisma.LogicalModelOrderByWithRelationInput | Prisma.LogicalModelOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for LogicalModels.
   */
  cursor?: Prisma.LogicalModelWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` LogicalModels from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` LogicalModels.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of LogicalModels.
   */
  distinct?: Prisma.LogicalModelScalarFieldEnum | Prisma.LogicalModelScalarFieldEnum[]
}

/**
 * LogicalModel findMany
 */
export type LogicalModelFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LogicalModel
   */
  select?: Prisma.LogicalModelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LogicalModel
   */
  omit?: Prisma.LogicalModelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LogicalModelInclude<ExtArgs> | null
  /**
   * Filter, which LogicalModels to fetch.
   */
  where?: Prisma.LogicalModelWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of LogicalModels to fetch.
   */
  orderBy?: Prisma.LogicalModelOrderByWithRelationInput | Prisma.LogicalModelOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing LogicalModels.
   */
  cursor?: Prisma.LogicalModelWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` LogicalModels from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` LogicalModels.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of LogicalModels.
   */
  distinct?: Prisma.LogicalModelScalarFieldEnum | Prisma.LogicalModelScalarFieldEnum[]
}

/**
 * LogicalModel create
 */
export type LogicalModelCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LogicalModel
   */
  select?: Prisma.LogicalModelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LogicalModel
   */
  omit?: Prisma.LogicalModelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LogicalModelInclude<ExtArgs> | null
  /**
   * The data needed to create a LogicalModel.
   */
  data: Prisma.XOR<Prisma.LogicalModelCreateInput, Prisma.LogicalModelUncheckedCreateInput>
}

/**
 * LogicalModel createMany
 */
export type LogicalModelCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many LogicalModels.
   */
  data: Prisma.LogicalModelCreateManyInput | Prisma.LogicalModelCreateManyInput[]
}

/**
 * LogicalModel createManyAndReturn
 */
export type LogicalModelCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LogicalModel
   */
  select?: Prisma.LogicalModelSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the LogicalModel
   */
  omit?: Prisma.LogicalModelOmit<ExtArgs> | null
  /**
   * The data used to create many LogicalModels.
   */
  data: Prisma.LogicalModelCreateManyInput | Prisma.LogicalModelCreateManyInput[]
}

/**
 * LogicalModel update
 */
export type LogicalModelUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LogicalModel
   */
  select?: Prisma.LogicalModelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LogicalModel
   */
  omit?: Prisma.LogicalModelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LogicalModelInclude<ExtArgs> | null
  /**
   * The data needed to update a LogicalModel.
   */
  data: Prisma.XOR<Prisma.LogicalModelUpdateInput, Prisma.LogicalModelUncheckedUpdateInput>
  /**
   * Choose, which LogicalModel to update.
   */
  where: Prisma.LogicalModelWhereUniqueInput
}

/**
 * LogicalModel updateMany
 */
export type LogicalModelUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update LogicalModels.
   */
  data: Prisma.XOR<Prisma.LogicalModelUpdateManyMutationInput, Prisma.LogicalModelUncheckedUpdateManyInput>
  /**
   * Filter which LogicalModels to update
   */
  where?: Prisma.LogicalModelWhereInput
  /**
   * Limit how many LogicalModels to update.
   */
  limit?: number
}

/**
 * LogicalModel updateManyAndReturn
 */
export type LogicalModelUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LogicalModel
   */
  select?: Prisma.LogicalModelSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the LogicalModel
   */
  omit?: Prisma.LogicalModelOmit<ExtArgs> | null
  /**
   * The data used to update LogicalModels.
   */
  data: Prisma.XOR<Prisma.LogicalModelUpdateManyMutationInput, Prisma.LogicalModelUncheckedUpdateManyInput>
  /**
   * Filter which LogicalModels to update
   */
  where?: Prisma.LogicalModelWhereInput
  /**
   * Limit how many LogicalModels to update.
   */
  limit?: number
}

/**
 * LogicalModel upsert
 */
export type LogicalModelUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LogicalModel
   */
  select?: Prisma.LogicalModelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LogicalModel
   */
  omit?: Prisma.LogicalModelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LogicalModelInclude<ExtArgs> | null
  /**
   * The filter to search for the LogicalModel to update in case it exists.
   */
  where: Prisma.LogicalModelWhereUniqueInput
  /**
   * In case the LogicalModel found by the `where` argument doesn't exist, create a new LogicalModel with this data.
   */
  create: Prisma.XOR<Prisma.LogicalModelCreateInput, Prisma.LogicalModelUncheckedCreateInput>
  /**
   * In case the LogicalModel was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.LogicalModelUpdateInput, Prisma.LogicalModelUncheckedUpdateInput>
}

/**
 * LogicalModel delete
 */
export type LogicalModelDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LogicalModel
   */
  select?: Prisma.LogicalModelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LogicalModel
   */
  omit?: Prisma.LogicalModelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LogicalModelInclude<ExtArgs> | null
  /**
   * Filter which LogicalModel to delete.
   */
  where: Prisma.LogicalModelWhereUniqueInput
}

/**
 * LogicalModel deleteMany
 */
export type LogicalModelDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which LogicalModels to delete
   */
  where?: Prisma.LogicalModelWhereInput
  /**
   * Limit how many LogicalModels to delete.
   */
  limit?: number
}

/**
 * LogicalModel.bindings
 */
export type LogicalModel$bindingsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ModelBinding
   */
  select?: Prisma.ModelBindingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ModelBinding
   */
  omit?: Prisma.ModelBindingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ModelBindingInclude<ExtArgs> | null
  where?: Prisma.ModelBindingWhereInput
  orderBy?: Prisma.ModelBindingOrderByWithRelationInput | Prisma.ModelBindingOrderByWithRelationInput[]
  cursor?: Prisma.ModelBindingWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ModelBindingScalarFieldEnum | Prisma.ModelBindingScalarFieldEnum[]
}

/**
 * LogicalModel without action
 */
export type LogicalModelDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LogicalModel
   */
  select?: Prisma.LogicalModelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LogicalModel
   */
  omit?: Prisma.LogicalModelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LogicalModelInclude<ExtArgs> | null
}
