
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ModelBinding` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model ModelBinding
 * 
 */
export type ModelBindingModel = runtime.Types.Result.DefaultSelection<Prisma.$ModelBindingPayload>

export type AggregateModelBinding = {
  _count: ModelBindingCountAggregateOutputType | null
  _avg: ModelBindingAvgAggregateOutputType | null
  _sum: ModelBindingSumAggregateOutputType | null
  _min: ModelBindingMinAggregateOutputType | null
  _max: ModelBindingMaxAggregateOutputType | null
}

export type ModelBindingAvgAggregateOutputType = {
  priority: number | null
  createdTime: number | null
  updatedTime: number | null
  deletedTime: number | null
}

export type ModelBindingSumAggregateOutputType = {
  priority: number | null
  createdTime: bigint | null
  updatedTime: bigint | null
  deletedTime: bigint | null
}

export type ModelBindingMinAggregateOutputType = {
  id: string | null
  logicalModelId: string | null
  providerId: string | null
  protocol: string | null
  upstreamUrl: string | null
  upstreamModelId: string | null
  priority: number | null
  enabled: boolean | null
  customAuthHeader: string | null
  createdTime: bigint | null
  updatedTime: bigint | null
  deletedTime: bigint | null
}

export type ModelBindingMaxAggregateOutputType = {
  id: string | null
  logicalModelId: string | null
  providerId: string | null
  protocol: string | null
  upstreamUrl: string | null
  upstreamModelId: string | null
  priority: number | null
  enabled: boolean | null
  customAuthHeader: string | null
  createdTime: bigint | null
  updatedTime: bigint | null
  deletedTime: bigint | null
}

export type ModelBindingCountAggregateOutputType = {
  id: number
  logicalModelId: number
  providerId: number
  protocol: number
  upstreamUrl: number
  upstreamModelId: number
  priority: number
  enabled: number
  customAuthHeader: number
  createdTime: number
  updatedTime: number
  deletedTime: number
  _all: number
}


export type ModelBindingAvgAggregateInputType = {
  priority?: true
  createdTime?: true
  updatedTime?: true
  deletedTime?: true
}

export type ModelBindingSumAggregateInputType = {
  priority?: true
  createdTime?: true
  updatedTime?: true
  deletedTime?: true
}

export type ModelBindingMinAggregateInputType = {
  id?: true
  logicalModelId?: true
  providerId?: true
  protocol?: true
  upstreamUrl?: true
  upstreamModelId?: true
  priority?: true
  enabled?: true
  customAuthHeader?: true
  createdTime?: true
  updatedTime?: true
  deletedTime?: true
}

export type ModelBindingMaxAggregateInputType = {
  id?: true
  logicalModelId?: true
  providerId?: true
  protocol?: true
  upstreamUrl?: true
  upstreamModelId?: true
  priority?: true
  enabled?: true
  customAuthHeader?: true
  createdTime?: true
  updatedTime?: true
  deletedTime?: true
}

export type ModelBindingCountAggregateInputType = {
  id?: true
  logicalModelId?: true
  providerId?: true
  protocol?: true
  upstreamUrl?: true
  upstreamModelId?: true
  priority?: true
  enabled?: true
  customAuthHeader?: true
  createdTime?: true
  updatedTime?: true
  deletedTime?: true
  _all?: true
}

export type ModelBindingAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ModelBinding to aggregate.
   */
  where?: Prisma.ModelBindingWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ModelBindings to fetch.
   */
  orderBy?: Prisma.ModelBindingOrderByWithRelationInput | Prisma.ModelBindingOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ModelBindingWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ModelBindings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ModelBindings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ModelBindings
  **/
  _count?: true | ModelBindingCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: ModelBindingAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: ModelBindingSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ModelBindingMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ModelBindingMaxAggregateInputType
}

export type GetModelBindingAggregateType<T extends ModelBindingAggregateArgs> = {
      [P in keyof T & keyof AggregateModelBinding]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateModelBinding[P]>
    : Prisma.GetScalarType<T[P], AggregateModelBinding[P]>
}




export type ModelBindingGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ModelBindingWhereInput
  orderBy?: Prisma.ModelBindingOrderByWithAggregationInput | Prisma.ModelBindingOrderByWithAggregationInput[]
  by: Prisma.ModelBindingScalarFieldEnum[] | Prisma.ModelBindingScalarFieldEnum
  having?: Prisma.ModelBindingScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ModelBindingCountAggregateInputType | true
  _avg?: ModelBindingAvgAggregateInputType
  _sum?: ModelBindingSumAggregateInputType
  _min?: ModelBindingMinAggregateInputType
  _max?: ModelBindingMaxAggregateInputType
}

export type ModelBindingGroupByOutputType = {
  id: string
  logicalModelId: string
  providerId: string
  protocol: string
  upstreamUrl: string
  upstreamModelId: string
  priority: number
  enabled: boolean
  customAuthHeader: string | null
  createdTime: bigint
  updatedTime: bigint
  deletedTime: bigint | null
  _count: ModelBindingCountAggregateOutputType | null
  _avg: ModelBindingAvgAggregateOutputType | null
  _sum: ModelBindingSumAggregateOutputType | null
  _min: ModelBindingMinAggregateOutputType | null
  _max: ModelBindingMaxAggregateOutputType | null
}

export type GetModelBindingGroupByPayload<T extends ModelBindingGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ModelBindingGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ModelBindingGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ModelBindingGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ModelBindingGroupByOutputType[P]>
      }
    >
  >



export type ModelBindingWhereInput = {
  AND?: Prisma.ModelBindingWhereInput | Prisma.ModelBindingWhereInput[]
  OR?: Prisma.ModelBindingWhereInput[]
  NOT?: Prisma.ModelBindingWhereInput | Prisma.ModelBindingWhereInput[]
  id?: Prisma.StringFilter<"ModelBinding"> | string
  logicalModelId?: Prisma.StringFilter<"ModelBinding"> | string
  providerId?: Prisma.StringFilter<"ModelBinding"> | string
  protocol?: Prisma.StringFilter<"ModelBinding"> | string
  upstreamUrl?: Prisma.StringFilter<"ModelBinding"> | string
  upstreamModelId?: Prisma.StringFilter<"ModelBinding"> | string
  priority?: Prisma.IntFilter<"ModelBinding"> | number
  enabled?: Prisma.BoolFilter<"ModelBinding"> | boolean
  customAuthHeader?: Prisma.StringNullableFilter<"ModelBinding"> | string | null
  createdTime?: Prisma.BigIntFilter<"ModelBinding"> | bigint | number
  updatedTime?: Prisma.BigIntFilter<"ModelBinding"> | bigint | number
  deletedTime?: Prisma.BigIntNullableFilter<"ModelBinding"> | bigint | number | null
  logicalModel?: Prisma.XOR<Prisma.LogicalModelScalarRelationFilter, Prisma.LogicalModelWhereInput>
  provider?: Prisma.XOR<Prisma.ProviderScalarRelationFilter, Prisma.ProviderWhereInput>
  attempts?: Prisma.RequestAttemptListRelationFilter
}

export type ModelBindingOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  logicalModelId?: Prisma.SortOrder
  providerId?: Prisma.SortOrder
  protocol?: Prisma.SortOrder
  upstreamUrl?: Prisma.SortOrder
  upstreamModelId?: Prisma.SortOrder
  priority?: Prisma.SortOrder
  enabled?: Prisma.SortOrder
  customAuthHeader?: Prisma.SortOrderInput | Prisma.SortOrder
  createdTime?: Prisma.SortOrder
  updatedTime?: Prisma.SortOrder
  deletedTime?: Prisma.SortOrderInput | Prisma.SortOrder
  logicalModel?: Prisma.LogicalModelOrderByWithRelationInput
  provider?: Prisma.ProviderOrderByWithRelationInput
  attempts?: Prisma.RequestAttemptOrderByRelationAggregateInput
}

export type ModelBindingWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.ModelBindingWhereInput | Prisma.ModelBindingWhereInput[]
  OR?: Prisma.ModelBindingWhereInput[]
  NOT?: Prisma.ModelBindingWhereInput | Prisma.ModelBindingWhereInput[]
  logicalModelId?: Prisma.StringFilter<"ModelBinding"> | string
  providerId?: Prisma.StringFilter<"ModelBinding"> | string
  protocol?: Prisma.StringFilter<"ModelBinding"> | string
  upstreamUrl?: Prisma.StringFilter<"ModelBinding"> | string
  upstreamModelId?: Prisma.StringFilter<"ModelBinding"> | string
  priority?: Prisma.IntFilter<"ModelBinding"> | number
  enabled?: Prisma.BoolFilter<"ModelBinding"> | boolean
  customAuthHeader?: Prisma.StringNullableFilter<"ModelBinding"> | string | null
  createdTime?: Prisma.BigIntFilter<"ModelBinding"> | bigint | number
  updatedTime?: Prisma.BigIntFilter<"ModelBinding"> | bigint | number
  deletedTime?: Prisma.BigIntNullableFilter<"ModelBinding"> | bigint | number | null
  logicalModel?: Prisma.XOR<Prisma.LogicalModelScalarRelationFilter, Prisma.LogicalModelWhereInput>
  provider?: Prisma.XOR<Prisma.ProviderScalarRelationFilter, Prisma.ProviderWhereInput>
  attempts?: Prisma.RequestAttemptListRelationFilter
}, "id">

export type ModelBindingOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  logicalModelId?: Prisma.SortOrder
  providerId?: Prisma.SortOrder
  protocol?: Prisma.SortOrder
  upstreamUrl?: Prisma.SortOrder
  upstreamModelId?: Prisma.SortOrder
  priority?: Prisma.SortOrder
  enabled?: Prisma.SortOrder
  customAuthHeader?: Prisma.SortOrderInput | Prisma.SortOrder
  createdTime?: Prisma.SortOrder
  updatedTime?: Prisma.SortOrder
  deletedTime?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.ModelBindingCountOrderByAggregateInput
  _avg?: Prisma.ModelBindingAvgOrderByAggregateInput
  _max?: Prisma.ModelBindingMaxOrderByAggregateInput
  _min?: Prisma.ModelBindingMinOrderByAggregateInput
  _sum?: Prisma.ModelBindingSumOrderByAggregateInput
}

export type ModelBindingScalarWhereWithAggregatesInput = {
  AND?: Prisma.ModelBindingScalarWhereWithAggregatesInput | Prisma.ModelBindingScalarWhereWithAggregatesInput[]
  OR?: Prisma.ModelBindingScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ModelBindingScalarWhereWithAggregatesInput | Prisma.ModelBindingScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"ModelBinding"> | string
  logicalModelId?: Prisma.StringWithAggregatesFilter<"ModelBinding"> | string
  providerId?: Prisma.StringWithAggregatesFilter<"ModelBinding"> | string
  protocol?: Prisma.StringWithAggregatesFilter<"ModelBinding"> | string
  upstreamUrl?: Prisma.StringWithAggregatesFilter<"ModelBinding"> | string
  upstreamModelId?: Prisma.StringWithAggregatesFilter<"ModelBinding"> | string
  priority?: Prisma.IntWithAggregatesFilter<"ModelBinding"> | number
  enabled?: Prisma.BoolWithAggregatesFilter<"ModelBinding"> | boolean
  customAuthHeader?: Prisma.StringNullableWithAggregatesFilter<"ModelBinding"> | string | null
  createdTime?: Prisma.BigIntWithAggregatesFilter<"ModelBinding"> | bigint | number
  updatedTime?: Prisma.BigIntWithAggregatesFilter<"ModelBinding"> | bigint | number
  deletedTime?: Prisma.BigIntNullableWithAggregatesFilter<"ModelBinding"> | bigint | number | null
}

export type ModelBindingCreateInput = {
  id: string
  protocol: string
  upstreamUrl: string
  upstreamModelId: string
  priority: number
  enabled?: boolean
  customAuthHeader?: string | null
  createdTime: bigint | number
  updatedTime: bigint | number
  deletedTime?: bigint | number | null
  logicalModel: Prisma.LogicalModelCreateNestedOneWithoutBindingsInput
  provider: Prisma.ProviderCreateNestedOneWithoutBindingsInput
  attempts?: Prisma.RequestAttemptCreateNestedManyWithoutBindingInput
}

export type ModelBindingUncheckedCreateInput = {
  id: string
  logicalModelId: string
  providerId: string
  protocol: string
  upstreamUrl: string
  upstreamModelId: string
  priority: number
  enabled?: boolean
  customAuthHeader?: string | null
  createdTime: bigint | number
  updatedTime: bigint | number
  deletedTime?: bigint | number | null
  attempts?: Prisma.RequestAttemptUncheckedCreateNestedManyWithoutBindingInput
}

export type ModelBindingUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  protocol?: Prisma.StringFieldUpdateOperationsInput | string
  upstreamUrl?: Prisma.StringFieldUpdateOperationsInput | string
  upstreamModelId?: Prisma.StringFieldUpdateOperationsInput | string
  priority?: Prisma.IntFieldUpdateOperationsInput | number
  enabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  customAuthHeader?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdTime?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  updatedTime?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  deletedTime?: Prisma.NullableBigIntFieldUpdateOperationsInput | bigint | number | null
  logicalModel?: Prisma.LogicalModelUpdateOneRequiredWithoutBindingsNestedInput
  provider?: Prisma.ProviderUpdateOneRequiredWithoutBindingsNestedInput
  attempts?: Prisma.RequestAttemptUpdateManyWithoutBindingNestedInput
}

export type ModelBindingUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  logicalModelId?: Prisma.StringFieldUpdateOperationsInput | string
  providerId?: Prisma.StringFieldUpdateOperationsInput | string
  protocol?: Prisma.StringFieldUpdateOperationsInput | string
  upstreamUrl?: Prisma.StringFieldUpdateOperationsInput | string
  upstreamModelId?: Prisma.StringFieldUpdateOperationsInput | string
  priority?: Prisma.IntFieldUpdateOperationsInput | number
  enabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  customAuthHeader?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdTime?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  updatedTime?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  deletedTime?: Prisma.NullableBigIntFieldUpdateOperationsInput | bigint | number | null
  attempts?: Prisma.RequestAttemptUncheckedUpdateManyWithoutBindingNestedInput
}

export type ModelBindingCreateManyInput = {
  id: string
  logicalModelId: string
  providerId: string
  protocol: string
  upstreamUrl: string
  upstreamModelId: string
  priority: number
  enabled?: boolean
  customAuthHeader?: string | null
  createdTime: bigint | number
  updatedTime: bigint | number
  deletedTime?: bigint | number | null
}

export type ModelBindingUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  protocol?: Prisma.StringFieldUpdateOperationsInput | string
  upstreamUrl?: Prisma.StringFieldUpdateOperationsInput | string
  upstreamModelId?: Prisma.StringFieldUpdateOperationsInput | string
  priority?: Prisma.IntFieldUpdateOperationsInput | number
  enabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  customAuthHeader?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdTime?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  updatedTime?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  deletedTime?: Prisma.NullableBigIntFieldUpdateOperationsInput | bigint | number | null
}

export type ModelBindingUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  logicalModelId?: Prisma.StringFieldUpdateOperationsInput | string
  providerId?: Prisma.StringFieldUpdateOperationsInput | string
  protocol?: Prisma.StringFieldUpdateOperationsInput | string
  upstreamUrl?: Prisma.StringFieldUpdateOperationsInput | string
  upstreamModelId?: Prisma.StringFieldUpdateOperationsInput | string
  priority?: Prisma.IntFieldUpdateOperationsInput | number
  enabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  customAuthHeader?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdTime?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  updatedTime?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  deletedTime?: Prisma.NullableBigIntFieldUpdateOperationsInput | bigint | number | null
}

export type ModelBindingListRelationFilter = {
  every?: Prisma.ModelBindingWhereInput
  some?: Prisma.ModelBindingWhereInput
  none?: Prisma.ModelBindingWhereInput
}

export type ModelBindingOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ModelBindingCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  logicalModelId?: Prisma.SortOrder
  providerId?: Prisma.SortOrder
  protocol?: Prisma.SortOrder
  upstreamUrl?: Prisma.SortOrder
  upstreamModelId?: Prisma.SortOrder
  priority?: Prisma.SortOrder
  enabled?: Prisma.SortOrder
  customAuthHeader?: Prisma.SortOrder
  createdTime?: Prisma.SortOrder
  updatedTime?: Prisma.SortOrder
  deletedTime?: Prisma.SortOrder
}

export type ModelBindingAvgOrderByAggregateInput = {
  priority?: Prisma.SortOrder
  createdTime?: Prisma.SortOrder
  updatedTime?: Prisma.SortOrder
  deletedTime?: Prisma.SortOrder
}

export type ModelBindingMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  logicalModelId?: Prisma.SortOrder
  providerId?: Prisma.SortOrder
  protocol?: Prisma.SortOrder
  upstreamUrl?: Prisma.SortOrder
  upstreamModelId?: Prisma.SortOrder
  priority?: Prisma.SortOrder
  enabled?: Prisma.SortOrder
  customAuthHeader?: Prisma.SortOrder
  createdTime?: Prisma.SortOrder
  updatedTime?: Prisma.SortOrder
  deletedTime?: Prisma.SortOrder
}

export type ModelBindingMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  logicalModelId?: Prisma.SortOrder
  providerId?: Prisma.SortOrder
  protocol?: Prisma.SortOrder
  upstreamUrl?: Prisma.SortOrder
  upstreamModelId?: Prisma.SortOrder
  priority?: Prisma.SortOrder
  enabled?: Prisma.SortOrder
  customAuthHeader?: Prisma.SortOrder
  createdTime?: Prisma.SortOrder
  updatedTime?: Prisma.SortOrder
  deletedTime?: Prisma.SortOrder
}

export type ModelBindingSumOrderByAggregateInput = {
  priority?: Prisma.SortOrder
  createdTime?: Prisma.SortOrder
  updatedTime?: Prisma.SortOrder
  deletedTime?: Prisma.SortOrder
}

export type ModelBindingScalarRelationFilter = {
  is?: Prisma.ModelBindingWhereInput
  isNot?: Prisma.ModelBindingWhereInput
}

export type ModelBindingCreateNestedManyWithoutProviderInput = {
  create?: Prisma.XOR<Prisma.ModelBindingCreateWithoutProviderInput, Prisma.ModelBindingUncheckedCreateWithoutProviderInput> | Prisma.ModelBindingCreateWithoutProviderInput[] | Prisma.ModelBindingUncheckedCreateWithoutProviderInput[]
  connectOrCreate?: Prisma.ModelBindingCreateOrConnectWithoutProviderInput | Prisma.ModelBindingCreateOrConnectWithoutProviderInput[]
  createMany?: Prisma.ModelBindingCreateManyProviderInputEnvelope
  connect?: Prisma.ModelBindingWhereUniqueInput | Prisma.ModelBindingWhereUniqueInput[]
}

export type ModelBindingUncheckedCreateNestedManyWithoutProviderInput = {
  create?: Prisma.XOR<Prisma.ModelBindingCreateWithoutProviderInput, Prisma.ModelBindingUncheckedCreateWithoutProviderInput> | Prisma.ModelBindingCreateWithoutProviderInput[] | Prisma.ModelBindingUncheckedCreateWithoutProviderInput[]
  connectOrCreate?: Prisma.ModelBindingCreateOrConnectWithoutProviderInput | Prisma.ModelBindingCreateOrConnectWithoutProviderInput[]
  createMany?: Prisma.ModelBindingCreateManyProviderInputEnvelope
  connect?: Prisma.ModelBindingWhereUniqueInput | Prisma.ModelBindingWhereUniqueInput[]
}

export type ModelBindingUpdateManyWithoutProviderNestedInput = {
  create?: Prisma.XOR<Prisma.ModelBindingCreateWithoutProviderInput, Prisma.ModelBindingUncheckedCreateWithoutProviderInput> | Prisma.ModelBindingCreateWithoutProviderInput[] | Prisma.ModelBindingUncheckedCreateWithoutProviderInput[]
  connectOrCreate?: Prisma.ModelBindingCreateOrConnectWithoutProviderInput | Prisma.ModelBindingCreateOrConnectWithoutProviderInput[]
  upsert?: Prisma.ModelBindingUpsertWithWhereUniqueWithoutProviderInput | Prisma.ModelBindingUpsertWithWhereUniqueWithoutProviderInput[]
  createMany?: Prisma.ModelBindingCreateManyProviderInputEnvelope
  set?: Prisma.ModelBindingWhereUniqueInput | Prisma.ModelBindingWhereUniqueInput[]
  disconnect?: Prisma.ModelBindingWhereUniqueInput | Prisma.ModelBindingWhereUniqueInput[]
  delete?: Prisma.ModelBindingWhereUniqueInput | Prisma.ModelBindingWhereUniqueInput[]
  connect?: Prisma.ModelBindingWhereUniqueInput | Prisma.ModelBindingWhereUniqueInput[]
  update?: Prisma.ModelBindingUpdateWithWhereUniqueWithoutProviderInput | Prisma.ModelBindingUpdateWithWhereUniqueWithoutProviderInput[]
  updateMany?: Prisma.ModelBindingUpdateManyWithWhereWithoutProviderInput | Prisma.ModelBindingUpdateManyWithWhereWithoutProviderInput[]
  deleteMany?: Prisma.ModelBindingScalarWhereInput | Prisma.ModelBindingScalarWhereInput[]
}

export type ModelBindingUncheckedUpdateManyWithoutProviderNestedInput = {
  create?: Prisma.XOR<Prisma.ModelBindingCreateWithoutProviderInput, Prisma.ModelBindingUncheckedCreateWithoutProviderInput> | Prisma.ModelBindingCreateWithoutProviderInput[] | Prisma.ModelBindingUncheckedCreateWithoutProviderInput[]
  connectOrCreate?: Prisma.ModelBindingCreateOrConnectWithoutProviderInput | Prisma.ModelBindingCreateOrConnectWithoutProviderInput[]
  upsert?: Prisma.ModelBindingUpsertWithWhereUniqueWithoutProviderInput | Prisma.ModelBindingUpsertWithWhereUniqueWithoutProviderInput[]
  createMany?: Prisma.ModelBindingCreateManyProviderInputEnvelope
  set?: Prisma.ModelBindingWhereUniqueInput | Prisma.ModelBindingWhereUniqueInput[]
  disconnect?: Prisma.ModelBindingWhereUniqueInput | Prisma.ModelBindingWhereUniqueInput[]
  delete?: Prisma.ModelBindingWhereUniqueInput | Prisma.ModelBindingWhereUniqueInput[]
  connect?: Prisma.ModelBindingWhereUniqueInput | Prisma.ModelBindingWhereUniqueInput[]
  update?: Prisma.ModelBindingUpdateWithWhereUniqueWithoutProviderInput | Prisma.ModelBindingUpdateWithWhereUniqueWithoutProviderInput[]
  updateMany?: Prisma.ModelBindingUpdateManyWithWhereWithoutProviderInput | Prisma.ModelBindingUpdateManyWithWhereWithoutProviderInput[]
  deleteMany?: Prisma.ModelBindingScalarWhereInput | Prisma.ModelBindingScalarWhereInput[]
}

export type ModelBindingCreateNestedManyWithoutLogicalModelInput = {
  create?: Prisma.XOR<Prisma.ModelBindingCreateWithoutLogicalModelInput, Prisma.ModelBindingUncheckedCreateWithoutLogicalModelInput> | Prisma.ModelBindingCreateWithoutLogicalModelInput[] | Prisma.ModelBindingUncheckedCreateWithoutLogicalModelInput[]
  connectOrCreate?: Prisma.ModelBindingCreateOrConnectWithoutLogicalModelInput | Prisma.ModelBindingCreateOrConnectWithoutLogicalModelInput[]
  createMany?: Prisma.ModelBindingCreateManyLogicalModelInputEnvelope
  connect?: Prisma.ModelBindingWhereUniqueInput | Prisma.ModelBindingWhereUniqueInput[]
}

export type ModelBindingUncheckedCreateNestedManyWithoutLogicalModelInput = {
  create?: Prisma.XOR<Prisma.ModelBindingCreateWithoutLogicalModelInput, Prisma.ModelBindingUncheckedCreateWithoutLogicalModelInput> | Prisma.ModelBindingCreateWithoutLogicalModelInput[] | Prisma.ModelBindingUncheckedCreateWithoutLogicalModelInput[]
  connectOrCreate?: Prisma.ModelBindingCreateOrConnectWithoutLogicalModelInput | Prisma.ModelBindingCreateOrConnectWithoutLogicalModelInput[]
  createMany?: Prisma.ModelBindingCreateManyLogicalModelInputEnvelope
  connect?: Prisma.ModelBindingWhereUniqueInput | Prisma.ModelBindingWhereUniqueInput[]
}

export type ModelBindingUpdateManyWithoutLogicalModelNestedInput = {
  create?: Prisma.XOR<Prisma.ModelBindingCreateWithoutLogicalModelInput, Prisma.ModelBindingUncheckedCreateWithoutLogicalModelInput> | Prisma.ModelBindingCreateWithoutLogicalModelInput[] | Prisma.ModelBindingUncheckedCreateWithoutLogicalModelInput[]
  connectOrCreate?: Prisma.ModelBindingCreateOrConnectWithoutLogicalModelInput | Prisma.ModelBindingCreateOrConnectWithoutLogicalModelInput[]
  upsert?: Prisma.ModelBindingUpsertWithWhereUniqueWithoutLogicalModelInput | Prisma.ModelBindingUpsertWithWhereUniqueWithoutLogicalModelInput[]
  createMany?: Prisma.ModelBindingCreateManyLogicalModelInputEnvelope
  set?: Prisma.ModelBindingWhereUniqueInput | Prisma.ModelBindingWhereUniqueInput[]
  disconnect?: Prisma.ModelBindingWhereUniqueInput | Prisma.ModelBindingWhereUniqueInput[]
  delete?: Prisma.ModelBindingWhereUniqueInput | Prisma.ModelBindingWhereUniqueInput[]
  connect?: Prisma.ModelBindingWhereUniqueInput | Prisma.ModelBindingWhereUniqueInput[]
  update?: Prisma.ModelBindingUpdateWithWhereUniqueWithoutLogicalModelInput | Prisma.ModelBindingUpdateWithWhereUniqueWithoutLogicalModelInput[]
  updateMany?: Prisma.ModelBindingUpdateManyWithWhereWithoutLogicalModelInput | Prisma.ModelBindingUpdateManyWithWhereWithoutLogicalModelInput[]
  deleteMany?: Prisma.ModelBindingScalarWhereInput | Prisma.ModelBindingScalarWhereInput[]
}

export type ModelBindingUncheckedUpdateManyWithoutLogicalModelNestedInput = {
  create?: Prisma.XOR<Prisma.ModelBindingCreateWithoutLogicalModelInput, Prisma.ModelBindingUncheckedCreateWithoutLogicalModelInput> | Prisma.ModelBindingCreateWithoutLogicalModelInput[] | Prisma.ModelBindingUncheckedCreateWithoutLogicalModelInput[]
  connectOrCreate?: Prisma.ModelBindingCreateOrConnectWithoutLogicalModelInput | Prisma.ModelBindingCreateOrConnectWithoutLogicalModelInput[]
  upsert?: Prisma.ModelBindingUpsertWithWhereUniqueWithoutLogicalModelInput | Prisma.ModelBindingUpsertWithWhereUniqueWithoutLogicalModelInput[]
  createMany?: Prisma.ModelBindingCreateManyLogicalModelInputEnvelope
  set?: Prisma.ModelBindingWhereUniqueInput | Prisma.ModelBindingWhereUniqueInput[]
  disconnect?: Prisma.ModelBindingWhereUniqueInput | Prisma.ModelBindingWhereUniqueInput[]
  delete?: Prisma.ModelBindingWhereUniqueInput | Prisma.ModelBindingWhereUniqueInput[]
  connect?: Prisma.ModelBindingWhereUniqueInput | Prisma.ModelBindingWhereUniqueInput[]
  update?: Prisma.ModelBindingUpdateWithWhereUniqueWithoutLogicalModelInput | Prisma.ModelBindingUpdateWithWhereUniqueWithoutLogicalModelInput[]
  updateMany?: Prisma.ModelBindingUpdateManyWithWhereWithoutLogicalModelInput | Prisma.ModelBindingUpdateManyWithWhereWithoutLogicalModelInput[]
  deleteMany?: Prisma.ModelBindingScalarWhereInput | Prisma.ModelBindingScalarWhereInput[]
}

export type NullableStringFieldUpdateOperationsInput = {
  set?: string | null
}

export type ModelBindingCreateNestedOneWithoutAttemptsInput = {
  create?: Prisma.XOR<Prisma.ModelBindingCreateWithoutAttemptsInput, Prisma.ModelBindingUncheckedCreateWithoutAttemptsInput>
  connectOrCreate?: Prisma.ModelBindingCreateOrConnectWithoutAttemptsInput
  connect?: Prisma.ModelBindingWhereUniqueInput
}

export type ModelBindingUpdateOneRequiredWithoutAttemptsNestedInput = {
  create?: Prisma.XOR<Prisma.ModelBindingCreateWithoutAttemptsInput, Prisma.ModelBindingUncheckedCreateWithoutAttemptsInput>
  connectOrCreate?: Prisma.ModelBindingCreateOrConnectWithoutAttemptsInput
  upsert?: Prisma.ModelBindingUpsertWithoutAttemptsInput
  connect?: Prisma.ModelBindingWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ModelBindingUpdateToOneWithWhereWithoutAttemptsInput, Prisma.ModelBindingUpdateWithoutAttemptsInput>, Prisma.ModelBindingUncheckedUpdateWithoutAttemptsInput>
}

export type ModelBindingCreateWithoutProviderInput = {
  id: string
  protocol: string
  upstreamUrl: string
  upstreamModelId: string
  priority: number
  enabled?: boolean
  customAuthHeader?: string | null
  createdTime: bigint | number
  updatedTime: bigint | number
  deletedTime?: bigint | number | null
  logicalModel: Prisma.LogicalModelCreateNestedOneWithoutBindingsInput
  attempts?: Prisma.RequestAttemptCreateNestedManyWithoutBindingInput
}

export type ModelBindingUncheckedCreateWithoutProviderInput = {
  id: string
  logicalModelId: string
  protocol: string
  upstreamUrl: string
  upstreamModelId: string
  priority: number
  enabled?: boolean
  customAuthHeader?: string | null
  createdTime: bigint | number
  updatedTime: bigint | number
  deletedTime?: bigint | number | null
  attempts?: Prisma.RequestAttemptUncheckedCreateNestedManyWithoutBindingInput
}

export type ModelBindingCreateOrConnectWithoutProviderInput = {
  where: Prisma.ModelBindingWhereUniqueInput
  create: Prisma.XOR<Prisma.ModelBindingCreateWithoutProviderInput, Prisma.ModelBindingUncheckedCreateWithoutProviderInput>
}

export type ModelBindingCreateManyProviderInputEnvelope = {
  data: Prisma.ModelBindingCreateManyProviderInput | Prisma.ModelBindingCreateManyProviderInput[]
}

export type ModelBindingUpsertWithWhereUniqueWithoutProviderInput = {
  where: Prisma.ModelBindingWhereUniqueInput
  update: Prisma.XOR<Prisma.ModelBindingUpdateWithoutProviderInput, Prisma.ModelBindingUncheckedUpdateWithoutProviderInput>
  create: Prisma.XOR<Prisma.ModelBindingCreateWithoutProviderInput, Prisma.ModelBindingUncheckedCreateWithoutProviderInput>
}

export type ModelBindingUpdateWithWhereUniqueWithoutProviderInput = {
  where: Prisma.ModelBindingWhereUniqueInput
  data: Prisma.XOR<Prisma.ModelBindingUpdateWithoutProviderInput, Prisma.ModelBindingUncheckedUpdateWithoutProviderInput>
}

export type ModelBindingUpdateManyWithWhereWithoutProviderInput = {
  where: Prisma.ModelBindingScalarWhereInput
  data: Prisma.XOR<Prisma.ModelBindingUpdateManyMutationInput, Prisma.ModelBindingUncheckedUpdateManyWithoutProviderInput>
}

export type ModelBindingScalarWhereInput = {
  AND?: Prisma.ModelBindingScalarWhereInput | Prisma.ModelBindingScalarWhereInput[]
  OR?: Prisma.ModelBindingScalarWhereInput[]
  NOT?: Prisma.ModelBindingScalarWhereInput | Prisma.ModelBindingScalarWhereInput[]
  id?: Prisma.StringFilter<"ModelBinding"> | string
  logicalModelId?: Prisma.StringFilter<"ModelBinding"> | string
  providerId?: Prisma.StringFilter<"ModelBinding"> | string
  protocol?: Prisma.StringFilter<"ModelBinding"> | string
  upstreamUrl?: Prisma.StringFilter<"ModelBinding"> | string
  upstreamModelId?: Prisma.StringFilter<"ModelBinding"> | string
  priority?: Prisma.IntFilter<"ModelBinding"> | number
  enabled?: Prisma.BoolFilter<"ModelBinding"> | boolean
  customAuthHeader?: Prisma.StringNullableFilter<"ModelBinding"> | string | null
  createdTime?: Prisma.BigIntFilter<"ModelBinding"> | bigint | number
  updatedTime?: Prisma.BigIntFilter<"ModelBinding"> | bigint | number
  deletedTime?: Prisma.BigIntNullableFilter<"ModelBinding"> | bigint | number | null
}

export type ModelBindingCreateWithoutLogicalModelInput = {
  id: string
  protocol: string
  upstreamUrl: string
  upstreamModelId: string
  priority: number
  enabled?: boolean
  customAuthHeader?: string | null
  createdTime: bigint | number
  updatedTime: bigint | number
  deletedTime?: bigint | number | null
  provider: Prisma.ProviderCreateNestedOneWithoutBindingsInput
  attempts?: Prisma.RequestAttemptCreateNestedManyWithoutBindingInput
}

export type ModelBindingUncheckedCreateWithoutLogicalModelInput = {
  id: string
  providerId: string
  protocol: string
  upstreamUrl: string
  upstreamModelId: string
  priority: number
  enabled?: boolean
  customAuthHeader?: string | null
  createdTime: bigint | number
  updatedTime: bigint | number
  deletedTime?: bigint | number | null
  attempts?: Prisma.RequestAttemptUncheckedCreateNestedManyWithoutBindingInput
}

export type ModelBindingCreateOrConnectWithoutLogicalModelInput = {
  where: Prisma.ModelBindingWhereUniqueInput
  create: Prisma.XOR<Prisma.ModelBindingCreateWithoutLogicalModelInput, Prisma.ModelBindingUncheckedCreateWithoutLogicalModelInput>
}

export type ModelBindingCreateManyLogicalModelInputEnvelope = {
  data: Prisma.ModelBindingCreateManyLogicalModelInput | Prisma.ModelBindingCreateManyLogicalModelInput[]
}

export type ModelBindingUpsertWithWhereUniqueWithoutLogicalModelInput = {
  where: Prisma.ModelBindingWhereUniqueInput
  update: Prisma.XOR<Prisma.ModelBindingUpdateWithoutLogicalModelInput, Prisma.ModelBindingUncheckedUpdateWithoutLogicalModelInput>
  create: Prisma.XOR<Prisma.ModelBindingCreateWithoutLogicalModelInput, Prisma.ModelBindingUncheckedCreateWithoutLogicalModelInput>
}

export type ModelBindingUpdateWithWhereUniqueWithoutLogicalModelInput = {
  where: Prisma.ModelBindingWhereUniqueInput
  data: Prisma.XOR<Prisma.ModelBindingUpdateWithoutLogicalModelInput, Prisma.ModelBindingUncheckedUpdateWithoutLogicalModelInput>
}

export type ModelBindingUpdateManyWithWhereWithoutLogicalModelInput = {
  where: Prisma.ModelBindingScalarWhereInput
  data: Prisma.XOR<Prisma.ModelBindingUpdateManyMutationInput, Prisma.ModelBindingUncheckedUpdateManyWithoutLogicalModelInput>
}

export type ModelBindingCreateWithoutAttemptsInput = {
  id: string
  protocol: string
  upstreamUrl: string
  upstreamModelId: string
  priority: number
  enabled?: boolean
  customAuthHeader?: string | null
  createdTime: bigint | number
  updatedTime: bigint | number
  deletedTime?: bigint | number | null
  logicalModel: Prisma.LogicalModelCreateNestedOneWithoutBindingsInput
  provider: Prisma.ProviderCreateNestedOneWithoutBindingsInput
}

export type ModelBindingUncheckedCreateWithoutAttemptsInput = {
  id: string
  logicalModelId: string
  providerId: string
  protocol: string
  upstreamUrl: string
  upstreamModelId: string
  priority: number
  enabled?: boolean
  customAuthHeader?: string | null
  createdTime: bigint | number
  updatedTime: bigint | number
  deletedTime?: bigint | number | null
}

export type ModelBindingCreateOrConnectWithoutAttemptsInput = {
  where: Prisma.ModelBindingWhereUniqueInput
  create: Prisma.XOR<Prisma.ModelBindingCreateWithoutAttemptsInput, Prisma.ModelBindingUncheckedCreateWithoutAttemptsInput>
}

export type ModelBindingUpsertWithoutAttemptsInput = {
  update: Prisma.XOR<Prisma.ModelBindingUpdateWithoutAttemptsInput, Prisma.ModelBindingUncheckedUpdateWithoutAttemptsInput>
  create: Prisma.XOR<Prisma.ModelBindingCreateWithoutAttemptsInput, Prisma.ModelBindingUncheckedCreateWithoutAttemptsInput>
  where?: Prisma.ModelBindingWhereInput
}

export type ModelBindingUpdateToOneWithWhereWithoutAttemptsInput = {
  where?: Prisma.ModelBindingWhereInput
  data: Prisma.XOR<Prisma.ModelBindingUpdateWithoutAttemptsInput, Prisma.ModelBindingUncheckedUpdateWithoutAttemptsInput>
}

export type ModelBindingUpdateWithoutAttemptsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  protocol?: Prisma.StringFieldUpdateOperationsInput | string
  upstreamUrl?: Prisma.StringFieldUpdateOperationsInput | string
  upstreamModelId?: Prisma.StringFieldUpdateOperationsInput | string
  priority?: Prisma.IntFieldUpdateOperationsInput | number
  enabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  customAuthHeader?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdTime?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  updatedTime?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  deletedTime?: Prisma.NullableBigIntFieldUpdateOperationsInput | bigint | number | null
  logicalModel?: Prisma.LogicalModelUpdateOneRequiredWithoutBindingsNestedInput
  provider?: Prisma.ProviderUpdateOneRequiredWithoutBindingsNestedInput
}

export type ModelBindingUncheckedUpdateWithoutAttemptsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  logicalModelId?: Prisma.StringFieldUpdateOperationsInput | string
  providerId?: Prisma.StringFieldUpdateOperationsInput | string
  protocol?: Prisma.StringFieldUpdateOperationsInput | string
  upstreamUrl?: Prisma.StringFieldUpdateOperationsInput | string
  upstreamModelId?: Prisma.StringFieldUpdateOperationsInput | string
  priority?: Prisma.IntFieldUpdateOperationsInput | number
  enabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  customAuthHeader?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdTime?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  updatedTime?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  deletedTime?: Prisma.NullableBigIntFieldUpdateOperationsInput | bigint | number | null
}

export type ModelBindingCreateManyProviderInput = {
  id: string
  logicalModelId: string
  protocol: string
  upstreamUrl: string
  upstreamModelId: string
  priority: number
  enabled?: boolean
  customAuthHeader?: string | null
  createdTime: bigint | number
  updatedTime: bigint | number
  deletedTime?: bigint | number | null
}

export type ModelBindingUpdateWithoutProviderInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  protocol?: Prisma.StringFieldUpdateOperationsInput | string
  upstreamUrl?: Prisma.StringFieldUpdateOperationsInput | string
  upstreamModelId?: Prisma.StringFieldUpdateOperationsInput | string
  priority?: Prisma.IntFieldUpdateOperationsInput | number
  enabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  customAuthHeader?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdTime?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  updatedTime?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  deletedTime?: Prisma.NullableBigIntFieldUpdateOperationsInput | bigint | number | null
  logicalModel?: Prisma.LogicalModelUpdateOneRequiredWithoutBindingsNestedInput
  attempts?: Prisma.RequestAttemptUpdateManyWithoutBindingNestedInput
}

export type ModelBindingUncheckedUpdateWithoutProviderInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  logicalModelId?: Prisma.StringFieldUpdateOperationsInput | string
  protocol?: Prisma.StringFieldUpdateOperationsInput | string
  upstreamUrl?: Prisma.StringFieldUpdateOperationsInput | string
  upstreamModelId?: Prisma.StringFieldUpdateOperationsInput | string
  priority?: Prisma.IntFieldUpdateOperationsInput | number
  enabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  customAuthHeader?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdTime?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  updatedTime?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  deletedTime?: Prisma.NullableBigIntFieldUpdateOperationsInput | bigint | number | null
  attempts?: Prisma.RequestAttemptUncheckedUpdateManyWithoutBindingNestedInput
}

export type ModelBindingUncheckedUpdateManyWithoutProviderInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  logicalModelId?: Prisma.StringFieldUpdateOperationsInput | string
  protocol?: Prisma.StringFieldUpdateOperationsInput | string
  upstreamUrl?: Prisma.StringFieldUpdateOperationsInput | string
  upstreamModelId?: Prisma.StringFieldUpdateOperationsInput | string
  priority?: Prisma.IntFieldUpdateOperationsInput | number
  enabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  customAuthHeader?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdTime?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  updatedTime?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  deletedTime?: Prisma.NullableBigIntFieldUpdateOperationsInput | bigint | number | null
}

export type ModelBindingCreateManyLogicalModelInput = {
  id: string
  providerId: string
  protocol: string
  upstreamUrl: string
  upstreamModelId: string
  priority: number
  enabled?: boolean
  customAuthHeader?: string | null
  createdTime: bigint | number
  updatedTime: bigint | number
  deletedTime?: bigint | number | null
}

export type ModelBindingUpdateWithoutLogicalModelInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  protocol?: Prisma.StringFieldUpdateOperationsInput | string
  upstreamUrl?: Prisma.StringFieldUpdateOperationsInput | string
  upstreamModelId?: Prisma.StringFieldUpdateOperationsInput | string
  priority?: Prisma.IntFieldUpdateOperationsInput | number
  enabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  customAuthHeader?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdTime?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  updatedTime?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  deletedTime?: Prisma.NullableBigIntFieldUpdateOperationsInput | bigint | number | null
  provider?: Prisma.ProviderUpdateOneRequiredWithoutBindingsNestedInput
  attempts?: Prisma.RequestAttemptUpdateManyWithoutBindingNestedInput
}

export type ModelBindingUncheckedUpdateWithoutLogicalModelInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  providerId?: Prisma.StringFieldUpdateOperationsInput | string
  protocol?: Prisma.StringFieldUpdateOperationsInput | string
  upstreamUrl?: Prisma.StringFieldUpdateOperationsInput | string
  upstreamModelId?: Prisma.StringFieldUpdateOperationsInput | string
  priority?: Prisma.IntFieldUpdateOperationsInput | number
  enabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  customAuthHeader?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdTime?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  updatedTime?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  deletedTime?: Prisma.NullableBigIntFieldUpdateOperationsInput | bigint | number | null
  attempts?: Prisma.RequestAttemptUncheckedUpdateManyWithoutBindingNestedInput
}

export type ModelBindingUncheckedUpdateManyWithoutLogicalModelInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  providerId?: Prisma.StringFieldUpdateOperationsInput | string
  protocol?: Prisma.StringFieldUpdateOperationsInput | string
  upstreamUrl?: Prisma.StringFieldUpdateOperationsInput | string
  upstreamModelId?: Prisma.StringFieldUpdateOperationsInput | string
  priority?: Prisma.IntFieldUpdateOperationsInput | number
  enabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  customAuthHeader?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdTime?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  updatedTime?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  deletedTime?: Prisma.NullableBigIntFieldUpdateOperationsInput | bigint | number | null
}


/**
 * Count Type ModelBindingCountOutputType
 */

export type ModelBindingCountOutputType = {
  attempts: number
}

export type ModelBindingCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  attempts?: boolean | ModelBindingCountOutputTypeCountAttemptsArgs
}

/**
 * ModelBindingCountOutputType without action
 */
export type ModelBindingCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ModelBindingCountOutputType
   */
  select?: Prisma.ModelBindingCountOutputTypeSelect<ExtArgs> | null
}

/**
 * ModelBindingCountOutputType without action
 */
export type ModelBindingCountOutputTypeCountAttemptsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.RequestAttemptWhereInput
}


export type ModelBindingSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  logicalModelId?: boolean
  providerId?: boolean
  protocol?: boolean
  upstreamUrl?: boolean
  upstreamModelId?: boolean
  priority?: boolean
  enabled?: boolean
  customAuthHeader?: boolean
  createdTime?: boolean
  updatedTime?: boolean
  deletedTime?: boolean
  logicalModel?: boolean | Prisma.LogicalModelDefaultArgs<ExtArgs>
  provider?: boolean | Prisma.ProviderDefaultArgs<ExtArgs>
  attempts?: boolean | Prisma.ModelBinding$attemptsArgs<ExtArgs>
  _count?: boolean | Prisma.ModelBindingCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["modelBinding"]>

export type ModelBindingSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  logicalModelId?: boolean
  providerId?: boolean
  protocol?: boolean
  upstreamUrl?: boolean
  upstreamModelId?: boolean
  priority?: boolean
  enabled?: boolean
  customAuthHeader?: boolean
  createdTime?: boolean
  updatedTime?: boolean
  deletedTime?: boolean
  logicalModel?: boolean | Prisma.LogicalModelDefaultArgs<ExtArgs>
  provider?: boolean | Prisma.ProviderDefaultArgs<ExtArgs>
}, ExtArgs["result"]["modelBinding"]>

export type ModelBindingSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  logicalModelId?: boolean
  providerId?: boolean
  protocol?: boolean
  upstreamUrl?: boolean
  upstreamModelId?: boolean
  priority?: boolean
  enabled?: boolean
  customAuthHeader?: boolean
  createdTime?: boolean
  updatedTime?: boolean
  deletedTime?: boolean
  logicalModel?: boolean | Prisma.LogicalModelDefaultArgs<ExtArgs>
  provider?: boolean | Prisma.ProviderDefaultArgs<ExtArgs>
}, ExtArgs["result"]["modelBinding"]>

export type ModelBindingSelectScalar = {
  id?: boolean
  logicalModelId?: boolean
  providerId?: boolean
  protocol?: boolean
  upstreamUrl?: boolean
  upstreamModelId?: boolean
  priority?: boolean
  enabled?: boolean
  customAuthHeader?: boolean
  createdTime?: boolean
  updatedTime?: boolean
  deletedTime?: boolean
}

export type ModelBindingOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "logicalModelId" | "providerId" | "protocol" | "upstreamUrl" | "upstreamModelId" | "priority" | "enabled" | "customAuthHeader" | "createdTime" | "updatedTime" | "deletedTime", ExtArgs["result"]["modelBinding"]>
export type ModelBindingInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  logicalModel?: boolean | Prisma.LogicalModelDefaultArgs<ExtArgs>
  provider?: boolean | Prisma.ProviderDefaultArgs<ExtArgs>
  attempts?: boolean | Prisma.ModelBinding$attemptsArgs<ExtArgs>
  _count?: boolean | Prisma.ModelBindingCountOutputTypeDefaultArgs<ExtArgs>
}
export type ModelBindingIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  logicalModel?: boolean | Prisma.LogicalModelDefaultArgs<ExtArgs>
  provider?: boolean | Prisma.ProviderDefaultArgs<ExtArgs>
}
export type ModelBindingIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  logicalModel?: boolean | Prisma.LogicalModelDefaultArgs<ExtArgs>
  provider?: boolean | Prisma.ProviderDefaultArgs<ExtArgs>
}

export type $ModelBindingPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ModelBinding"
  objects: {
    logicalModel: Prisma.$LogicalModelPayload<ExtArgs>
    provider: Prisma.$ProviderPayload<ExtArgs>
    attempts: Prisma.$RequestAttemptPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    logicalModelId: string
    providerId: string
    protocol: string
    upstreamUrl: string
    upstreamModelId: string
    priority: number
    enabled: boolean
    customAuthHeader: string | null
    createdTime: bigint
    updatedTime: bigint
    deletedTime: bigint | null
  }, ExtArgs["result"]["modelBinding"]>
  composites: {}
}

export type ModelBindingGetPayload<S extends boolean | null | undefined | ModelBindingDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ModelBindingPayload, S>

export type ModelBindingCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ModelBindingFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ModelBindingCountAggregateInputType | true
  }

export interface ModelBindingDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ModelBinding'], meta: { name: 'ModelBinding' } }
  /**
   * Find zero or one ModelBinding that matches the filter.
   * @param {ModelBindingFindUniqueArgs} args - Arguments to find a ModelBinding
   * @example
   * // Get one ModelBinding
   * const modelBinding = await prisma.modelBinding.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ModelBindingFindUniqueArgs>(args: Prisma.SelectSubset<T, ModelBindingFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ModelBindingClient<runtime.Types.Result.GetResult<Prisma.$ModelBindingPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ModelBinding that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ModelBindingFindUniqueOrThrowArgs} args - Arguments to find a ModelBinding
   * @example
   * // Get one ModelBinding
   * const modelBinding = await prisma.modelBinding.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ModelBindingFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ModelBindingFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ModelBindingClient<runtime.Types.Result.GetResult<Prisma.$ModelBindingPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ModelBinding that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ModelBindingFindFirstArgs} args - Arguments to find a ModelBinding
   * @example
   * // Get one ModelBinding
   * const modelBinding = await prisma.modelBinding.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ModelBindingFindFirstArgs>(args?: Prisma.SelectSubset<T, ModelBindingFindFirstArgs<ExtArgs>>): Prisma.Prisma__ModelBindingClient<runtime.Types.Result.GetResult<Prisma.$ModelBindingPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ModelBinding that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ModelBindingFindFirstOrThrowArgs} args - Arguments to find a ModelBinding
   * @example
   * // Get one ModelBinding
   * const modelBinding = await prisma.modelBinding.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ModelBindingFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ModelBindingFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ModelBindingClient<runtime.Types.Result.GetResult<Prisma.$ModelBindingPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ModelBindings that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ModelBindingFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ModelBindings
   * const modelBindings = await prisma.modelBinding.findMany()
   * 
   * // Get first 10 ModelBindings
   * const modelBindings = await prisma.modelBinding.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const modelBindingWithIdOnly = await prisma.modelBinding.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ModelBindingFindManyArgs>(args?: Prisma.SelectSubset<T, ModelBindingFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ModelBindingPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ModelBinding.
   * @param {ModelBindingCreateArgs} args - Arguments to create a ModelBinding.
   * @example
   * // Create one ModelBinding
   * const ModelBinding = await prisma.modelBinding.create({
   *   data: {
   *     // ... data to create a ModelBinding
   *   }
   * })
   * 
   */
  create<T extends ModelBindingCreateArgs>(args: Prisma.SelectSubset<T, ModelBindingCreateArgs<ExtArgs>>): Prisma.Prisma__ModelBindingClient<runtime.Types.Result.GetResult<Prisma.$ModelBindingPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ModelBindings.
   * @param {ModelBindingCreateManyArgs} args - Arguments to create many ModelBindings.
   * @example
   * // Create many ModelBindings
   * const modelBinding = await prisma.modelBinding.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ModelBindingCreateManyArgs>(args?: Prisma.SelectSubset<T, ModelBindingCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ModelBindings and returns the data saved in the database.
   * @param {ModelBindingCreateManyAndReturnArgs} args - Arguments to create many ModelBindings.
   * @example
   * // Create many ModelBindings
   * const modelBinding = await prisma.modelBinding.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ModelBindings and only return the `id`
   * const modelBindingWithIdOnly = await prisma.modelBinding.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ModelBindingCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ModelBindingCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ModelBindingPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ModelBinding.
   * @param {ModelBindingDeleteArgs} args - Arguments to delete one ModelBinding.
   * @example
   * // Delete one ModelBinding
   * const ModelBinding = await prisma.modelBinding.delete({
   *   where: {
   *     // ... filter to delete one ModelBinding
   *   }
   * })
   * 
   */
  delete<T extends ModelBindingDeleteArgs>(args: Prisma.SelectSubset<T, ModelBindingDeleteArgs<ExtArgs>>): Prisma.Prisma__ModelBindingClient<runtime.Types.Result.GetResult<Prisma.$ModelBindingPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ModelBinding.
   * @param {ModelBindingUpdateArgs} args - Arguments to update one ModelBinding.
   * @example
   * // Update one ModelBinding
   * const modelBinding = await prisma.modelBinding.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ModelBindingUpdateArgs>(args: Prisma.SelectSubset<T, ModelBindingUpdateArgs<ExtArgs>>): Prisma.Prisma__ModelBindingClient<runtime.Types.Result.GetResult<Prisma.$ModelBindingPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ModelBindings.
   * @param {ModelBindingDeleteManyArgs} args - Arguments to filter ModelBindings to delete.
   * @example
   * // Delete a few ModelBindings
   * const { count } = await prisma.modelBinding.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ModelBindingDeleteManyArgs>(args?: Prisma.SelectSubset<T, ModelBindingDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ModelBindings.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ModelBindingUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ModelBindings
   * const modelBinding = await prisma.modelBinding.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ModelBindingUpdateManyArgs>(args: Prisma.SelectSubset<T, ModelBindingUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ModelBindings and returns the data updated in the database.
   * @param {ModelBindingUpdateManyAndReturnArgs} args - Arguments to update many ModelBindings.
   * @example
   * // Update many ModelBindings
   * const modelBinding = await prisma.modelBinding.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ModelBindings and only return the `id`
   * const modelBindingWithIdOnly = await prisma.modelBinding.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ModelBindingUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ModelBindingUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ModelBindingPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ModelBinding.
   * @param {ModelBindingUpsertArgs} args - Arguments to update or create a ModelBinding.
   * @example
   * // Update or create a ModelBinding
   * const modelBinding = await prisma.modelBinding.upsert({
   *   create: {
   *     // ... data to create a ModelBinding
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ModelBinding we want to update
   *   }
   * })
   */
  upsert<T extends ModelBindingUpsertArgs>(args: Prisma.SelectSubset<T, ModelBindingUpsertArgs<ExtArgs>>): Prisma.Prisma__ModelBindingClient<runtime.Types.Result.GetResult<Prisma.$ModelBindingPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ModelBindings.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ModelBindingCountArgs} args - Arguments to filter ModelBindings to count.
   * @example
   * // Count the number of ModelBindings
   * const count = await prisma.modelBinding.count({
   *   where: {
   *     // ... the filter for the ModelBindings we want to count
   *   }
   * })
  **/
  count<T extends ModelBindingCountArgs>(
    args?: Prisma.Subset<T, ModelBindingCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ModelBindingCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ModelBinding.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ModelBindingAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ModelBindingAggregateArgs>(args: Prisma.Subset<T, ModelBindingAggregateArgs>): Prisma.PrismaPromise<GetModelBindingAggregateType<T>>

  /**
   * Group by ModelBinding.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ModelBindingGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ModelBindingGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ModelBindingGroupByArgs['orderBy'] }
      : { orderBy?: ModelBindingGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ModelBindingGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetModelBindingGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ModelBinding model
 */
readonly fields: ModelBindingFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ModelBinding.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ModelBindingClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  logicalModel<T extends Prisma.LogicalModelDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.LogicalModelDefaultArgs<ExtArgs>>): Prisma.Prisma__LogicalModelClient<runtime.Types.Result.GetResult<Prisma.$LogicalModelPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  provider<T extends Prisma.ProviderDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ProviderDefaultArgs<ExtArgs>>): Prisma.Prisma__ProviderClient<runtime.Types.Result.GetResult<Prisma.$ProviderPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  attempts<T extends Prisma.ModelBinding$attemptsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ModelBinding$attemptsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RequestAttemptPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ModelBinding model
 */
export interface ModelBindingFieldRefs {
  readonly id: Prisma.FieldRef<"ModelBinding", 'String'>
  readonly logicalModelId: Prisma.FieldRef<"ModelBinding", 'String'>
  readonly providerId: Prisma.FieldRef<"ModelBinding", 'String'>
  readonly protocol: Prisma.FieldRef<"ModelBinding", 'String'>
  readonly upstreamUrl: Prisma.FieldRef<"ModelBinding", 'String'>
  readonly upstreamModelId: Prisma.FieldRef<"ModelBinding", 'String'>
  readonly priority: Prisma.FieldRef<"ModelBinding", 'Int'>
  readonly enabled: Prisma.FieldRef<"ModelBinding", 'Boolean'>
  readonly customAuthHeader: Prisma.FieldRef<"ModelBinding", 'String'>
  readonly createdTime: Prisma.FieldRef<"ModelBinding", 'BigInt'>
  readonly updatedTime: Prisma.FieldRef<"ModelBinding", 'BigInt'>
  readonly deletedTime: Prisma.FieldRef<"ModelBinding", 'BigInt'>
}
    

// Custom InputTypes
/**
 * ModelBinding findUnique
 */
export type ModelBindingFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ModelBinding
   */
  select?: Prisma.ModelBindingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ModelBinding
   */
  omit?: Prisma.ModelBindingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ModelBindingInclude<ExtArgs> | null
  /**
   * Filter, which ModelBinding to fetch.
   */
  where: Prisma.ModelBindingWhereUniqueInput
}

/**
 * ModelBinding findUniqueOrThrow
 */
export type ModelBindingFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ModelBinding
   */
  select?: Prisma.ModelBindingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ModelBinding
   */
  omit?: Prisma.ModelBindingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ModelBindingInclude<ExtArgs> | null
  /**
   * Filter, which ModelBinding to fetch.
   */
  where: Prisma.ModelBindingWhereUniqueInput
}

/**
 * ModelBinding findFirst
 */
export type ModelBindingFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ModelBinding
   */
  select?: Prisma.ModelBindingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ModelBinding
   */
  omit?: Prisma.ModelBindingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ModelBindingInclude<ExtArgs> | null
  /**
   * Filter, which ModelBinding to fetch.
   */
  where?: Prisma.ModelBindingWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ModelBindings to fetch.
   */
  orderBy?: Prisma.ModelBindingOrderByWithRelationInput | Prisma.ModelBindingOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ModelBindings.
   */
  cursor?: Prisma.ModelBindingWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ModelBindings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ModelBindings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ModelBindings.
   */
  distinct?: Prisma.ModelBindingScalarFieldEnum | Prisma.ModelBindingScalarFieldEnum[]
}

/**
 * ModelBinding findFirstOrThrow
 */
export type ModelBindingFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ModelBinding
   */
  select?: Prisma.ModelBindingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ModelBinding
   */
  omit?: Prisma.ModelBindingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ModelBindingInclude<ExtArgs> | null
  /**
   * Filter, which ModelBinding to fetch.
   */
  where?: Prisma.ModelBindingWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ModelBindings to fetch.
   */
  orderBy?: Prisma.ModelBindingOrderByWithRelationInput | Prisma.ModelBindingOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ModelBindings.
   */
  cursor?: Prisma.ModelBindingWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ModelBindings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ModelBindings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ModelBindings.
   */
  distinct?: Prisma.ModelBindingScalarFieldEnum | Prisma.ModelBindingScalarFieldEnum[]
}

/**
 * ModelBinding findMany
 */
export type ModelBindingFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ModelBinding
   */
  select?: Prisma.ModelBindingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ModelBinding
   */
  omit?: Prisma.ModelBindingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ModelBindingInclude<ExtArgs> | null
  /**
   * Filter, which ModelBindings to fetch.
   */
  where?: Prisma.ModelBindingWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ModelBindings to fetch.
   */
  orderBy?: Prisma.ModelBindingOrderByWithRelationInput | Prisma.ModelBindingOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ModelBindings.
   */
  cursor?: Prisma.ModelBindingWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ModelBindings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ModelBindings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ModelBindings.
   */
  distinct?: Prisma.ModelBindingScalarFieldEnum | Prisma.ModelBindingScalarFieldEnum[]
}

/**
 * ModelBinding create
 */
export type ModelBindingCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ModelBinding
   */
  select?: Prisma.ModelBindingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ModelBinding
   */
  omit?: Prisma.ModelBindingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ModelBindingInclude<ExtArgs> | null
  /**
   * The data needed to create a ModelBinding.
   */
  data: Prisma.XOR<Prisma.ModelBindingCreateInput, Prisma.ModelBindingUncheckedCreateInput>
}

/**
 * ModelBinding createMany
 */
export type ModelBindingCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ModelBindings.
   */
  data: Prisma.ModelBindingCreateManyInput | Prisma.ModelBindingCreateManyInput[]
}

/**
 * ModelBinding createManyAndReturn
 */
export type ModelBindingCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ModelBinding
   */
  select?: Prisma.ModelBindingSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ModelBinding
   */
  omit?: Prisma.ModelBindingOmit<ExtArgs> | null
  /**
   * The data used to create many ModelBindings.
   */
  data: Prisma.ModelBindingCreateManyInput | Prisma.ModelBindingCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ModelBindingIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * ModelBinding update
 */
export type ModelBindingUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ModelBinding
   */
  select?: Prisma.ModelBindingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ModelBinding
   */
  omit?: Prisma.ModelBindingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ModelBindingInclude<ExtArgs> | null
  /**
   * The data needed to update a ModelBinding.
   */
  data: Prisma.XOR<Prisma.ModelBindingUpdateInput, Prisma.ModelBindingUncheckedUpdateInput>
  /**
   * Choose, which ModelBinding to update.
   */
  where: Prisma.ModelBindingWhereUniqueInput
}

/**
 * ModelBinding updateMany
 */
export type ModelBindingUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ModelBindings.
   */
  data: Prisma.XOR<Prisma.ModelBindingUpdateManyMutationInput, Prisma.ModelBindingUncheckedUpdateManyInput>
  /**
   * Filter which ModelBindings to update
   */
  where?: Prisma.ModelBindingWhereInput
  /**
   * Limit how many ModelBindings to update.
   */
  limit?: number
}

/**
 * ModelBinding updateManyAndReturn
 */
export type ModelBindingUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ModelBinding
   */
  select?: Prisma.ModelBindingSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ModelBinding
   */
  omit?: Prisma.ModelBindingOmit<ExtArgs> | null
  /**
   * The data used to update ModelBindings.
   */
  data: Prisma.XOR<Prisma.ModelBindingUpdateManyMutationInput, Prisma.ModelBindingUncheckedUpdateManyInput>
  /**
   * Filter which ModelBindings to update
   */
  where?: Prisma.ModelBindingWhereInput
  /**
   * Limit how many ModelBindings to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ModelBindingIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * ModelBinding upsert
 */
export type ModelBindingUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ModelBinding
   */
  select?: Prisma.ModelBindingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ModelBinding
   */
  omit?: Prisma.ModelBindingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ModelBindingInclude<ExtArgs> | null
  /**
   * The filter to search for the ModelBinding to update in case it exists.
   */
  where: Prisma.ModelBindingWhereUniqueInput
  /**
   * In case the ModelBinding found by the `where` argument doesn't exist, create a new ModelBinding with this data.
   */
  create: Prisma.XOR<Prisma.ModelBindingCreateInput, Prisma.ModelBindingUncheckedCreateInput>
  /**
   * In case the ModelBinding was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ModelBindingUpdateInput, Prisma.ModelBindingUncheckedUpdateInput>
}

/**
 * ModelBinding delete
 */
export type ModelBindingDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ModelBinding
   */
  select?: Prisma.ModelBindingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ModelBinding
   */
  omit?: Prisma.ModelBindingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ModelBindingInclude<ExtArgs> | null
  /**
   * Filter which ModelBinding to delete.
   */
  where: Prisma.ModelBindingWhereUniqueInput
}

/**
 * ModelBinding deleteMany
 */
export type ModelBindingDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ModelBindings to delete
   */
  where?: Prisma.ModelBindingWhereInput
  /**
   * Limit how many ModelBindings to delete.
   */
  limit?: number
}

/**
 * ModelBinding.attempts
 */
export type ModelBinding$attemptsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RequestAttempt
   */
  select?: Prisma.RequestAttemptSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RequestAttempt
   */
  omit?: Prisma.RequestAttemptOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RequestAttemptInclude<ExtArgs> | null
  where?: Prisma.RequestAttemptWhereInput
  orderBy?: Prisma.RequestAttemptOrderByWithRelationInput | Prisma.RequestAttemptOrderByWithRelationInput[]
  cursor?: Prisma.RequestAttemptWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.RequestAttemptScalarFieldEnum | Prisma.RequestAttemptScalarFieldEnum[]
}

/**
 * ModelBinding without action
 */
export type ModelBindingDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ModelBinding
   */
  select?: Prisma.ModelBindingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ModelBinding
   */
  omit?: Prisma.ModelBindingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ModelBindingInclude<ExtArgs> | null
}
