
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ProviderHealth` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model ProviderHealth
 * 
 */
export type ProviderHealthModel = runtime.Types.Result.DefaultSelection<Prisma.$ProviderHealthPayload>

export type AggregateProviderHealth = {
  _count: ProviderHealthCountAggregateOutputType | null
  _avg: ProviderHealthAvgAggregateOutputType | null
  _sum: ProviderHealthSumAggregateOutputType | null
  _min: ProviderHealthMinAggregateOutputType | null
  _max: ProviderHealthMaxAggregateOutputType | null
}

export type ProviderHealthAvgAggregateOutputType = {
  consecutiveFailures: number | null
  cooldownUntilTime: number | null
  lastSuccessTime: number | null
  lastFailureTime: number | null
  updatedTime: number | null
}

export type ProviderHealthSumAggregateOutputType = {
  consecutiveFailures: number | null
  cooldownUntilTime: bigint | null
  lastSuccessTime: bigint | null
  lastFailureTime: bigint | null
  updatedTime: bigint | null
}

export type ProviderHealthMinAggregateOutputType = {
  providerId: string | null
  consecutiveFailures: number | null
  cooldownUntilTime: bigint | null
  lastSuccessTime: bigint | null
  lastFailureTime: bigint | null
  updatedTime: bigint | null
}

export type ProviderHealthMaxAggregateOutputType = {
  providerId: string | null
  consecutiveFailures: number | null
  cooldownUntilTime: bigint | null
  lastSuccessTime: bigint | null
  lastFailureTime: bigint | null
  updatedTime: bigint | null
}

export type ProviderHealthCountAggregateOutputType = {
  providerId: number
  consecutiveFailures: number
  cooldownUntilTime: number
  lastSuccessTime: number
  lastFailureTime: number
  updatedTime: number
  _all: number
}


export type ProviderHealthAvgAggregateInputType = {
  consecutiveFailures?: true
  cooldownUntilTime?: true
  lastSuccessTime?: true
  lastFailureTime?: true
  updatedTime?: true
}

export type ProviderHealthSumAggregateInputType = {
  consecutiveFailures?: true
  cooldownUntilTime?: true
  lastSuccessTime?: true
  lastFailureTime?: true
  updatedTime?: true
}

export type ProviderHealthMinAggregateInputType = {
  providerId?: true
  consecutiveFailures?: true
  cooldownUntilTime?: true
  lastSuccessTime?: true
  lastFailureTime?: true
  updatedTime?: true
}

export type ProviderHealthMaxAggregateInputType = {
  providerId?: true
  consecutiveFailures?: true
  cooldownUntilTime?: true
  lastSuccessTime?: true
  lastFailureTime?: true
  updatedTime?: true
}

export type ProviderHealthCountAggregateInputType = {
  providerId?: true
  consecutiveFailures?: true
  cooldownUntilTime?: true
  lastSuccessTime?: true
  lastFailureTime?: true
  updatedTime?: true
  _all?: true
}

export type ProviderHealthAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ProviderHealth to aggregate.
   */
  where?: Prisma.ProviderHealthWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ProviderHealths to fetch.
   */
  orderBy?: Prisma.ProviderHealthOrderByWithRelationInput | Prisma.ProviderHealthOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ProviderHealthWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ProviderHealths from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ProviderHealths.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ProviderHealths
  **/
  _count?: true | ProviderHealthCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: ProviderHealthAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: ProviderHealthSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ProviderHealthMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ProviderHealthMaxAggregateInputType
}

export type GetProviderHealthAggregateType<T extends ProviderHealthAggregateArgs> = {
      [P in keyof T & keyof AggregateProviderHealth]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateProviderHealth[P]>
    : Prisma.GetScalarType<T[P], AggregateProviderHealth[P]>
}




export type ProviderHealthGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ProviderHealthWhereInput
  orderBy?: Prisma.ProviderHealthOrderByWithAggregationInput | Prisma.ProviderHealthOrderByWithAggregationInput[]
  by: Prisma.ProviderHealthScalarFieldEnum[] | Prisma.ProviderHealthScalarFieldEnum
  having?: Prisma.ProviderHealthScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ProviderHealthCountAggregateInputType | true
  _avg?: ProviderHealthAvgAggregateInputType
  _sum?: ProviderHealthSumAggregateInputType
  _min?: ProviderHealthMinAggregateInputType
  _max?: ProviderHealthMaxAggregateInputType
}

export type ProviderHealthGroupByOutputType = {
  providerId: string
  consecutiveFailures: number
  cooldownUntilTime: bigint | null
  lastSuccessTime: bigint | null
  lastFailureTime: bigint | null
  updatedTime: bigint
  _count: ProviderHealthCountAggregateOutputType | null
  _avg: ProviderHealthAvgAggregateOutputType | null
  _sum: ProviderHealthSumAggregateOutputType | null
  _min: ProviderHealthMinAggregateOutputType | null
  _max: ProviderHealthMaxAggregateOutputType | null
}

export type GetProviderHealthGroupByPayload<T extends ProviderHealthGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ProviderHealthGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ProviderHealthGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ProviderHealthGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ProviderHealthGroupByOutputType[P]>
      }
    >
  >



export type ProviderHealthWhereInput = {
  AND?: Prisma.ProviderHealthWhereInput | Prisma.ProviderHealthWhereInput[]
  OR?: Prisma.ProviderHealthWhereInput[]
  NOT?: Prisma.ProviderHealthWhereInput | Prisma.ProviderHealthWhereInput[]
  providerId?: Prisma.StringFilter<"ProviderHealth"> | string
  consecutiveFailures?: Prisma.IntFilter<"ProviderHealth"> | number
  cooldownUntilTime?: Prisma.BigIntNullableFilter<"ProviderHealth"> | bigint | number | null
  lastSuccessTime?: Prisma.BigIntNullableFilter<"ProviderHealth"> | bigint | number | null
  lastFailureTime?: Prisma.BigIntNullableFilter<"ProviderHealth"> | bigint | number | null
  updatedTime?: Prisma.BigIntFilter<"ProviderHealth"> | bigint | number
  provider?: Prisma.XOR<Prisma.ProviderScalarRelationFilter, Prisma.ProviderWhereInput>
}

export type ProviderHealthOrderByWithRelationInput = {
  providerId?: Prisma.SortOrder
  consecutiveFailures?: Prisma.SortOrder
  cooldownUntilTime?: Prisma.SortOrderInput | Prisma.SortOrder
  lastSuccessTime?: Prisma.SortOrderInput | Prisma.SortOrder
  lastFailureTime?: Prisma.SortOrderInput | Prisma.SortOrder
  updatedTime?: Prisma.SortOrder
  provider?: Prisma.ProviderOrderByWithRelationInput
}

export type ProviderHealthWhereUniqueInput = Prisma.AtLeast<{
  providerId?: string
  AND?: Prisma.ProviderHealthWhereInput | Prisma.ProviderHealthWhereInput[]
  OR?: Prisma.ProviderHealthWhereInput[]
  NOT?: Prisma.ProviderHealthWhereInput | Prisma.ProviderHealthWhereInput[]
  consecutiveFailures?: Prisma.IntFilter<"ProviderHealth"> | number
  cooldownUntilTime?: Prisma.BigIntNullableFilter<"ProviderHealth"> | bigint | number | null
  lastSuccessTime?: Prisma.BigIntNullableFilter<"ProviderHealth"> | bigint | number | null
  lastFailureTime?: Prisma.BigIntNullableFilter<"ProviderHealth"> | bigint | number | null
  updatedTime?: Prisma.BigIntFilter<"ProviderHealth"> | bigint | number
  provider?: Prisma.XOR<Prisma.ProviderScalarRelationFilter, Prisma.ProviderWhereInput>
}, "providerId">

export type ProviderHealthOrderByWithAggregationInput = {
  providerId?: Prisma.SortOrder
  consecutiveFailures?: Prisma.SortOrder
  cooldownUntilTime?: Prisma.SortOrderInput | Prisma.SortOrder
  lastSuccessTime?: Prisma.SortOrderInput | Prisma.SortOrder
  lastFailureTime?: Prisma.SortOrderInput | Prisma.SortOrder
  updatedTime?: Prisma.SortOrder
  _count?: Prisma.ProviderHealthCountOrderByAggregateInput
  _avg?: Prisma.ProviderHealthAvgOrderByAggregateInput
  _max?: Prisma.ProviderHealthMaxOrderByAggregateInput
  _min?: Prisma.ProviderHealthMinOrderByAggregateInput
  _sum?: Prisma.ProviderHealthSumOrderByAggregateInput
}

export type ProviderHealthScalarWhereWithAggregatesInput = {
  AND?: Prisma.ProviderHealthScalarWhereWithAggregatesInput | Prisma.ProviderHealthScalarWhereWithAggregatesInput[]
  OR?: Prisma.ProviderHealthScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ProviderHealthScalarWhereWithAggregatesInput | Prisma.ProviderHealthScalarWhereWithAggregatesInput[]
  providerId?: Prisma.StringWithAggregatesFilter<"ProviderHealth"> | string
  consecutiveFailures?: Prisma.IntWithAggregatesFilter<"ProviderHealth"> | number
  cooldownUntilTime?: Prisma.BigIntNullableWithAggregatesFilter<"ProviderHealth"> | bigint | number | null
  lastSuccessTime?: Prisma.BigIntNullableWithAggregatesFilter<"ProviderHealth"> | bigint | number | null
  lastFailureTime?: Prisma.BigIntNullableWithAggregatesFilter<"ProviderHealth"> | bigint | number | null
  updatedTime?: Prisma.BigIntWithAggregatesFilter<"ProviderHealth"> | bigint | number
}

export type ProviderHealthCreateInput = {
  consecutiveFailures?: number
  cooldownUntilTime?: bigint | number | null
  lastSuccessTime?: bigint | number | null
  lastFailureTime?: bigint | number | null
  updatedTime: bigint | number
  provider: Prisma.ProviderCreateNestedOneWithoutHealthInput
}

export type ProviderHealthUncheckedCreateInput = {
  providerId: string
  consecutiveFailures?: number
  cooldownUntilTime?: bigint | number | null
  lastSuccessTime?: bigint | number | null
  lastFailureTime?: bigint | number | null
  updatedTime: bigint | number
}

export type ProviderHealthUpdateInput = {
  consecutiveFailures?: Prisma.IntFieldUpdateOperationsInput | number
  cooldownUntilTime?: Prisma.NullableBigIntFieldUpdateOperationsInput | bigint | number | null
  lastSuccessTime?: Prisma.NullableBigIntFieldUpdateOperationsInput | bigint | number | null
  lastFailureTime?: Prisma.NullableBigIntFieldUpdateOperationsInput | bigint | number | null
  updatedTime?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  provider?: Prisma.ProviderUpdateOneRequiredWithoutHealthNestedInput
}

export type ProviderHealthUncheckedUpdateInput = {
  providerId?: Prisma.StringFieldUpdateOperationsInput | string
  consecutiveFailures?: Prisma.IntFieldUpdateOperationsInput | number
  cooldownUntilTime?: Prisma.NullableBigIntFieldUpdateOperationsInput | bigint | number | null
  lastSuccessTime?: Prisma.NullableBigIntFieldUpdateOperationsInput | bigint | number | null
  lastFailureTime?: Prisma.NullableBigIntFieldUpdateOperationsInput | bigint | number | null
  updatedTime?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
}

export type ProviderHealthCreateManyInput = {
  providerId: string
  consecutiveFailures?: number
  cooldownUntilTime?: bigint | number | null
  lastSuccessTime?: bigint | number | null
  lastFailureTime?: bigint | number | null
  updatedTime: bigint | number
}

export type ProviderHealthUpdateManyMutationInput = {
  consecutiveFailures?: Prisma.IntFieldUpdateOperationsInput | number
  cooldownUntilTime?: Prisma.NullableBigIntFieldUpdateOperationsInput | bigint | number | null
  lastSuccessTime?: Prisma.NullableBigIntFieldUpdateOperationsInput | bigint | number | null
  lastFailureTime?: Prisma.NullableBigIntFieldUpdateOperationsInput | bigint | number | null
  updatedTime?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
}

export type ProviderHealthUncheckedUpdateManyInput = {
  providerId?: Prisma.StringFieldUpdateOperationsInput | string
  consecutiveFailures?: Prisma.IntFieldUpdateOperationsInput | number
  cooldownUntilTime?: Prisma.NullableBigIntFieldUpdateOperationsInput | bigint | number | null
  lastSuccessTime?: Prisma.NullableBigIntFieldUpdateOperationsInput | bigint | number | null
  lastFailureTime?: Prisma.NullableBigIntFieldUpdateOperationsInput | bigint | number | null
  updatedTime?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
}

export type ProviderHealthNullableScalarRelationFilter = {
  is?: Prisma.ProviderHealthWhereInput | null
  isNot?: Prisma.ProviderHealthWhereInput | null
}

export type ProviderHealthCountOrderByAggregateInput = {
  providerId?: Prisma.SortOrder
  consecutiveFailures?: Prisma.SortOrder
  cooldownUntilTime?: Prisma.SortOrder
  lastSuccessTime?: Prisma.SortOrder
  lastFailureTime?: Prisma.SortOrder
  updatedTime?: Prisma.SortOrder
}

export type ProviderHealthAvgOrderByAggregateInput = {
  consecutiveFailures?: Prisma.SortOrder
  cooldownUntilTime?: Prisma.SortOrder
  lastSuccessTime?: Prisma.SortOrder
  lastFailureTime?: Prisma.SortOrder
  updatedTime?: Prisma.SortOrder
}

export type ProviderHealthMaxOrderByAggregateInput = {
  providerId?: Prisma.SortOrder
  consecutiveFailures?: Prisma.SortOrder
  cooldownUntilTime?: Prisma.SortOrder
  lastSuccessTime?: Prisma.SortOrder
  lastFailureTime?: Prisma.SortOrder
  updatedTime?: Prisma.SortOrder
}

export type ProviderHealthMinOrderByAggregateInput = {
  providerId?: Prisma.SortOrder
  consecutiveFailures?: Prisma.SortOrder
  cooldownUntilTime?: Prisma.SortOrder
  lastSuccessTime?: Prisma.SortOrder
  lastFailureTime?: Prisma.SortOrder
  updatedTime?: Prisma.SortOrder
}

export type ProviderHealthSumOrderByAggregateInput = {
  consecutiveFailures?: Prisma.SortOrder
  cooldownUntilTime?: Prisma.SortOrder
  lastSuccessTime?: Prisma.SortOrder
  lastFailureTime?: Prisma.SortOrder
  updatedTime?: Prisma.SortOrder
}

export type ProviderHealthCreateNestedOneWithoutProviderInput = {
  create?: Prisma.XOR<Prisma.ProviderHealthCreateWithoutProviderInput, Prisma.ProviderHealthUncheckedCreateWithoutProviderInput>
  connectOrCreate?: Prisma.ProviderHealthCreateOrConnectWithoutProviderInput
  connect?: Prisma.ProviderHealthWhereUniqueInput
}

export type ProviderHealthUncheckedCreateNestedOneWithoutProviderInput = {
  create?: Prisma.XOR<Prisma.ProviderHealthCreateWithoutProviderInput, Prisma.ProviderHealthUncheckedCreateWithoutProviderInput>
  connectOrCreate?: Prisma.ProviderHealthCreateOrConnectWithoutProviderInput
  connect?: Prisma.ProviderHealthWhereUniqueInput
}

export type ProviderHealthUpdateOneWithoutProviderNestedInput = {
  create?: Prisma.XOR<Prisma.ProviderHealthCreateWithoutProviderInput, Prisma.ProviderHealthUncheckedCreateWithoutProviderInput>
  connectOrCreate?: Prisma.ProviderHealthCreateOrConnectWithoutProviderInput
  upsert?: Prisma.ProviderHealthUpsertWithoutProviderInput
  disconnect?: Prisma.ProviderHealthWhereInput | boolean
  delete?: Prisma.ProviderHealthWhereInput | boolean
  connect?: Prisma.ProviderHealthWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ProviderHealthUpdateToOneWithWhereWithoutProviderInput, Prisma.ProviderHealthUpdateWithoutProviderInput>, Prisma.ProviderHealthUncheckedUpdateWithoutProviderInput>
}

export type ProviderHealthUncheckedUpdateOneWithoutProviderNestedInput = {
  create?: Prisma.XOR<Prisma.ProviderHealthCreateWithoutProviderInput, Prisma.ProviderHealthUncheckedCreateWithoutProviderInput>
  connectOrCreate?: Prisma.ProviderHealthCreateOrConnectWithoutProviderInput
  upsert?: Prisma.ProviderHealthUpsertWithoutProviderInput
  disconnect?: Prisma.ProviderHealthWhereInput | boolean
  delete?: Prisma.ProviderHealthWhereInput | boolean
  connect?: Prisma.ProviderHealthWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ProviderHealthUpdateToOneWithWhereWithoutProviderInput, Prisma.ProviderHealthUpdateWithoutProviderInput>, Prisma.ProviderHealthUncheckedUpdateWithoutProviderInput>
}

export type ProviderHealthCreateWithoutProviderInput = {
  consecutiveFailures?: number
  cooldownUntilTime?: bigint | number | null
  lastSuccessTime?: bigint | number | null
  lastFailureTime?: bigint | number | null
  updatedTime: bigint | number
}

export type ProviderHealthUncheckedCreateWithoutProviderInput = {
  consecutiveFailures?: number
  cooldownUntilTime?: bigint | number | null
  lastSuccessTime?: bigint | number | null
  lastFailureTime?: bigint | number | null
  updatedTime: bigint | number
}

export type ProviderHealthCreateOrConnectWithoutProviderInput = {
  where: Prisma.ProviderHealthWhereUniqueInput
  create: Prisma.XOR<Prisma.ProviderHealthCreateWithoutProviderInput, Prisma.ProviderHealthUncheckedCreateWithoutProviderInput>
}

export type ProviderHealthUpsertWithoutProviderInput = {
  update: Prisma.XOR<Prisma.ProviderHealthUpdateWithoutProviderInput, Prisma.ProviderHealthUncheckedUpdateWithoutProviderInput>
  create: Prisma.XOR<Prisma.ProviderHealthCreateWithoutProviderInput, Prisma.ProviderHealthUncheckedCreateWithoutProviderInput>
  where?: Prisma.ProviderHealthWhereInput
}

export type ProviderHealthUpdateToOneWithWhereWithoutProviderInput = {
  where?: Prisma.ProviderHealthWhereInput
  data: Prisma.XOR<Prisma.ProviderHealthUpdateWithoutProviderInput, Prisma.ProviderHealthUncheckedUpdateWithoutProviderInput>
}

export type ProviderHealthUpdateWithoutProviderInput = {
  consecutiveFailures?: Prisma.IntFieldUpdateOperationsInput | number
  cooldownUntilTime?: Prisma.NullableBigIntFieldUpdateOperationsInput | bigint | number | null
  lastSuccessTime?: Prisma.NullableBigIntFieldUpdateOperationsInput | bigint | number | null
  lastFailureTime?: Prisma.NullableBigIntFieldUpdateOperationsInput | bigint | number | null
  updatedTime?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
}

export type ProviderHealthUncheckedUpdateWithoutProviderInput = {
  consecutiveFailures?: Prisma.IntFieldUpdateOperationsInput | number
  cooldownUntilTime?: Prisma.NullableBigIntFieldUpdateOperationsInput | bigint | number | null
  lastSuccessTime?: Prisma.NullableBigIntFieldUpdateOperationsInput | bigint | number | null
  lastFailureTime?: Prisma.NullableBigIntFieldUpdateOperationsInput | bigint | number | null
  updatedTime?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
}



export type ProviderHealthSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  providerId?: boolean
  consecutiveFailures?: boolean
  cooldownUntilTime?: boolean
  lastSuccessTime?: boolean
  lastFailureTime?: boolean
  updatedTime?: boolean
  provider?: boolean | Prisma.ProviderDefaultArgs<ExtArgs>
}, ExtArgs["result"]["providerHealth"]>

export type ProviderHealthSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  providerId?: boolean
  consecutiveFailures?: boolean
  cooldownUntilTime?: boolean
  lastSuccessTime?: boolean
  lastFailureTime?: boolean
  updatedTime?: boolean
  provider?: boolean | Prisma.ProviderDefaultArgs<ExtArgs>
}, ExtArgs["result"]["providerHealth"]>

export type ProviderHealthSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  providerId?: boolean
  consecutiveFailures?: boolean
  cooldownUntilTime?: boolean
  lastSuccessTime?: boolean
  lastFailureTime?: boolean
  updatedTime?: boolean
  provider?: boolean | Prisma.ProviderDefaultArgs<ExtArgs>
}, ExtArgs["result"]["providerHealth"]>

export type ProviderHealthSelectScalar = {
  providerId?: boolean
  consecutiveFailures?: boolean
  cooldownUntilTime?: boolean
  lastSuccessTime?: boolean
  lastFailureTime?: boolean
  updatedTime?: boolean
}

export type ProviderHealthOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"providerId" | "consecutiveFailures" | "cooldownUntilTime" | "lastSuccessTime" | "lastFailureTime" | "updatedTime", ExtArgs["result"]["providerHealth"]>
export type ProviderHealthInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  provider?: boolean | Prisma.ProviderDefaultArgs<ExtArgs>
}
export type ProviderHealthIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  provider?: boolean | Prisma.ProviderDefaultArgs<ExtArgs>
}
export type ProviderHealthIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  provider?: boolean | Prisma.ProviderDefaultArgs<ExtArgs>
}

export type $ProviderHealthPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ProviderHealth"
  objects: {
    provider: Prisma.$ProviderPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    providerId: string
    consecutiveFailures: number
    cooldownUntilTime: bigint | null
    lastSuccessTime: bigint | null
    lastFailureTime: bigint | null
    updatedTime: bigint
  }, ExtArgs["result"]["providerHealth"]>
  composites: {}
}

export type ProviderHealthGetPayload<S extends boolean | null | undefined | ProviderHealthDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ProviderHealthPayload, S>

export type ProviderHealthCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ProviderHealthFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ProviderHealthCountAggregateInputType | true
  }

export interface ProviderHealthDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ProviderHealth'], meta: { name: 'ProviderHealth' } }
  /**
   * Find zero or one ProviderHealth that matches the filter.
   * @param {ProviderHealthFindUniqueArgs} args - Arguments to find a ProviderHealth
   * @example
   * // Get one ProviderHealth
   * const providerHealth = await prisma.providerHealth.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ProviderHealthFindUniqueArgs>(args: Prisma.SelectSubset<T, ProviderHealthFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ProviderHealthClient<runtime.Types.Result.GetResult<Prisma.$ProviderHealthPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ProviderHealth that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ProviderHealthFindUniqueOrThrowArgs} args - Arguments to find a ProviderHealth
   * @example
   * // Get one ProviderHealth
   * const providerHealth = await prisma.providerHealth.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ProviderHealthFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ProviderHealthFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ProviderHealthClient<runtime.Types.Result.GetResult<Prisma.$ProviderHealthPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ProviderHealth that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProviderHealthFindFirstArgs} args - Arguments to find a ProviderHealth
   * @example
   * // Get one ProviderHealth
   * const providerHealth = await prisma.providerHealth.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ProviderHealthFindFirstArgs>(args?: Prisma.SelectSubset<T, ProviderHealthFindFirstArgs<ExtArgs>>): Prisma.Prisma__ProviderHealthClient<runtime.Types.Result.GetResult<Prisma.$ProviderHealthPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ProviderHealth that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProviderHealthFindFirstOrThrowArgs} args - Arguments to find a ProviderHealth
   * @example
   * // Get one ProviderHealth
   * const providerHealth = await prisma.providerHealth.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ProviderHealthFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ProviderHealthFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ProviderHealthClient<runtime.Types.Result.GetResult<Prisma.$ProviderHealthPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ProviderHealths that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProviderHealthFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ProviderHealths
   * const providerHealths = await prisma.providerHealth.findMany()
   * 
   * // Get first 10 ProviderHealths
   * const providerHealths = await prisma.providerHealth.findMany({ take: 10 })
   * 
   * // Only select the `providerId`
   * const providerHealthWithProviderIdOnly = await prisma.providerHealth.findMany({ select: { providerId: true } })
   * 
   */
  findMany<T extends ProviderHealthFindManyArgs>(args?: Prisma.SelectSubset<T, ProviderHealthFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProviderHealthPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ProviderHealth.
   * @param {ProviderHealthCreateArgs} args - Arguments to create a ProviderHealth.
   * @example
   * // Create one ProviderHealth
   * const ProviderHealth = await prisma.providerHealth.create({
   *   data: {
   *     // ... data to create a ProviderHealth
   *   }
   * })
   * 
   */
  create<T extends ProviderHealthCreateArgs>(args: Prisma.SelectSubset<T, ProviderHealthCreateArgs<ExtArgs>>): Prisma.Prisma__ProviderHealthClient<runtime.Types.Result.GetResult<Prisma.$ProviderHealthPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ProviderHealths.
   * @param {ProviderHealthCreateManyArgs} args - Arguments to create many ProviderHealths.
   * @example
   * // Create many ProviderHealths
   * const providerHealth = await prisma.providerHealth.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ProviderHealthCreateManyArgs>(args?: Prisma.SelectSubset<T, ProviderHealthCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ProviderHealths and returns the data saved in the database.
   * @param {ProviderHealthCreateManyAndReturnArgs} args - Arguments to create many ProviderHealths.
   * @example
   * // Create many ProviderHealths
   * const providerHealth = await prisma.providerHealth.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ProviderHealths and only return the `providerId`
   * const providerHealthWithProviderIdOnly = await prisma.providerHealth.createManyAndReturn({
   *   select: { providerId: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ProviderHealthCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ProviderHealthCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProviderHealthPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ProviderHealth.
   * @param {ProviderHealthDeleteArgs} args - Arguments to delete one ProviderHealth.
   * @example
   * // Delete one ProviderHealth
   * const ProviderHealth = await prisma.providerHealth.delete({
   *   where: {
   *     // ... filter to delete one ProviderHealth
   *   }
   * })
   * 
   */
  delete<T extends ProviderHealthDeleteArgs>(args: Prisma.SelectSubset<T, ProviderHealthDeleteArgs<ExtArgs>>): Prisma.Prisma__ProviderHealthClient<runtime.Types.Result.GetResult<Prisma.$ProviderHealthPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ProviderHealth.
   * @param {ProviderHealthUpdateArgs} args - Arguments to update one ProviderHealth.
   * @example
   * // Update one ProviderHealth
   * const providerHealth = await prisma.providerHealth.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ProviderHealthUpdateArgs>(args: Prisma.SelectSubset<T, ProviderHealthUpdateArgs<ExtArgs>>): Prisma.Prisma__ProviderHealthClient<runtime.Types.Result.GetResult<Prisma.$ProviderHealthPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ProviderHealths.
   * @param {ProviderHealthDeleteManyArgs} args - Arguments to filter ProviderHealths to delete.
   * @example
   * // Delete a few ProviderHealths
   * const { count } = await prisma.providerHealth.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ProviderHealthDeleteManyArgs>(args?: Prisma.SelectSubset<T, ProviderHealthDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ProviderHealths.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProviderHealthUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ProviderHealths
   * const providerHealth = await prisma.providerHealth.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ProviderHealthUpdateManyArgs>(args: Prisma.SelectSubset<T, ProviderHealthUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ProviderHealths and returns the data updated in the database.
   * @param {ProviderHealthUpdateManyAndReturnArgs} args - Arguments to update many ProviderHealths.
   * @example
   * // Update many ProviderHealths
   * const providerHealth = await prisma.providerHealth.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ProviderHealths and only return the `providerId`
   * const providerHealthWithProviderIdOnly = await prisma.providerHealth.updateManyAndReturn({
   *   select: { providerId: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ProviderHealthUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ProviderHealthUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProviderHealthPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ProviderHealth.
   * @param {ProviderHealthUpsertArgs} args - Arguments to update or create a ProviderHealth.
   * @example
   * // Update or create a ProviderHealth
   * const providerHealth = await prisma.providerHealth.upsert({
   *   create: {
   *     // ... data to create a ProviderHealth
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ProviderHealth we want to update
   *   }
   * })
   */
  upsert<T extends ProviderHealthUpsertArgs>(args: Prisma.SelectSubset<T, ProviderHealthUpsertArgs<ExtArgs>>): Prisma.Prisma__ProviderHealthClient<runtime.Types.Result.GetResult<Prisma.$ProviderHealthPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ProviderHealths.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProviderHealthCountArgs} args - Arguments to filter ProviderHealths to count.
   * @example
   * // Count the number of ProviderHealths
   * const count = await prisma.providerHealth.count({
   *   where: {
   *     // ... the filter for the ProviderHealths we want to count
   *   }
   * })
  **/
  count<T extends ProviderHealthCountArgs>(
    args?: Prisma.Subset<T, ProviderHealthCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ProviderHealthCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ProviderHealth.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProviderHealthAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ProviderHealthAggregateArgs>(args: Prisma.Subset<T, ProviderHealthAggregateArgs>): Prisma.PrismaPromise<GetProviderHealthAggregateType<T>>

  /**
   * Group by ProviderHealth.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProviderHealthGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ProviderHealthGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ProviderHealthGroupByArgs['orderBy'] }
      : { orderBy?: ProviderHealthGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ProviderHealthGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetProviderHealthGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ProviderHealth model
 */
readonly fields: ProviderHealthFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ProviderHealth.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ProviderHealthClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  provider<T extends Prisma.ProviderDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ProviderDefaultArgs<ExtArgs>>): Prisma.Prisma__ProviderClient<runtime.Types.Result.GetResult<Prisma.$ProviderPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ProviderHealth model
 */
export interface ProviderHealthFieldRefs {
  readonly providerId: Prisma.FieldRef<"ProviderHealth", 'String'>
  readonly consecutiveFailures: Prisma.FieldRef<"ProviderHealth", 'Int'>
  readonly cooldownUntilTime: Prisma.FieldRef<"ProviderHealth", 'BigInt'>
  readonly lastSuccessTime: Prisma.FieldRef<"ProviderHealth", 'BigInt'>
  readonly lastFailureTime: Prisma.FieldRef<"ProviderHealth", 'BigInt'>
  readonly updatedTime: Prisma.FieldRef<"ProviderHealth", 'BigInt'>
}
    

// Custom InputTypes
/**
 * ProviderHealth findUnique
 */
export type ProviderHealthFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProviderHealth
   */
  select?: Prisma.ProviderHealthSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProviderHealth
   */
  omit?: Prisma.ProviderHealthOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProviderHealthInclude<ExtArgs> | null
  /**
   * Filter, which ProviderHealth to fetch.
   */
  where: Prisma.ProviderHealthWhereUniqueInput
}

/**
 * ProviderHealth findUniqueOrThrow
 */
export type ProviderHealthFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProviderHealth
   */
  select?: Prisma.ProviderHealthSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProviderHealth
   */
  omit?: Prisma.ProviderHealthOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProviderHealthInclude<ExtArgs> | null
  /**
   * Filter, which ProviderHealth to fetch.
   */
  where: Prisma.ProviderHealthWhereUniqueInput
}

/**
 * ProviderHealth findFirst
 */
export type ProviderHealthFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProviderHealth
   */
  select?: Prisma.ProviderHealthSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProviderHealth
   */
  omit?: Prisma.ProviderHealthOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProviderHealthInclude<ExtArgs> | null
  /**
   * Filter, which ProviderHealth to fetch.
   */
  where?: Prisma.ProviderHealthWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ProviderHealths to fetch.
   */
  orderBy?: Prisma.ProviderHealthOrderByWithRelationInput | Prisma.ProviderHealthOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ProviderHealths.
   */
  cursor?: Prisma.ProviderHealthWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ProviderHealths from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ProviderHealths.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ProviderHealths.
   */
  distinct?: Prisma.ProviderHealthScalarFieldEnum | Prisma.ProviderHealthScalarFieldEnum[]
}

/**
 * ProviderHealth findFirstOrThrow
 */
export type ProviderHealthFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProviderHealth
   */
  select?: Prisma.ProviderHealthSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProviderHealth
   */
  omit?: Prisma.ProviderHealthOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProviderHealthInclude<ExtArgs> | null
  /**
   * Filter, which ProviderHealth to fetch.
   */
  where?: Prisma.ProviderHealthWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ProviderHealths to fetch.
   */
  orderBy?: Prisma.ProviderHealthOrderByWithRelationInput | Prisma.ProviderHealthOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ProviderHealths.
   */
  cursor?: Prisma.ProviderHealthWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ProviderHealths from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ProviderHealths.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ProviderHealths.
   */
  distinct?: Prisma.ProviderHealthScalarFieldEnum | Prisma.ProviderHealthScalarFieldEnum[]
}

/**
 * ProviderHealth findMany
 */
export type ProviderHealthFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProviderHealth
   */
  select?: Prisma.ProviderHealthSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProviderHealth
   */
  omit?: Prisma.ProviderHealthOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProviderHealthInclude<ExtArgs> | null
  /**
   * Filter, which ProviderHealths to fetch.
   */
  where?: Prisma.ProviderHealthWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ProviderHealths to fetch.
   */
  orderBy?: Prisma.ProviderHealthOrderByWithRelationInput | Prisma.ProviderHealthOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ProviderHealths.
   */
  cursor?: Prisma.ProviderHealthWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ProviderHealths from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ProviderHealths.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ProviderHealths.
   */
  distinct?: Prisma.ProviderHealthScalarFieldEnum | Prisma.ProviderHealthScalarFieldEnum[]
}

/**
 * ProviderHealth create
 */
export type ProviderHealthCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProviderHealth
   */
  select?: Prisma.ProviderHealthSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProviderHealth
   */
  omit?: Prisma.ProviderHealthOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProviderHealthInclude<ExtArgs> | null
  /**
   * The data needed to create a ProviderHealth.
   */
  data: Prisma.XOR<Prisma.ProviderHealthCreateInput, Prisma.ProviderHealthUncheckedCreateInput>
}

/**
 * ProviderHealth createMany
 */
export type ProviderHealthCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ProviderHealths.
   */
  data: Prisma.ProviderHealthCreateManyInput | Prisma.ProviderHealthCreateManyInput[]
}

/**
 * ProviderHealth createManyAndReturn
 */
export type ProviderHealthCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProviderHealth
   */
  select?: Prisma.ProviderHealthSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ProviderHealth
   */
  omit?: Prisma.ProviderHealthOmit<ExtArgs> | null
  /**
   * The data used to create many ProviderHealths.
   */
  data: Prisma.ProviderHealthCreateManyInput | Prisma.ProviderHealthCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProviderHealthIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * ProviderHealth update
 */
export type ProviderHealthUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProviderHealth
   */
  select?: Prisma.ProviderHealthSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProviderHealth
   */
  omit?: Prisma.ProviderHealthOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProviderHealthInclude<ExtArgs> | null
  /**
   * The data needed to update a ProviderHealth.
   */
  data: Prisma.XOR<Prisma.ProviderHealthUpdateInput, Prisma.ProviderHealthUncheckedUpdateInput>
  /**
   * Choose, which ProviderHealth to update.
   */
  where: Prisma.ProviderHealthWhereUniqueInput
}

/**
 * ProviderHealth updateMany
 */
export type ProviderHealthUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ProviderHealths.
   */
  data: Prisma.XOR<Prisma.ProviderHealthUpdateManyMutationInput, Prisma.ProviderHealthUncheckedUpdateManyInput>
  /**
   * Filter which ProviderHealths to update
   */
  where?: Prisma.ProviderHealthWhereInput
  /**
   * Limit how many ProviderHealths to update.
   */
  limit?: number
}

/**
 * ProviderHealth updateManyAndReturn
 */
export type ProviderHealthUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProviderHealth
   */
  select?: Prisma.ProviderHealthSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ProviderHealth
   */
  omit?: Prisma.ProviderHealthOmit<ExtArgs> | null
  /**
   * The data used to update ProviderHealths.
   */
  data: Prisma.XOR<Prisma.ProviderHealthUpdateManyMutationInput, Prisma.ProviderHealthUncheckedUpdateManyInput>
  /**
   * Filter which ProviderHealths to update
   */
  where?: Prisma.ProviderHealthWhereInput
  /**
   * Limit how many ProviderHealths to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProviderHealthIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * ProviderHealth upsert
 */
export type ProviderHealthUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProviderHealth
   */
  select?: Prisma.ProviderHealthSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProviderHealth
   */
  omit?: Prisma.ProviderHealthOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProviderHealthInclude<ExtArgs> | null
  /**
   * The filter to search for the ProviderHealth to update in case it exists.
   */
  where: Prisma.ProviderHealthWhereUniqueInput
  /**
   * In case the ProviderHealth found by the `where` argument doesn't exist, create a new ProviderHealth with this data.
   */
  create: Prisma.XOR<Prisma.ProviderHealthCreateInput, Prisma.ProviderHealthUncheckedCreateInput>
  /**
   * In case the ProviderHealth was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ProviderHealthUpdateInput, Prisma.ProviderHealthUncheckedUpdateInput>
}

/**
 * ProviderHealth delete
 */
export type ProviderHealthDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProviderHealth
   */
  select?: Prisma.ProviderHealthSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProviderHealth
   */
  omit?: Prisma.ProviderHealthOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProviderHealthInclude<ExtArgs> | null
  /**
   * Filter which ProviderHealth to delete.
   */
  where: Prisma.ProviderHealthWhereUniqueInput
}

/**
 * ProviderHealth deleteMany
 */
export type ProviderHealthDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ProviderHealths to delete
   */
  where?: Prisma.ProviderHealthWhereInput
  /**
   * Limit how many ProviderHealths to delete.
   */
  limit?: number
}

/**
 * ProviderHealth without action
 */
export type ProviderHealthDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProviderHealth
   */
  select?: Prisma.ProviderHealthSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProviderHealth
   */
  omit?: Prisma.ProviderHealthOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProviderHealthInclude<ExtArgs> | null
}
