
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `RequestAttempt` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model RequestAttempt
 * 
 */
export type RequestAttemptModel = runtime.Types.Result.DefaultSelection<Prisma.$RequestAttemptPayload>

export type AggregateRequestAttempt = {
  _count: RequestAttemptCountAggregateOutputType | null
  _avg: RequestAttemptAvgAggregateOutputType | null
  _sum: RequestAttemptSumAggregateOutputType | null
  _min: RequestAttemptMinAggregateOutputType | null
  _max: RequestAttemptMaxAggregateOutputType | null
}

export type RequestAttemptAvgAggregateOutputType = {
  attemptIndex: number | null
  durationMilliseconds: number | null
  createdTime: number | null
}

export type RequestAttemptSumAggregateOutputType = {
  attemptIndex: number | null
  durationMilliseconds: number | null
  createdTime: bigint | null
}

export type RequestAttemptMinAggregateOutputType = {
  id: string | null
  requestId: string | null
  providerId: string | null
  bindingId: string | null
  upstreamModelId: string | null
  attemptIndex: number | null
  status: string | null
  errorCode: string | null
  errorMessage: string | null
  durationMilliseconds: number | null
  createdTime: bigint | null
}

export type RequestAttemptMaxAggregateOutputType = {
  id: string | null
  requestId: string | null
  providerId: string | null
  bindingId: string | null
  upstreamModelId: string | null
  attemptIndex: number | null
  status: string | null
  errorCode: string | null
  errorMessage: string | null
  durationMilliseconds: number | null
  createdTime: bigint | null
}

export type RequestAttemptCountAggregateOutputType = {
  id: number
  requestId: number
  providerId: number
  bindingId: number
  upstreamModelId: number
  attemptIndex: number
  status: number
  errorCode: number
  errorMessage: number
  durationMilliseconds: number
  createdTime: number
  _all: number
}


export type RequestAttemptAvgAggregateInputType = {
  attemptIndex?: true
  durationMilliseconds?: true
  createdTime?: true
}

export type RequestAttemptSumAggregateInputType = {
  attemptIndex?: true
  durationMilliseconds?: true
  createdTime?: true
}

export type RequestAttemptMinAggregateInputType = {
  id?: true
  requestId?: true
  providerId?: true
  bindingId?: true
  upstreamModelId?: true
  attemptIndex?: true
  status?: true
  errorCode?: true
  errorMessage?: true
  durationMilliseconds?: true
  createdTime?: true
}

export type RequestAttemptMaxAggregateInputType = {
  id?: true
  requestId?: true
  providerId?: true
  bindingId?: true
  upstreamModelId?: true
  attemptIndex?: true
  status?: true
  errorCode?: true
  errorMessage?: true
  durationMilliseconds?: true
  createdTime?: true
}

export type RequestAttemptCountAggregateInputType = {
  id?: true
  requestId?: true
  providerId?: true
  bindingId?: true
  upstreamModelId?: true
  attemptIndex?: true
  status?: true
  errorCode?: true
  errorMessage?: true
  durationMilliseconds?: true
  createdTime?: true
  _all?: true
}

export type RequestAttemptAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which RequestAttempt to aggregate.
   */
  where?: Prisma.RequestAttemptWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RequestAttempts to fetch.
   */
  orderBy?: Prisma.RequestAttemptOrderByWithRelationInput | Prisma.RequestAttemptOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.RequestAttemptWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RequestAttempts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RequestAttempts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned RequestAttempts
  **/
  _count?: true | RequestAttemptCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: RequestAttemptAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: RequestAttemptSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: RequestAttemptMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: RequestAttemptMaxAggregateInputType
}

export type GetRequestAttemptAggregateType<T extends RequestAttemptAggregateArgs> = {
      [P in keyof T & keyof AggregateRequestAttempt]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateRequestAttempt[P]>
    : Prisma.GetScalarType<T[P], AggregateRequestAttempt[P]>
}




export type RequestAttemptGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.RequestAttemptWhereInput
  orderBy?: Prisma.RequestAttemptOrderByWithAggregationInput | Prisma.RequestAttemptOrderByWithAggregationInput[]
  by: Prisma.RequestAttemptScalarFieldEnum[] | Prisma.RequestAttemptScalarFieldEnum
  having?: Prisma.RequestAttemptScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: RequestAttemptCountAggregateInputType | true
  _avg?: RequestAttemptAvgAggregateInputType
  _sum?: RequestAttemptSumAggregateInputType
  _min?: RequestAttemptMinAggregateInputType
  _max?: RequestAttemptMaxAggregateInputType
}

export type RequestAttemptGroupByOutputType = {
  id: string
  requestId: string
  providerId: string
  bindingId: string
  upstreamModelId: string
  attemptIndex: number
  status: string
  errorCode: string | null
  errorMessage: string | null
  durationMilliseconds: number
  createdTime: bigint
  _count: RequestAttemptCountAggregateOutputType | null
  _avg: RequestAttemptAvgAggregateOutputType | null
  _sum: RequestAttemptSumAggregateOutputType | null
  _min: RequestAttemptMinAggregateOutputType | null
  _max: RequestAttemptMaxAggregateOutputType | null
}

export type GetRequestAttemptGroupByPayload<T extends RequestAttemptGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<RequestAttemptGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof RequestAttemptGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], RequestAttemptGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], RequestAttemptGroupByOutputType[P]>
      }
    >
  >



export type RequestAttemptWhereInput = {
  AND?: Prisma.RequestAttemptWhereInput | Prisma.RequestAttemptWhereInput[]
  OR?: Prisma.RequestAttemptWhereInput[]
  NOT?: Prisma.RequestAttemptWhereInput | Prisma.RequestAttemptWhereInput[]
  id?: Prisma.StringFilter<"RequestAttempt"> | string
  requestId?: Prisma.StringFilter<"RequestAttempt"> | string
  providerId?: Prisma.StringFilter<"RequestAttempt"> | string
  bindingId?: Prisma.StringFilter<"RequestAttempt"> | string
  upstreamModelId?: Prisma.StringFilter<"RequestAttempt"> | string
  attemptIndex?: Prisma.IntFilter<"RequestAttempt"> | number
  status?: Prisma.StringFilter<"RequestAttempt"> | string
  errorCode?: Prisma.StringNullableFilter<"RequestAttempt"> | string | null
  errorMessage?: Prisma.StringNullableFilter<"RequestAttempt"> | string | null
  durationMilliseconds?: Prisma.IntFilter<"RequestAttempt"> | number
  createdTime?: Prisma.BigIntFilter<"RequestAttempt"> | bigint | number
  request?: Prisma.XOR<Prisma.RequestLogScalarRelationFilter, Prisma.RequestLogWhereInput>
  provider?: Prisma.XOR<Prisma.ProviderScalarRelationFilter, Prisma.ProviderWhereInput>
  binding?: Prisma.XOR<Prisma.ModelBindingScalarRelationFilter, Prisma.ModelBindingWhereInput>
}

export type RequestAttemptOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  requestId?: Prisma.SortOrder
  providerId?: Prisma.SortOrder
  bindingId?: Prisma.SortOrder
  upstreamModelId?: Prisma.SortOrder
  attemptIndex?: Prisma.SortOrder
  status?: Prisma.SortOrder
  errorCode?: Prisma.SortOrderInput | Prisma.SortOrder
  errorMessage?: Prisma.SortOrderInput | Prisma.SortOrder
  durationMilliseconds?: Prisma.SortOrder
  createdTime?: Prisma.SortOrder
  request?: Prisma.RequestLogOrderByWithRelationInput
  provider?: Prisma.ProviderOrderByWithRelationInput
  binding?: Prisma.ModelBindingOrderByWithRelationInput
}

export type RequestAttemptWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.RequestAttemptWhereInput | Prisma.RequestAttemptWhereInput[]
  OR?: Prisma.RequestAttemptWhereInput[]
  NOT?: Prisma.RequestAttemptWhereInput | Prisma.RequestAttemptWhereInput[]
  requestId?: Prisma.StringFilter<"RequestAttempt"> | string
  providerId?: Prisma.StringFilter<"RequestAttempt"> | string
  bindingId?: Prisma.StringFilter<"RequestAttempt"> | string
  upstreamModelId?: Prisma.StringFilter<"RequestAttempt"> | string
  attemptIndex?: Prisma.IntFilter<"RequestAttempt"> | number
  status?: Prisma.StringFilter<"RequestAttempt"> | string
  errorCode?: Prisma.StringNullableFilter<"RequestAttempt"> | string | null
  errorMessage?: Prisma.StringNullableFilter<"RequestAttempt"> | string | null
  durationMilliseconds?: Prisma.IntFilter<"RequestAttempt"> | number
  createdTime?: Prisma.BigIntFilter<"RequestAttempt"> | bigint | number
  request?: Prisma.XOR<Prisma.RequestLogScalarRelationFilter, Prisma.RequestLogWhereInput>
  provider?: Prisma.XOR<Prisma.ProviderScalarRelationFilter, Prisma.ProviderWhereInput>
  binding?: Prisma.XOR<Prisma.ModelBindingScalarRelationFilter, Prisma.ModelBindingWhereInput>
}, "id">

export type RequestAttemptOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  requestId?: Prisma.SortOrder
  providerId?: Prisma.SortOrder
  bindingId?: Prisma.SortOrder
  upstreamModelId?: Prisma.SortOrder
  attemptIndex?: Prisma.SortOrder
  status?: Prisma.SortOrder
  errorCode?: Prisma.SortOrderInput | Prisma.SortOrder
  errorMessage?: Prisma.SortOrderInput | Prisma.SortOrder
  durationMilliseconds?: Prisma.SortOrder
  createdTime?: Prisma.SortOrder
  _count?: Prisma.RequestAttemptCountOrderByAggregateInput
  _avg?: Prisma.RequestAttemptAvgOrderByAggregateInput
  _max?: Prisma.RequestAttemptMaxOrderByAggregateInput
  _min?: Prisma.RequestAttemptMinOrderByAggregateInput
  _sum?: Prisma.RequestAttemptSumOrderByAggregateInput
}

export type RequestAttemptScalarWhereWithAggregatesInput = {
  AND?: Prisma.RequestAttemptScalarWhereWithAggregatesInput | Prisma.RequestAttemptScalarWhereWithAggregatesInput[]
  OR?: Prisma.RequestAttemptScalarWhereWithAggregatesInput[]
  NOT?: Prisma.RequestAttemptScalarWhereWithAggregatesInput | Prisma.RequestAttemptScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"RequestAttempt"> | string
  requestId?: Prisma.StringWithAggregatesFilter<"RequestAttempt"> | string
  providerId?: Prisma.StringWithAggregatesFilter<"RequestAttempt"> | string
  bindingId?: Prisma.StringWithAggregatesFilter<"RequestAttempt"> | string
  upstreamModelId?: Prisma.StringWithAggregatesFilter<"RequestAttempt"> | string
  attemptIndex?: Prisma.IntWithAggregatesFilter<"RequestAttempt"> | number
  status?: Prisma.StringWithAggregatesFilter<"RequestAttempt"> | string
  errorCode?: Prisma.StringNullableWithAggregatesFilter<"RequestAttempt"> | string | null
  errorMessage?: Prisma.StringNullableWithAggregatesFilter<"RequestAttempt"> | string | null
  durationMilliseconds?: Prisma.IntWithAggregatesFilter<"RequestAttempt"> | number
  createdTime?: Prisma.BigIntWithAggregatesFilter<"RequestAttempt"> | bigint | number
}

export type RequestAttemptCreateInput = {
  id: string
  upstreamModelId: string
  attemptIndex: number
  status: string
  errorCode?: string | null
  errorMessage?: string | null
  durationMilliseconds: number
  createdTime: bigint | number
  request: Prisma.RequestLogCreateNestedOneWithoutAttemptsInput
  provider: Prisma.ProviderCreateNestedOneWithoutAttemptsInput
  binding: Prisma.ModelBindingCreateNestedOneWithoutAttemptsInput
}

export type RequestAttemptUncheckedCreateInput = {
  id: string
  requestId: string
  providerId: string
  bindingId: string
  upstreamModelId: string
  attemptIndex: number
  status: string
  errorCode?: string | null
  errorMessage?: string | null
  durationMilliseconds: number
  createdTime: bigint | number
}

export type RequestAttemptUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  upstreamModelId?: Prisma.StringFieldUpdateOperationsInput | string
  attemptIndex?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.StringFieldUpdateOperationsInput | string
  errorCode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  errorMessage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  durationMilliseconds?: Prisma.IntFieldUpdateOperationsInput | number
  createdTime?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  request?: Prisma.RequestLogUpdateOneRequiredWithoutAttemptsNestedInput
  provider?: Prisma.ProviderUpdateOneRequiredWithoutAttemptsNestedInput
  binding?: Prisma.ModelBindingUpdateOneRequiredWithoutAttemptsNestedInput
}

export type RequestAttemptUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  requestId?: Prisma.StringFieldUpdateOperationsInput | string
  providerId?: Prisma.StringFieldUpdateOperationsInput | string
  bindingId?: Prisma.StringFieldUpdateOperationsInput | string
  upstreamModelId?: Prisma.StringFieldUpdateOperationsInput | string
  attemptIndex?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.StringFieldUpdateOperationsInput | string
  errorCode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  errorMessage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  durationMilliseconds?: Prisma.IntFieldUpdateOperationsInput | number
  createdTime?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
}

export type RequestAttemptCreateManyInput = {
  id: string
  requestId: string
  providerId: string
  bindingId: string
  upstreamModelId: string
  attemptIndex: number
  status: string
  errorCode?: string | null
  errorMessage?: string | null
  durationMilliseconds: number
  createdTime: bigint | number
}

export type RequestAttemptUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  upstreamModelId?: Prisma.StringFieldUpdateOperationsInput | string
  attemptIndex?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.StringFieldUpdateOperationsInput | string
  errorCode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  errorMessage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  durationMilliseconds?: Prisma.IntFieldUpdateOperationsInput | number
  createdTime?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
}

export type RequestAttemptUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  requestId?: Prisma.StringFieldUpdateOperationsInput | string
  providerId?: Prisma.StringFieldUpdateOperationsInput | string
  bindingId?: Prisma.StringFieldUpdateOperationsInput | string
  upstreamModelId?: Prisma.StringFieldUpdateOperationsInput | string
  attemptIndex?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.StringFieldUpdateOperationsInput | string
  errorCode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  errorMessage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  durationMilliseconds?: Prisma.IntFieldUpdateOperationsInput | number
  createdTime?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
}

export type RequestAttemptListRelationFilter = {
  every?: Prisma.RequestAttemptWhereInput
  some?: Prisma.RequestAttemptWhereInput
  none?: Prisma.RequestAttemptWhereInput
}

export type RequestAttemptOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type RequestAttemptCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  requestId?: Prisma.SortOrder
  providerId?: Prisma.SortOrder
  bindingId?: Prisma.SortOrder
  upstreamModelId?: Prisma.SortOrder
  attemptIndex?: Prisma.SortOrder
  status?: Prisma.SortOrder
  errorCode?: Prisma.SortOrder
  errorMessage?: Prisma.SortOrder
  durationMilliseconds?: Prisma.SortOrder
  createdTime?: Prisma.SortOrder
}

export type RequestAttemptAvgOrderByAggregateInput = {
  attemptIndex?: Prisma.SortOrder
  durationMilliseconds?: Prisma.SortOrder
  createdTime?: Prisma.SortOrder
}

export type RequestAttemptMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  requestId?: Prisma.SortOrder
  providerId?: Prisma.SortOrder
  bindingId?: Prisma.SortOrder
  upstreamModelId?: Prisma.SortOrder
  attemptIndex?: Prisma.SortOrder
  status?: Prisma.SortOrder
  errorCode?: Prisma.SortOrder
  errorMessage?: Prisma.SortOrder
  durationMilliseconds?: Prisma.SortOrder
  createdTime?: Prisma.SortOrder
}

export type RequestAttemptMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  requestId?: Prisma.SortOrder
  providerId?: Prisma.SortOrder
  bindingId?: Prisma.SortOrder
  upstreamModelId?: Prisma.SortOrder
  attemptIndex?: Prisma.SortOrder
  status?: Prisma.SortOrder
  errorCode?: Prisma.SortOrder
  errorMessage?: Prisma.SortOrder
  durationMilliseconds?: Prisma.SortOrder
  createdTime?: Prisma.SortOrder
}

export type RequestAttemptSumOrderByAggregateInput = {
  attemptIndex?: Prisma.SortOrder
  durationMilliseconds?: Prisma.SortOrder
  createdTime?: Prisma.SortOrder
}

export type RequestAttemptCreateNestedManyWithoutProviderInput = {
  create?: Prisma.XOR<Prisma.RequestAttemptCreateWithoutProviderInput, Prisma.RequestAttemptUncheckedCreateWithoutProviderInput> | Prisma.RequestAttemptCreateWithoutProviderInput[] | Prisma.RequestAttemptUncheckedCreateWithoutProviderInput[]
  connectOrCreate?: Prisma.RequestAttemptCreateOrConnectWithoutProviderInput | Prisma.RequestAttemptCreateOrConnectWithoutProviderInput[]
  createMany?: Prisma.RequestAttemptCreateManyProviderInputEnvelope
  connect?: Prisma.RequestAttemptWhereUniqueInput | Prisma.RequestAttemptWhereUniqueInput[]
}

export type RequestAttemptUncheckedCreateNestedManyWithoutProviderInput = {
  create?: Prisma.XOR<Prisma.RequestAttemptCreateWithoutProviderInput, Prisma.RequestAttemptUncheckedCreateWithoutProviderInput> | Prisma.RequestAttemptCreateWithoutProviderInput[] | Prisma.RequestAttemptUncheckedCreateWithoutProviderInput[]
  connectOrCreate?: Prisma.RequestAttemptCreateOrConnectWithoutProviderInput | Prisma.RequestAttemptCreateOrConnectWithoutProviderInput[]
  createMany?: Prisma.RequestAttemptCreateManyProviderInputEnvelope
  connect?: Prisma.RequestAttemptWhereUniqueInput | Prisma.RequestAttemptWhereUniqueInput[]
}

export type RequestAttemptUpdateManyWithoutProviderNestedInput = {
  create?: Prisma.XOR<Prisma.RequestAttemptCreateWithoutProviderInput, Prisma.RequestAttemptUncheckedCreateWithoutProviderInput> | Prisma.RequestAttemptCreateWithoutProviderInput[] | Prisma.RequestAttemptUncheckedCreateWithoutProviderInput[]
  connectOrCreate?: Prisma.RequestAttemptCreateOrConnectWithoutProviderInput | Prisma.RequestAttemptCreateOrConnectWithoutProviderInput[]
  upsert?: Prisma.RequestAttemptUpsertWithWhereUniqueWithoutProviderInput | Prisma.RequestAttemptUpsertWithWhereUniqueWithoutProviderInput[]
  createMany?: Prisma.RequestAttemptCreateManyProviderInputEnvelope
  set?: Prisma.RequestAttemptWhereUniqueInput | Prisma.RequestAttemptWhereUniqueInput[]
  disconnect?: Prisma.RequestAttemptWhereUniqueInput | Prisma.RequestAttemptWhereUniqueInput[]
  delete?: Prisma.RequestAttemptWhereUniqueInput | Prisma.RequestAttemptWhereUniqueInput[]
  connect?: Prisma.RequestAttemptWhereUniqueInput | Prisma.RequestAttemptWhereUniqueInput[]
  update?: Prisma.RequestAttemptUpdateWithWhereUniqueWithoutProviderInput | Prisma.RequestAttemptUpdateWithWhereUniqueWithoutProviderInput[]
  updateMany?: Prisma.RequestAttemptUpdateManyWithWhereWithoutProviderInput | Prisma.RequestAttemptUpdateManyWithWhereWithoutProviderInput[]
  deleteMany?: Prisma.RequestAttemptScalarWhereInput | Prisma.RequestAttemptScalarWhereInput[]
}

export type RequestAttemptUncheckedUpdateManyWithoutProviderNestedInput = {
  create?: Prisma.XOR<Prisma.RequestAttemptCreateWithoutProviderInput, Prisma.RequestAttemptUncheckedCreateWithoutProviderInput> | Prisma.RequestAttemptCreateWithoutProviderInput[] | Prisma.RequestAttemptUncheckedCreateWithoutProviderInput[]
  connectOrCreate?: Prisma.RequestAttemptCreateOrConnectWithoutProviderInput | Prisma.RequestAttemptCreateOrConnectWithoutProviderInput[]
  upsert?: Prisma.RequestAttemptUpsertWithWhereUniqueWithoutProviderInput | Prisma.RequestAttemptUpsertWithWhereUniqueWithoutProviderInput[]
  createMany?: Prisma.RequestAttemptCreateManyProviderInputEnvelope
  set?: Prisma.RequestAttemptWhereUniqueInput | Prisma.RequestAttemptWhereUniqueInput[]
  disconnect?: Prisma.RequestAttemptWhereUniqueInput | Prisma.RequestAttemptWhereUniqueInput[]
  delete?: Prisma.RequestAttemptWhereUniqueInput | Prisma.RequestAttemptWhereUniqueInput[]
  connect?: Prisma.RequestAttemptWhereUniqueInput | Prisma.RequestAttemptWhereUniqueInput[]
  update?: Prisma.RequestAttemptUpdateWithWhereUniqueWithoutProviderInput | Prisma.RequestAttemptUpdateWithWhereUniqueWithoutProviderInput[]
  updateMany?: Prisma.RequestAttemptUpdateManyWithWhereWithoutProviderInput | Prisma.RequestAttemptUpdateManyWithWhereWithoutProviderInput[]
  deleteMany?: Prisma.RequestAttemptScalarWhereInput | Prisma.RequestAttemptScalarWhereInput[]
}

export type RequestAttemptCreateNestedManyWithoutBindingInput = {
  create?: Prisma.XOR<Prisma.RequestAttemptCreateWithoutBindingInput, Prisma.RequestAttemptUncheckedCreateWithoutBindingInput> | Prisma.RequestAttemptCreateWithoutBindingInput[] | Prisma.RequestAttemptUncheckedCreateWithoutBindingInput[]
  connectOrCreate?: Prisma.RequestAttemptCreateOrConnectWithoutBindingInput | Prisma.RequestAttemptCreateOrConnectWithoutBindingInput[]
  createMany?: Prisma.RequestAttemptCreateManyBindingInputEnvelope
  connect?: Prisma.RequestAttemptWhereUniqueInput | Prisma.RequestAttemptWhereUniqueInput[]
}

export type RequestAttemptUncheckedCreateNestedManyWithoutBindingInput = {
  create?: Prisma.XOR<Prisma.RequestAttemptCreateWithoutBindingInput, Prisma.RequestAttemptUncheckedCreateWithoutBindingInput> | Prisma.RequestAttemptCreateWithoutBindingInput[] | Prisma.RequestAttemptUncheckedCreateWithoutBindingInput[]
  connectOrCreate?: Prisma.RequestAttemptCreateOrConnectWithoutBindingInput | Prisma.RequestAttemptCreateOrConnectWithoutBindingInput[]
  createMany?: Prisma.RequestAttemptCreateManyBindingInputEnvelope
  connect?: Prisma.RequestAttemptWhereUniqueInput | Prisma.RequestAttemptWhereUniqueInput[]
}

export type RequestAttemptUpdateManyWithoutBindingNestedInput = {
  create?: Prisma.XOR<Prisma.RequestAttemptCreateWithoutBindingInput, Prisma.RequestAttemptUncheckedCreateWithoutBindingInput> | Prisma.RequestAttemptCreateWithoutBindingInput[] | Prisma.RequestAttemptUncheckedCreateWithoutBindingInput[]
  connectOrCreate?: Prisma.RequestAttemptCreateOrConnectWithoutBindingInput | Prisma.RequestAttemptCreateOrConnectWithoutBindingInput[]
  upsert?: Prisma.RequestAttemptUpsertWithWhereUniqueWithoutBindingInput | Prisma.RequestAttemptUpsertWithWhereUniqueWithoutBindingInput[]
  createMany?: Prisma.RequestAttemptCreateManyBindingInputEnvelope
  set?: Prisma.RequestAttemptWhereUniqueInput | Prisma.RequestAttemptWhereUniqueInput[]
  disconnect?: Prisma.RequestAttemptWhereUniqueInput | Prisma.RequestAttemptWhereUniqueInput[]
  delete?: Prisma.RequestAttemptWhereUniqueInput | Prisma.RequestAttemptWhereUniqueInput[]
  connect?: Prisma.RequestAttemptWhereUniqueInput | Prisma.RequestAttemptWhereUniqueInput[]
  update?: Prisma.RequestAttemptUpdateWithWhereUniqueWithoutBindingInput | Prisma.RequestAttemptUpdateWithWhereUniqueWithoutBindingInput[]
  updateMany?: Prisma.RequestAttemptUpdateManyWithWhereWithoutBindingInput | Prisma.RequestAttemptUpdateManyWithWhereWithoutBindingInput[]
  deleteMany?: Prisma.RequestAttemptScalarWhereInput | Prisma.RequestAttemptScalarWhereInput[]
}

export type RequestAttemptUncheckedUpdateManyWithoutBindingNestedInput = {
  create?: Prisma.XOR<Prisma.RequestAttemptCreateWithoutBindingInput, Prisma.RequestAttemptUncheckedCreateWithoutBindingInput> | Prisma.RequestAttemptCreateWithoutBindingInput[] | Prisma.RequestAttemptUncheckedCreateWithoutBindingInput[]
  connectOrCreate?: Prisma.RequestAttemptCreateOrConnectWithoutBindingInput | Prisma.RequestAttemptCreateOrConnectWithoutBindingInput[]
  upsert?: Prisma.RequestAttemptUpsertWithWhereUniqueWithoutBindingInput | Prisma.RequestAttemptUpsertWithWhereUniqueWithoutBindingInput[]
  createMany?: Prisma.RequestAttemptCreateManyBindingInputEnvelope
  set?: Prisma.RequestAttemptWhereUniqueInput | Prisma.RequestAttemptWhereUniqueInput[]
  disconnect?: Prisma.RequestAttemptWhereUniqueInput | Prisma.RequestAttemptWhereUniqueInput[]
  delete?: Prisma.RequestAttemptWhereUniqueInput | Prisma.RequestAttemptWhereUniqueInput[]
  connect?: Prisma.RequestAttemptWhereUniqueInput | Prisma.RequestAttemptWhereUniqueInput[]
  update?: Prisma.RequestAttemptUpdateWithWhereUniqueWithoutBindingInput | Prisma.RequestAttemptUpdateWithWhereUniqueWithoutBindingInput[]
  updateMany?: Prisma.RequestAttemptUpdateManyWithWhereWithoutBindingInput | Prisma.RequestAttemptUpdateManyWithWhereWithoutBindingInput[]
  deleteMany?: Prisma.RequestAttemptScalarWhereInput | Prisma.RequestAttemptScalarWhereInput[]
}

export type RequestAttemptCreateNestedManyWithoutRequestInput = {
  create?: Prisma.XOR<Prisma.RequestAttemptCreateWithoutRequestInput, Prisma.RequestAttemptUncheckedCreateWithoutRequestInput> | Prisma.RequestAttemptCreateWithoutRequestInput[] | Prisma.RequestAttemptUncheckedCreateWithoutRequestInput[]
  connectOrCreate?: Prisma.RequestAttemptCreateOrConnectWithoutRequestInput | Prisma.RequestAttemptCreateOrConnectWithoutRequestInput[]
  createMany?: Prisma.RequestAttemptCreateManyRequestInputEnvelope
  connect?: Prisma.RequestAttemptWhereUniqueInput | Prisma.RequestAttemptWhereUniqueInput[]
}

export type RequestAttemptUncheckedCreateNestedManyWithoutRequestInput = {
  create?: Prisma.XOR<Prisma.RequestAttemptCreateWithoutRequestInput, Prisma.RequestAttemptUncheckedCreateWithoutRequestInput> | Prisma.RequestAttemptCreateWithoutRequestInput[] | Prisma.RequestAttemptUncheckedCreateWithoutRequestInput[]
  connectOrCreate?: Prisma.RequestAttemptCreateOrConnectWithoutRequestInput | Prisma.RequestAttemptCreateOrConnectWithoutRequestInput[]
  createMany?: Prisma.RequestAttemptCreateManyRequestInputEnvelope
  connect?: Prisma.RequestAttemptWhereUniqueInput | Prisma.RequestAttemptWhereUniqueInput[]
}

export type RequestAttemptUpdateManyWithoutRequestNestedInput = {
  create?: Prisma.XOR<Prisma.RequestAttemptCreateWithoutRequestInput, Prisma.RequestAttemptUncheckedCreateWithoutRequestInput> | Prisma.RequestAttemptCreateWithoutRequestInput[] | Prisma.RequestAttemptUncheckedCreateWithoutRequestInput[]
  connectOrCreate?: Prisma.RequestAttemptCreateOrConnectWithoutRequestInput | Prisma.RequestAttemptCreateOrConnectWithoutRequestInput[]
  upsert?: Prisma.RequestAttemptUpsertWithWhereUniqueWithoutRequestInput | Prisma.RequestAttemptUpsertWithWhereUniqueWithoutRequestInput[]
  createMany?: Prisma.RequestAttemptCreateManyRequestInputEnvelope
  set?: Prisma.RequestAttemptWhereUniqueInput | Prisma.RequestAttemptWhereUniqueInput[]
  disconnect?: Prisma.RequestAttemptWhereUniqueInput | Prisma.RequestAttemptWhereUniqueInput[]
  delete?: Prisma.RequestAttemptWhereUniqueInput | Prisma.RequestAttemptWhereUniqueInput[]
  connect?: Prisma.RequestAttemptWhereUniqueInput | Prisma.RequestAttemptWhereUniqueInput[]
  update?: Prisma.RequestAttemptUpdateWithWhereUniqueWithoutRequestInput | Prisma.RequestAttemptUpdateWithWhereUniqueWithoutRequestInput[]
  updateMany?: Prisma.RequestAttemptUpdateManyWithWhereWithoutRequestInput | Prisma.RequestAttemptUpdateManyWithWhereWithoutRequestInput[]
  deleteMany?: Prisma.RequestAttemptScalarWhereInput | Prisma.RequestAttemptScalarWhereInput[]
}

export type RequestAttemptUncheckedUpdateManyWithoutRequestNestedInput = {
  create?: Prisma.XOR<Prisma.RequestAttemptCreateWithoutRequestInput, Prisma.RequestAttemptUncheckedCreateWithoutRequestInput> | Prisma.RequestAttemptCreateWithoutRequestInput[] | Prisma.RequestAttemptUncheckedCreateWithoutRequestInput[]
  connectOrCreate?: Prisma.RequestAttemptCreateOrConnectWithoutRequestInput | Prisma.RequestAttemptCreateOrConnectWithoutRequestInput[]
  upsert?: Prisma.RequestAttemptUpsertWithWhereUniqueWithoutRequestInput | Prisma.RequestAttemptUpsertWithWhereUniqueWithoutRequestInput[]
  createMany?: Prisma.RequestAttemptCreateManyRequestInputEnvelope
  set?: Prisma.RequestAttemptWhereUniqueInput | Prisma.RequestAttemptWhereUniqueInput[]
  disconnect?: Prisma.RequestAttemptWhereUniqueInput | Prisma.RequestAttemptWhereUniqueInput[]
  delete?: Prisma.RequestAttemptWhereUniqueInput | Prisma.RequestAttemptWhereUniqueInput[]
  connect?: Prisma.RequestAttemptWhereUniqueInput | Prisma.RequestAttemptWhereUniqueInput[]
  update?: Prisma.RequestAttemptUpdateWithWhereUniqueWithoutRequestInput | Prisma.RequestAttemptUpdateWithWhereUniqueWithoutRequestInput[]
  updateMany?: Prisma.RequestAttemptUpdateManyWithWhereWithoutRequestInput | Prisma.RequestAttemptUpdateManyWithWhereWithoutRequestInput[]
  deleteMany?: Prisma.RequestAttemptScalarWhereInput | Prisma.RequestAttemptScalarWhereInput[]
}

export type RequestAttemptCreateWithoutProviderInput = {
  id: string
  upstreamModelId: string
  attemptIndex: number
  status: string
  errorCode?: string | null
  errorMessage?: string | null
  durationMilliseconds: number
  createdTime: bigint | number
  request: Prisma.RequestLogCreateNestedOneWithoutAttemptsInput
  binding: Prisma.ModelBindingCreateNestedOneWithoutAttemptsInput
}

export type RequestAttemptUncheckedCreateWithoutProviderInput = {
  id: string
  requestId: string
  bindingId: string
  upstreamModelId: string
  attemptIndex: number
  status: string
  errorCode?: string | null
  errorMessage?: string | null
  durationMilliseconds: number
  createdTime: bigint | number
}

export type RequestAttemptCreateOrConnectWithoutProviderInput = {
  where: Prisma.RequestAttemptWhereUniqueInput
  create: Prisma.XOR<Prisma.RequestAttemptCreateWithoutProviderInput, Prisma.RequestAttemptUncheckedCreateWithoutProviderInput>
}

export type RequestAttemptCreateManyProviderInputEnvelope = {
  data: Prisma.RequestAttemptCreateManyProviderInput | Prisma.RequestAttemptCreateManyProviderInput[]
}

export type RequestAttemptUpsertWithWhereUniqueWithoutProviderInput = {
  where: Prisma.RequestAttemptWhereUniqueInput
  update: Prisma.XOR<Prisma.RequestAttemptUpdateWithoutProviderInput, Prisma.RequestAttemptUncheckedUpdateWithoutProviderInput>
  create: Prisma.XOR<Prisma.RequestAttemptCreateWithoutProviderInput, Prisma.RequestAttemptUncheckedCreateWithoutProviderInput>
}

export type RequestAttemptUpdateWithWhereUniqueWithoutProviderInput = {
  where: Prisma.RequestAttemptWhereUniqueInput
  data: Prisma.XOR<Prisma.RequestAttemptUpdateWithoutProviderInput, Prisma.RequestAttemptUncheckedUpdateWithoutProviderInput>
}

export type RequestAttemptUpdateManyWithWhereWithoutProviderInput = {
  where: Prisma.RequestAttemptScalarWhereInput
  data: Prisma.XOR<Prisma.RequestAttemptUpdateManyMutationInput, Prisma.RequestAttemptUncheckedUpdateManyWithoutProviderInput>
}

export type RequestAttemptScalarWhereInput = {
  AND?: Prisma.RequestAttemptScalarWhereInput | Prisma.RequestAttemptScalarWhereInput[]
  OR?: Prisma.RequestAttemptScalarWhereInput[]
  NOT?: Prisma.RequestAttemptScalarWhereInput | Prisma.RequestAttemptScalarWhereInput[]
  id?: Prisma.StringFilter<"RequestAttempt"> | string
  requestId?: Prisma.StringFilter<"RequestAttempt"> | string
  providerId?: Prisma.StringFilter<"RequestAttempt"> | string
  bindingId?: Prisma.StringFilter<"RequestAttempt"> | string
  upstreamModelId?: Prisma.StringFilter<"RequestAttempt"> | string
  attemptIndex?: Prisma.IntFilter<"RequestAttempt"> | number
  status?: Prisma.StringFilter<"RequestAttempt"> | string
  errorCode?: Prisma.StringNullableFilter<"RequestAttempt"> | string | null
  errorMessage?: Prisma.StringNullableFilter<"RequestAttempt"> | string | null
  durationMilliseconds?: Prisma.IntFilter<"RequestAttempt"> | number
  createdTime?: Prisma.BigIntFilter<"RequestAttempt"> | bigint | number
}

export type RequestAttemptCreateWithoutBindingInput = {
  id: string
  upstreamModelId: string
  attemptIndex: number
  status: string
  errorCode?: string | null
  errorMessage?: string | null
  durationMilliseconds: number
  createdTime: bigint | number
  request: Prisma.RequestLogCreateNestedOneWithoutAttemptsInput
  provider: Prisma.ProviderCreateNestedOneWithoutAttemptsInput
}

export type RequestAttemptUncheckedCreateWithoutBindingInput = {
  id: string
  requestId: string
  providerId: string
  upstreamModelId: string
  attemptIndex: number
  status: string
  errorCode?: string | null
  errorMessage?: string | null
  durationMilliseconds: number
  createdTime: bigint | number
}

export type RequestAttemptCreateOrConnectWithoutBindingInput = {
  where: Prisma.RequestAttemptWhereUniqueInput
  create: Prisma.XOR<Prisma.RequestAttemptCreateWithoutBindingInput, Prisma.RequestAttemptUncheckedCreateWithoutBindingInput>
}

export type RequestAttemptCreateManyBindingInputEnvelope = {
  data: Prisma.RequestAttemptCreateManyBindingInput | Prisma.RequestAttemptCreateManyBindingInput[]
}

export type RequestAttemptUpsertWithWhereUniqueWithoutBindingInput = {
  where: Prisma.RequestAttemptWhereUniqueInput
  update: Prisma.XOR<Prisma.RequestAttemptUpdateWithoutBindingInput, Prisma.RequestAttemptUncheckedUpdateWithoutBindingInput>
  create: Prisma.XOR<Prisma.RequestAttemptCreateWithoutBindingInput, Prisma.RequestAttemptUncheckedCreateWithoutBindingInput>
}

export type RequestAttemptUpdateWithWhereUniqueWithoutBindingInput = {
  where: Prisma.RequestAttemptWhereUniqueInput
  data: Prisma.XOR<Prisma.RequestAttemptUpdateWithoutBindingInput, Prisma.RequestAttemptUncheckedUpdateWithoutBindingInput>
}

export type RequestAttemptUpdateManyWithWhereWithoutBindingInput = {
  where: Prisma.RequestAttemptScalarWhereInput
  data: Prisma.XOR<Prisma.RequestAttemptUpdateManyMutationInput, Prisma.RequestAttemptUncheckedUpdateManyWithoutBindingInput>
}

export type RequestAttemptCreateWithoutRequestInput = {
  id: string
  upstreamModelId: string
  attemptIndex: number
  status: string
  errorCode?: string | null
  errorMessage?: string | null
  durationMilliseconds: number
  createdTime: bigint | number
  provider: Prisma.ProviderCreateNestedOneWithoutAttemptsInput
  binding: Prisma.ModelBindingCreateNestedOneWithoutAttemptsInput
}

export type RequestAttemptUncheckedCreateWithoutRequestInput = {
  id: string
  providerId: string
  bindingId: string
  upstreamModelId: string
  attemptIndex: number
  status: string
  errorCode?: string | null
  errorMessage?: string | null
  durationMilliseconds: number
  createdTime: bigint | number
}

export type RequestAttemptCreateOrConnectWithoutRequestInput = {
  where: Prisma.RequestAttemptWhereUniqueInput
  create: Prisma.XOR<Prisma.RequestAttemptCreateWithoutRequestInput, Prisma.RequestAttemptUncheckedCreateWithoutRequestInput>
}

export type RequestAttemptCreateManyRequestInputEnvelope = {
  data: Prisma.RequestAttemptCreateManyRequestInput | Prisma.RequestAttemptCreateManyRequestInput[]
}

export type RequestAttemptUpsertWithWhereUniqueWithoutRequestInput = {
  where: Prisma.RequestAttemptWhereUniqueInput
  update: Prisma.XOR<Prisma.RequestAttemptUpdateWithoutRequestInput, Prisma.RequestAttemptUncheckedUpdateWithoutRequestInput>
  create: Prisma.XOR<Prisma.RequestAttemptCreateWithoutRequestInput, Prisma.RequestAttemptUncheckedCreateWithoutRequestInput>
}

export type RequestAttemptUpdateWithWhereUniqueWithoutRequestInput = {
  where: Prisma.RequestAttemptWhereUniqueInput
  data: Prisma.XOR<Prisma.RequestAttemptUpdateWithoutRequestInput, Prisma.RequestAttemptUncheckedUpdateWithoutRequestInput>
}

export type RequestAttemptUpdateManyWithWhereWithoutRequestInput = {
  where: Prisma.RequestAttemptScalarWhereInput
  data: Prisma.XOR<Prisma.RequestAttemptUpdateManyMutationInput, Prisma.RequestAttemptUncheckedUpdateManyWithoutRequestInput>
}

export type RequestAttemptCreateManyProviderInput = {
  id: string
  requestId: string
  bindingId: string
  upstreamModelId: string
  attemptIndex: number
  status: string
  errorCode?: string | null
  errorMessage?: string | null
  durationMilliseconds: number
  createdTime: bigint | number
}

export type RequestAttemptUpdateWithoutProviderInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  upstreamModelId?: Prisma.StringFieldUpdateOperationsInput | string
  attemptIndex?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.StringFieldUpdateOperationsInput | string
  errorCode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  errorMessage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  durationMilliseconds?: Prisma.IntFieldUpdateOperationsInput | number
  createdTime?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  request?: Prisma.RequestLogUpdateOneRequiredWithoutAttemptsNestedInput
  binding?: Prisma.ModelBindingUpdateOneRequiredWithoutAttemptsNestedInput
}

export type RequestAttemptUncheckedUpdateWithoutProviderInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  requestId?: Prisma.StringFieldUpdateOperationsInput | string
  bindingId?: Prisma.StringFieldUpdateOperationsInput | string
  upstreamModelId?: Prisma.StringFieldUpdateOperationsInput | string
  attemptIndex?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.StringFieldUpdateOperationsInput | string
  errorCode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  errorMessage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  durationMilliseconds?: Prisma.IntFieldUpdateOperationsInput | number
  createdTime?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
}

export type RequestAttemptUncheckedUpdateManyWithoutProviderInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  requestId?: Prisma.StringFieldUpdateOperationsInput | string
  bindingId?: Prisma.StringFieldUpdateOperationsInput | string
  upstreamModelId?: Prisma.StringFieldUpdateOperationsInput | string
  attemptIndex?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.StringFieldUpdateOperationsInput | string
  errorCode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  errorMessage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  durationMilliseconds?: Prisma.IntFieldUpdateOperationsInput | number
  createdTime?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
}

export type RequestAttemptCreateManyBindingInput = {
  id: string
  requestId: string
  providerId: string
  upstreamModelId: string
  attemptIndex: number
  status: string
  errorCode?: string | null
  errorMessage?: string | null
  durationMilliseconds: number
  createdTime: bigint | number
}

export type RequestAttemptUpdateWithoutBindingInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  upstreamModelId?: Prisma.StringFieldUpdateOperationsInput | string
  attemptIndex?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.StringFieldUpdateOperationsInput | string
  errorCode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  errorMessage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  durationMilliseconds?: Prisma.IntFieldUpdateOperationsInput | number
  createdTime?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  request?: Prisma.RequestLogUpdateOneRequiredWithoutAttemptsNestedInput
  provider?: Prisma.ProviderUpdateOneRequiredWithoutAttemptsNestedInput
}

export type RequestAttemptUncheckedUpdateWithoutBindingInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  requestId?: Prisma.StringFieldUpdateOperationsInput | string
  providerId?: Prisma.StringFieldUpdateOperationsInput | string
  upstreamModelId?: Prisma.StringFieldUpdateOperationsInput | string
  attemptIndex?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.StringFieldUpdateOperationsInput | string
  errorCode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  errorMessage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  durationMilliseconds?: Prisma.IntFieldUpdateOperationsInput | number
  createdTime?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
}

export type RequestAttemptUncheckedUpdateManyWithoutBindingInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  requestId?: Prisma.StringFieldUpdateOperationsInput | string
  providerId?: Prisma.StringFieldUpdateOperationsInput | string
  upstreamModelId?: Prisma.StringFieldUpdateOperationsInput | string
  attemptIndex?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.StringFieldUpdateOperationsInput | string
  errorCode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  errorMessage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  durationMilliseconds?: Prisma.IntFieldUpdateOperationsInput | number
  createdTime?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
}

export type RequestAttemptCreateManyRequestInput = {
  id: string
  providerId: string
  bindingId: string
  upstreamModelId: string
  attemptIndex: number
  status: string
  errorCode?: string | null
  errorMessage?: string | null
  durationMilliseconds: number
  createdTime: bigint | number
}

export type RequestAttemptUpdateWithoutRequestInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  upstreamModelId?: Prisma.StringFieldUpdateOperationsInput | string
  attemptIndex?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.StringFieldUpdateOperationsInput | string
  errorCode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  errorMessage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  durationMilliseconds?: Prisma.IntFieldUpdateOperationsInput | number
  createdTime?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  provider?: Prisma.ProviderUpdateOneRequiredWithoutAttemptsNestedInput
  binding?: Prisma.ModelBindingUpdateOneRequiredWithoutAttemptsNestedInput
}

export type RequestAttemptUncheckedUpdateWithoutRequestInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  providerId?: Prisma.StringFieldUpdateOperationsInput | string
  bindingId?: Prisma.StringFieldUpdateOperationsInput | string
  upstreamModelId?: Prisma.StringFieldUpdateOperationsInput | string
  attemptIndex?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.StringFieldUpdateOperationsInput | string
  errorCode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  errorMessage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  durationMilliseconds?: Prisma.IntFieldUpdateOperationsInput | number
  createdTime?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
}

export type RequestAttemptUncheckedUpdateManyWithoutRequestInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  providerId?: Prisma.StringFieldUpdateOperationsInput | string
  bindingId?: Prisma.StringFieldUpdateOperationsInput | string
  upstreamModelId?: Prisma.StringFieldUpdateOperationsInput | string
  attemptIndex?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.StringFieldUpdateOperationsInput | string
  errorCode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  errorMessage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  durationMilliseconds?: Prisma.IntFieldUpdateOperationsInput | number
  createdTime?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
}



export type RequestAttemptSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  requestId?: boolean
  providerId?: boolean
  bindingId?: boolean
  upstreamModelId?: boolean
  attemptIndex?: boolean
  status?: boolean
  errorCode?: boolean
  errorMessage?: boolean
  durationMilliseconds?: boolean
  createdTime?: boolean
  request?: boolean | Prisma.RequestLogDefaultArgs<ExtArgs>
  provider?: boolean | Prisma.ProviderDefaultArgs<ExtArgs>
  binding?: boolean | Prisma.ModelBindingDefaultArgs<ExtArgs>
}, ExtArgs["result"]["requestAttempt"]>

export type RequestAttemptSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  requestId?: boolean
  providerId?: boolean
  bindingId?: boolean
  upstreamModelId?: boolean
  attemptIndex?: boolean
  status?: boolean
  errorCode?: boolean
  errorMessage?: boolean
  durationMilliseconds?: boolean
  createdTime?: boolean
  request?: boolean | Prisma.RequestLogDefaultArgs<ExtArgs>
  provider?: boolean | Prisma.ProviderDefaultArgs<ExtArgs>
  binding?: boolean | Prisma.ModelBindingDefaultArgs<ExtArgs>
}, ExtArgs["result"]["requestAttempt"]>

export type RequestAttemptSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  requestId?: boolean
  providerId?: boolean
  bindingId?: boolean
  upstreamModelId?: boolean
  attemptIndex?: boolean
  status?: boolean
  errorCode?: boolean
  errorMessage?: boolean
  durationMilliseconds?: boolean
  createdTime?: boolean
  request?: boolean | Prisma.RequestLogDefaultArgs<ExtArgs>
  provider?: boolean | Prisma.ProviderDefaultArgs<ExtArgs>
  binding?: boolean | Prisma.ModelBindingDefaultArgs<ExtArgs>
}, ExtArgs["result"]["requestAttempt"]>

export type RequestAttemptSelectScalar = {
  id?: boolean
  requestId?: boolean
  providerId?: boolean
  bindingId?: boolean
  upstreamModelId?: boolean
  attemptIndex?: boolean
  status?: boolean
  errorCode?: boolean
  errorMessage?: boolean
  durationMilliseconds?: boolean
  createdTime?: boolean
}

export type RequestAttemptOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "requestId" | "providerId" | "bindingId" | "upstreamModelId" | "attemptIndex" | "status" | "errorCode" | "errorMessage" | "durationMilliseconds" | "createdTime", ExtArgs["result"]["requestAttempt"]>
export type RequestAttemptInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  request?: boolean | Prisma.RequestLogDefaultArgs<ExtArgs>
  provider?: boolean | Prisma.ProviderDefaultArgs<ExtArgs>
  binding?: boolean | Prisma.ModelBindingDefaultArgs<ExtArgs>
}
export type RequestAttemptIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  request?: boolean | Prisma.RequestLogDefaultArgs<ExtArgs>
  provider?: boolean | Prisma.ProviderDefaultArgs<ExtArgs>
  binding?: boolean | Prisma.ModelBindingDefaultArgs<ExtArgs>
}
export type RequestAttemptIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  request?: boolean | Prisma.RequestLogDefaultArgs<ExtArgs>
  provider?: boolean | Prisma.ProviderDefaultArgs<ExtArgs>
  binding?: boolean | Prisma.ModelBindingDefaultArgs<ExtArgs>
}

export type $RequestAttemptPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "RequestAttempt"
  objects: {
    request: Prisma.$RequestLogPayload<ExtArgs>
    provider: Prisma.$ProviderPayload<ExtArgs>
    binding: Prisma.$ModelBindingPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    requestId: string
    providerId: string
    bindingId: string
    upstreamModelId: string
    attemptIndex: number
    status: string
    errorCode: string | null
    errorMessage: string | null
    durationMilliseconds: number
    createdTime: bigint
  }, ExtArgs["result"]["requestAttempt"]>
  composites: {}
}

export type RequestAttemptGetPayload<S extends boolean | null | undefined | RequestAttemptDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$RequestAttemptPayload, S>

export type RequestAttemptCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<RequestAttemptFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: RequestAttemptCountAggregateInputType | true
  }

export interface RequestAttemptDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['RequestAttempt'], meta: { name: 'RequestAttempt' } }
  /**
   * Find zero or one RequestAttempt that matches the filter.
   * @param {RequestAttemptFindUniqueArgs} args - Arguments to find a RequestAttempt
   * @example
   * // Get one RequestAttempt
   * const requestAttempt = await prisma.requestAttempt.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends RequestAttemptFindUniqueArgs>(args: Prisma.SelectSubset<T, RequestAttemptFindUniqueArgs<ExtArgs>>): Prisma.Prisma__RequestAttemptClient<runtime.Types.Result.GetResult<Prisma.$RequestAttemptPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one RequestAttempt that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {RequestAttemptFindUniqueOrThrowArgs} args - Arguments to find a RequestAttempt
   * @example
   * // Get one RequestAttempt
   * const requestAttempt = await prisma.requestAttempt.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends RequestAttemptFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, RequestAttemptFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__RequestAttemptClient<runtime.Types.Result.GetResult<Prisma.$RequestAttemptPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first RequestAttempt that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RequestAttemptFindFirstArgs} args - Arguments to find a RequestAttempt
   * @example
   * // Get one RequestAttempt
   * const requestAttempt = await prisma.requestAttempt.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends RequestAttemptFindFirstArgs>(args?: Prisma.SelectSubset<T, RequestAttemptFindFirstArgs<ExtArgs>>): Prisma.Prisma__RequestAttemptClient<runtime.Types.Result.GetResult<Prisma.$RequestAttemptPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first RequestAttempt that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RequestAttemptFindFirstOrThrowArgs} args - Arguments to find a RequestAttempt
   * @example
   * // Get one RequestAttempt
   * const requestAttempt = await prisma.requestAttempt.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends RequestAttemptFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, RequestAttemptFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__RequestAttemptClient<runtime.Types.Result.GetResult<Prisma.$RequestAttemptPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more RequestAttempts that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RequestAttemptFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all RequestAttempts
   * const requestAttempts = await prisma.requestAttempt.findMany()
   * 
   * // Get first 10 RequestAttempts
   * const requestAttempts = await prisma.requestAttempt.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const requestAttemptWithIdOnly = await prisma.requestAttempt.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends RequestAttemptFindManyArgs>(args?: Prisma.SelectSubset<T, RequestAttemptFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RequestAttemptPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a RequestAttempt.
   * @param {RequestAttemptCreateArgs} args - Arguments to create a RequestAttempt.
   * @example
   * // Create one RequestAttempt
   * const RequestAttempt = await prisma.requestAttempt.create({
   *   data: {
   *     // ... data to create a RequestAttempt
   *   }
   * })
   * 
   */
  create<T extends RequestAttemptCreateArgs>(args: Prisma.SelectSubset<T, RequestAttemptCreateArgs<ExtArgs>>): Prisma.Prisma__RequestAttemptClient<runtime.Types.Result.GetResult<Prisma.$RequestAttemptPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many RequestAttempts.
   * @param {RequestAttemptCreateManyArgs} args - Arguments to create many RequestAttempts.
   * @example
   * // Create many RequestAttempts
   * const requestAttempt = await prisma.requestAttempt.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends RequestAttemptCreateManyArgs>(args?: Prisma.SelectSubset<T, RequestAttemptCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many RequestAttempts and returns the data saved in the database.
   * @param {RequestAttemptCreateManyAndReturnArgs} args - Arguments to create many RequestAttempts.
   * @example
   * // Create many RequestAttempts
   * const requestAttempt = await prisma.requestAttempt.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many RequestAttempts and only return the `id`
   * const requestAttemptWithIdOnly = await prisma.requestAttempt.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends RequestAttemptCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, RequestAttemptCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RequestAttemptPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a RequestAttempt.
   * @param {RequestAttemptDeleteArgs} args - Arguments to delete one RequestAttempt.
   * @example
   * // Delete one RequestAttempt
   * const RequestAttempt = await prisma.requestAttempt.delete({
   *   where: {
   *     // ... filter to delete one RequestAttempt
   *   }
   * })
   * 
   */
  delete<T extends RequestAttemptDeleteArgs>(args: Prisma.SelectSubset<T, RequestAttemptDeleteArgs<ExtArgs>>): Prisma.Prisma__RequestAttemptClient<runtime.Types.Result.GetResult<Prisma.$RequestAttemptPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one RequestAttempt.
   * @param {RequestAttemptUpdateArgs} args - Arguments to update one RequestAttempt.
   * @example
   * // Update one RequestAttempt
   * const requestAttempt = await prisma.requestAttempt.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends RequestAttemptUpdateArgs>(args: Prisma.SelectSubset<T, RequestAttemptUpdateArgs<ExtArgs>>): Prisma.Prisma__RequestAttemptClient<runtime.Types.Result.GetResult<Prisma.$RequestAttemptPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more RequestAttempts.
   * @param {RequestAttemptDeleteManyArgs} args - Arguments to filter RequestAttempts to delete.
   * @example
   * // Delete a few RequestAttempts
   * const { count } = await prisma.requestAttempt.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends RequestAttemptDeleteManyArgs>(args?: Prisma.SelectSubset<T, RequestAttemptDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more RequestAttempts.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RequestAttemptUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many RequestAttempts
   * const requestAttempt = await prisma.requestAttempt.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends RequestAttemptUpdateManyArgs>(args: Prisma.SelectSubset<T, RequestAttemptUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more RequestAttempts and returns the data updated in the database.
   * @param {RequestAttemptUpdateManyAndReturnArgs} args - Arguments to update many RequestAttempts.
   * @example
   * // Update many RequestAttempts
   * const requestAttempt = await prisma.requestAttempt.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more RequestAttempts and only return the `id`
   * const requestAttemptWithIdOnly = await prisma.requestAttempt.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends RequestAttemptUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, RequestAttemptUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RequestAttemptPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one RequestAttempt.
   * @param {RequestAttemptUpsertArgs} args - Arguments to update or create a RequestAttempt.
   * @example
   * // Update or create a RequestAttempt
   * const requestAttempt = await prisma.requestAttempt.upsert({
   *   create: {
   *     // ... data to create a RequestAttempt
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the RequestAttempt we want to update
   *   }
   * })
   */
  upsert<T extends RequestAttemptUpsertArgs>(args: Prisma.SelectSubset<T, RequestAttemptUpsertArgs<ExtArgs>>): Prisma.Prisma__RequestAttemptClient<runtime.Types.Result.GetResult<Prisma.$RequestAttemptPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of RequestAttempts.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RequestAttemptCountArgs} args - Arguments to filter RequestAttempts to count.
   * @example
   * // Count the number of RequestAttempts
   * const count = await prisma.requestAttempt.count({
   *   where: {
   *     // ... the filter for the RequestAttempts we want to count
   *   }
   * })
  **/
  count<T extends RequestAttemptCountArgs>(
    args?: Prisma.Subset<T, RequestAttemptCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], RequestAttemptCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a RequestAttempt.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RequestAttemptAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends RequestAttemptAggregateArgs>(args: Prisma.Subset<T, RequestAttemptAggregateArgs>): Prisma.PrismaPromise<GetRequestAttemptAggregateType<T>>

  /**
   * Group by RequestAttempt.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RequestAttemptGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends RequestAttemptGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: RequestAttemptGroupByArgs['orderBy'] }
      : { orderBy?: RequestAttemptGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, RequestAttemptGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetRequestAttemptGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the RequestAttempt model
 */
readonly fields: RequestAttemptFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for RequestAttempt.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__RequestAttemptClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  request<T extends Prisma.RequestLogDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.RequestLogDefaultArgs<ExtArgs>>): Prisma.Prisma__RequestLogClient<runtime.Types.Result.GetResult<Prisma.$RequestLogPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  provider<T extends Prisma.ProviderDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ProviderDefaultArgs<ExtArgs>>): Prisma.Prisma__ProviderClient<runtime.Types.Result.GetResult<Prisma.$ProviderPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  binding<T extends Prisma.ModelBindingDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ModelBindingDefaultArgs<ExtArgs>>): Prisma.Prisma__ModelBindingClient<runtime.Types.Result.GetResult<Prisma.$ModelBindingPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the RequestAttempt model
 */
export interface RequestAttemptFieldRefs {
  readonly id: Prisma.FieldRef<"RequestAttempt", 'String'>
  readonly requestId: Prisma.FieldRef<"RequestAttempt", 'String'>
  readonly providerId: Prisma.FieldRef<"RequestAttempt", 'String'>
  readonly bindingId: Prisma.FieldRef<"RequestAttempt", 'String'>
  readonly upstreamModelId: Prisma.FieldRef<"RequestAttempt", 'String'>
  readonly attemptIndex: Prisma.FieldRef<"RequestAttempt", 'Int'>
  readonly status: Prisma.FieldRef<"RequestAttempt", 'String'>
  readonly errorCode: Prisma.FieldRef<"RequestAttempt", 'String'>
  readonly errorMessage: Prisma.FieldRef<"RequestAttempt", 'String'>
  readonly durationMilliseconds: Prisma.FieldRef<"RequestAttempt", 'Int'>
  readonly createdTime: Prisma.FieldRef<"RequestAttempt", 'BigInt'>
}
    

// Custom InputTypes
/**
 * RequestAttempt findUnique
 */
export type RequestAttemptFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RequestAttempt
   */
  select?: Prisma.RequestAttemptSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RequestAttempt
   */
  omit?: Prisma.RequestAttemptOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RequestAttemptInclude<ExtArgs> | null
  /**
   * Filter, which RequestAttempt to fetch.
   */
  where: Prisma.RequestAttemptWhereUniqueInput
}

/**
 * RequestAttempt findUniqueOrThrow
 */
export type RequestAttemptFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RequestAttempt
   */
  select?: Prisma.RequestAttemptSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RequestAttempt
   */
  omit?: Prisma.RequestAttemptOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RequestAttemptInclude<ExtArgs> | null
  /**
   * Filter, which RequestAttempt to fetch.
   */
  where: Prisma.RequestAttemptWhereUniqueInput
}

/**
 * RequestAttempt findFirst
 */
export type RequestAttemptFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RequestAttempt
   */
  select?: Prisma.RequestAttemptSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RequestAttempt
   */
  omit?: Prisma.RequestAttemptOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RequestAttemptInclude<ExtArgs> | null
  /**
   * Filter, which RequestAttempt to fetch.
   */
  where?: Prisma.RequestAttemptWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RequestAttempts to fetch.
   */
  orderBy?: Prisma.RequestAttemptOrderByWithRelationInput | Prisma.RequestAttemptOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for RequestAttempts.
   */
  cursor?: Prisma.RequestAttemptWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RequestAttempts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RequestAttempts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of RequestAttempts.
   */
  distinct?: Prisma.RequestAttemptScalarFieldEnum | Prisma.RequestAttemptScalarFieldEnum[]
}

/**
 * RequestAttempt findFirstOrThrow
 */
export type RequestAttemptFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RequestAttempt
   */
  select?: Prisma.RequestAttemptSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RequestAttempt
   */
  omit?: Prisma.RequestAttemptOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RequestAttemptInclude<ExtArgs> | null
  /**
   * Filter, which RequestAttempt to fetch.
   */
  where?: Prisma.RequestAttemptWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RequestAttempts to fetch.
   */
  orderBy?: Prisma.RequestAttemptOrderByWithRelationInput | Prisma.RequestAttemptOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for RequestAttempts.
   */
  cursor?: Prisma.RequestAttemptWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RequestAttempts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RequestAttempts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of RequestAttempts.
   */
  distinct?: Prisma.RequestAttemptScalarFieldEnum | Prisma.RequestAttemptScalarFieldEnum[]
}

/**
 * RequestAttempt findMany
 */
export type RequestAttemptFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RequestAttempt
   */
  select?: Prisma.RequestAttemptSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RequestAttempt
   */
  omit?: Prisma.RequestAttemptOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RequestAttemptInclude<ExtArgs> | null
  /**
   * Filter, which RequestAttempts to fetch.
   */
  where?: Prisma.RequestAttemptWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RequestAttempts to fetch.
   */
  orderBy?: Prisma.RequestAttemptOrderByWithRelationInput | Prisma.RequestAttemptOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing RequestAttempts.
   */
  cursor?: Prisma.RequestAttemptWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RequestAttempts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RequestAttempts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of RequestAttempts.
   */
  distinct?: Prisma.RequestAttemptScalarFieldEnum | Prisma.RequestAttemptScalarFieldEnum[]
}

/**
 * RequestAttempt create
 */
export type RequestAttemptCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RequestAttempt
   */
  select?: Prisma.RequestAttemptSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RequestAttempt
   */
  omit?: Prisma.RequestAttemptOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RequestAttemptInclude<ExtArgs> | null
  /**
   * The data needed to create a RequestAttempt.
   */
  data: Prisma.XOR<Prisma.RequestAttemptCreateInput, Prisma.RequestAttemptUncheckedCreateInput>
}

/**
 * RequestAttempt createMany
 */
export type RequestAttemptCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many RequestAttempts.
   */
  data: Prisma.RequestAttemptCreateManyInput | Prisma.RequestAttemptCreateManyInput[]
}

/**
 * RequestAttempt createManyAndReturn
 */
export type RequestAttemptCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RequestAttempt
   */
  select?: Prisma.RequestAttemptSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the RequestAttempt
   */
  omit?: Prisma.RequestAttemptOmit<ExtArgs> | null
  /**
   * The data used to create many RequestAttempts.
   */
  data: Prisma.RequestAttemptCreateManyInput | Prisma.RequestAttemptCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RequestAttemptIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * RequestAttempt update
 */
export type RequestAttemptUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RequestAttempt
   */
  select?: Prisma.RequestAttemptSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RequestAttempt
   */
  omit?: Prisma.RequestAttemptOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RequestAttemptInclude<ExtArgs> | null
  /**
   * The data needed to update a RequestAttempt.
   */
  data: Prisma.XOR<Prisma.RequestAttemptUpdateInput, Prisma.RequestAttemptUncheckedUpdateInput>
  /**
   * Choose, which RequestAttempt to update.
   */
  where: Prisma.RequestAttemptWhereUniqueInput
}

/**
 * RequestAttempt updateMany
 */
export type RequestAttemptUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update RequestAttempts.
   */
  data: Prisma.XOR<Prisma.RequestAttemptUpdateManyMutationInput, Prisma.RequestAttemptUncheckedUpdateManyInput>
  /**
   * Filter which RequestAttempts to update
   */
  where?: Prisma.RequestAttemptWhereInput
  /**
   * Limit how many RequestAttempts to update.
   */
  limit?: number
}

/**
 * RequestAttempt updateManyAndReturn
 */
export type RequestAttemptUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RequestAttempt
   */
  select?: Prisma.RequestAttemptSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the RequestAttempt
   */
  omit?: Prisma.RequestAttemptOmit<ExtArgs> | null
  /**
   * The data used to update RequestAttempts.
   */
  data: Prisma.XOR<Prisma.RequestAttemptUpdateManyMutationInput, Prisma.RequestAttemptUncheckedUpdateManyInput>
  /**
   * Filter which RequestAttempts to update
   */
  where?: Prisma.RequestAttemptWhereInput
  /**
   * Limit how many RequestAttempts to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RequestAttemptIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * RequestAttempt upsert
 */
export type RequestAttemptUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RequestAttempt
   */
  select?: Prisma.RequestAttemptSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RequestAttempt
   */
  omit?: Prisma.RequestAttemptOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RequestAttemptInclude<ExtArgs> | null
  /**
   * The filter to search for the RequestAttempt to update in case it exists.
   */
  where: Prisma.RequestAttemptWhereUniqueInput
  /**
   * In case the RequestAttempt found by the `where` argument doesn't exist, create a new RequestAttempt with this data.
   */
  create: Prisma.XOR<Prisma.RequestAttemptCreateInput, Prisma.RequestAttemptUncheckedCreateInput>
  /**
   * In case the RequestAttempt was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.RequestAttemptUpdateInput, Prisma.RequestAttemptUncheckedUpdateInput>
}

/**
 * RequestAttempt delete
 */
export type RequestAttemptDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RequestAttempt
   */
  select?: Prisma.RequestAttemptSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RequestAttempt
   */
  omit?: Prisma.RequestAttemptOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RequestAttemptInclude<ExtArgs> | null
  /**
   * Filter which RequestAttempt to delete.
   */
  where: Prisma.RequestAttemptWhereUniqueInput
}

/**
 * RequestAttempt deleteMany
 */
export type RequestAttemptDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which RequestAttempts to delete
   */
  where?: Prisma.RequestAttemptWhereInput
  /**
   * Limit how many RequestAttempts to delete.
   */
  limit?: number
}

/**
 * RequestAttempt without action
 */
export type RequestAttemptDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RequestAttempt
   */
  select?: Prisma.RequestAttemptSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RequestAttempt
   */
  omit?: Prisma.RequestAttemptOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RequestAttemptInclude<ExtArgs> | null
}
