
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `RequestLog` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model RequestLog
 * 
 */
export type RequestLogModel = runtime.Types.Result.DefaultSelection<Prisma.$RequestLogPayload>

export type AggregateRequestLog = {
  _count: RequestLogCountAggregateOutputType | null
  _avg: RequestLogAvgAggregateOutputType | null
  _sum: RequestLogSumAggregateOutputType | null
  _min: RequestLogMinAggregateOutputType | null
  _max: RequestLogMaxAggregateOutputType | null
}

export type RequestLogAvgAggregateOutputType = {
  totalDurationMilliseconds: number | null
  totalTokens: number | null
  createdTime: number | null
}

export type RequestLogSumAggregateOutputType = {
  totalDurationMilliseconds: number | null
  totalTokens: number | null
  createdTime: bigint | null
}

export type RequestLogMinAggregateOutputType = {
  id: string | null
  logicalModelId: string | null
  protocol: string | null
  status: string | null
  totalDurationMilliseconds: number | null
  totalTokens: number | null
  createdTime: bigint | null
}

export type RequestLogMaxAggregateOutputType = {
  id: string | null
  logicalModelId: string | null
  protocol: string | null
  status: string | null
  totalDurationMilliseconds: number | null
  totalTokens: number | null
  createdTime: bigint | null
}

export type RequestLogCountAggregateOutputType = {
  id: number
  logicalModelId: number
  protocol: number
  status: number
  totalDurationMilliseconds: number
  totalTokens: number
  createdTime: number
  _all: number
}


export type RequestLogAvgAggregateInputType = {
  totalDurationMilliseconds?: true
  totalTokens?: true
  createdTime?: true
}

export type RequestLogSumAggregateInputType = {
  totalDurationMilliseconds?: true
  totalTokens?: true
  createdTime?: true
}

export type RequestLogMinAggregateInputType = {
  id?: true
  logicalModelId?: true
  protocol?: true
  status?: true
  totalDurationMilliseconds?: true
  totalTokens?: true
  createdTime?: true
}

export type RequestLogMaxAggregateInputType = {
  id?: true
  logicalModelId?: true
  protocol?: true
  status?: true
  totalDurationMilliseconds?: true
  totalTokens?: true
  createdTime?: true
}

export type RequestLogCountAggregateInputType = {
  id?: true
  logicalModelId?: true
  protocol?: true
  status?: true
  totalDurationMilliseconds?: true
  totalTokens?: true
  createdTime?: true
  _all?: true
}

export type RequestLogAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which RequestLog to aggregate.
   */
  where?: Prisma.RequestLogWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RequestLogs to fetch.
   */
  orderBy?: Prisma.RequestLogOrderByWithRelationInput | Prisma.RequestLogOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.RequestLogWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RequestLogs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RequestLogs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned RequestLogs
  **/
  _count?: true | RequestLogCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: RequestLogAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: RequestLogSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: RequestLogMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: RequestLogMaxAggregateInputType
}

export type GetRequestLogAggregateType<T extends RequestLogAggregateArgs> = {
      [P in keyof T & keyof AggregateRequestLog]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateRequestLog[P]>
    : Prisma.GetScalarType<T[P], AggregateRequestLog[P]>
}




export type RequestLogGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.RequestLogWhereInput
  orderBy?: Prisma.RequestLogOrderByWithAggregationInput | Prisma.RequestLogOrderByWithAggregationInput[]
  by: Prisma.RequestLogScalarFieldEnum[] | Prisma.RequestLogScalarFieldEnum
  having?: Prisma.RequestLogScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: RequestLogCountAggregateInputType | true
  _avg?: RequestLogAvgAggregateInputType
  _sum?: RequestLogSumAggregateInputType
  _min?: RequestLogMinAggregateInputType
  _max?: RequestLogMaxAggregateInputType
}

export type RequestLogGroupByOutputType = {
  id: string
  logicalModelId: string
  protocol: string
  status: string
  totalDurationMilliseconds: number
  totalTokens: number | null
  createdTime: bigint
  _count: RequestLogCountAggregateOutputType | null
  _avg: RequestLogAvgAggregateOutputType | null
  _sum: RequestLogSumAggregateOutputType | null
  _min: RequestLogMinAggregateOutputType | null
  _max: RequestLogMaxAggregateOutputType | null
}

export type GetRequestLogGroupByPayload<T extends RequestLogGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<RequestLogGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof RequestLogGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], RequestLogGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], RequestLogGroupByOutputType[P]>
      }
    >
  >



export type RequestLogWhereInput = {
  AND?: Prisma.RequestLogWhereInput | Prisma.RequestLogWhereInput[]
  OR?: Prisma.RequestLogWhereInput[]
  NOT?: Prisma.RequestLogWhereInput | Prisma.RequestLogWhereInput[]
  id?: Prisma.StringFilter<"RequestLog"> | string
  logicalModelId?: Prisma.StringFilter<"RequestLog"> | string
  protocol?: Prisma.StringFilter<"RequestLog"> | string
  status?: Prisma.StringFilter<"RequestLog"> | string
  totalDurationMilliseconds?: Prisma.IntFilter<"RequestLog"> | number
  totalTokens?: Prisma.IntNullableFilter<"RequestLog"> | number | null
  createdTime?: Prisma.BigIntFilter<"RequestLog"> | bigint | number
  attempts?: Prisma.RequestAttemptListRelationFilter
}

export type RequestLogOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  logicalModelId?: Prisma.SortOrder
  protocol?: Prisma.SortOrder
  status?: Prisma.SortOrder
  totalDurationMilliseconds?: Prisma.SortOrder
  totalTokens?: Prisma.SortOrderInput | Prisma.SortOrder
  createdTime?: Prisma.SortOrder
  attempts?: Prisma.RequestAttemptOrderByRelationAggregateInput
}

export type RequestLogWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.RequestLogWhereInput | Prisma.RequestLogWhereInput[]
  OR?: Prisma.RequestLogWhereInput[]
  NOT?: Prisma.RequestLogWhereInput | Prisma.RequestLogWhereInput[]
  logicalModelId?: Prisma.StringFilter<"RequestLog"> | string
  protocol?: Prisma.StringFilter<"RequestLog"> | string
  status?: Prisma.StringFilter<"RequestLog"> | string
  totalDurationMilliseconds?: Prisma.IntFilter<"RequestLog"> | number
  totalTokens?: Prisma.IntNullableFilter<"RequestLog"> | number | null
  createdTime?: Prisma.BigIntFilter<"RequestLog"> | bigint | number
  attempts?: Prisma.RequestAttemptListRelationFilter
}, "id">

export type RequestLogOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  logicalModelId?: Prisma.SortOrder
  protocol?: Prisma.SortOrder
  status?: Prisma.SortOrder
  totalDurationMilliseconds?: Prisma.SortOrder
  totalTokens?: Prisma.SortOrderInput | Prisma.SortOrder
  createdTime?: Prisma.SortOrder
  _count?: Prisma.RequestLogCountOrderByAggregateInput
  _avg?: Prisma.RequestLogAvgOrderByAggregateInput
  _max?: Prisma.RequestLogMaxOrderByAggregateInput
  _min?: Prisma.RequestLogMinOrderByAggregateInput
  _sum?: Prisma.RequestLogSumOrderByAggregateInput
}

export type RequestLogScalarWhereWithAggregatesInput = {
  AND?: Prisma.RequestLogScalarWhereWithAggregatesInput | Prisma.RequestLogScalarWhereWithAggregatesInput[]
  OR?: Prisma.RequestLogScalarWhereWithAggregatesInput[]
  NOT?: Prisma.RequestLogScalarWhereWithAggregatesInput | Prisma.RequestLogScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"RequestLog"> | string
  logicalModelId?: Prisma.StringWithAggregatesFilter<"RequestLog"> | string
  protocol?: Prisma.StringWithAggregatesFilter<"RequestLog"> | string
  status?: Prisma.StringWithAggregatesFilter<"RequestLog"> | string
  totalDurationMilliseconds?: Prisma.IntWithAggregatesFilter<"RequestLog"> | number
  totalTokens?: Prisma.IntNullableWithAggregatesFilter<"RequestLog"> | number | null
  createdTime?: Prisma.BigIntWithAggregatesFilter<"RequestLog"> | bigint | number
}

export type RequestLogCreateInput = {
  id: string
  logicalModelId: string
  protocol: string
  status: string
  totalDurationMilliseconds: number
  totalTokens?: number | null
  createdTime: bigint | number
  attempts?: Prisma.RequestAttemptCreateNestedManyWithoutRequestInput
}

export type RequestLogUncheckedCreateInput = {
  id: string
  logicalModelId: string
  protocol: string
  status: string
  totalDurationMilliseconds: number
  totalTokens?: number | null
  createdTime: bigint | number
  attempts?: Prisma.RequestAttemptUncheckedCreateNestedManyWithoutRequestInput
}

export type RequestLogUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  logicalModelId?: Prisma.StringFieldUpdateOperationsInput | string
  protocol?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  totalDurationMilliseconds?: Prisma.IntFieldUpdateOperationsInput | number
  totalTokens?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdTime?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  attempts?: Prisma.RequestAttemptUpdateManyWithoutRequestNestedInput
}

export type RequestLogUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  logicalModelId?: Prisma.StringFieldUpdateOperationsInput | string
  protocol?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  totalDurationMilliseconds?: Prisma.IntFieldUpdateOperationsInput | number
  totalTokens?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdTime?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  attempts?: Prisma.RequestAttemptUncheckedUpdateManyWithoutRequestNestedInput
}

export type RequestLogCreateManyInput = {
  id: string
  logicalModelId: string
  protocol: string
  status: string
  totalDurationMilliseconds: number
  totalTokens?: number | null
  createdTime: bigint | number
}

export type RequestLogUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  logicalModelId?: Prisma.StringFieldUpdateOperationsInput | string
  protocol?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  totalDurationMilliseconds?: Prisma.IntFieldUpdateOperationsInput | number
  totalTokens?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdTime?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
}

export type RequestLogUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  logicalModelId?: Prisma.StringFieldUpdateOperationsInput | string
  protocol?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  totalDurationMilliseconds?: Prisma.IntFieldUpdateOperationsInput | number
  totalTokens?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdTime?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
}

export type RequestLogCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  logicalModelId?: Prisma.SortOrder
  protocol?: Prisma.SortOrder
  status?: Prisma.SortOrder
  totalDurationMilliseconds?: Prisma.SortOrder
  totalTokens?: Prisma.SortOrder
  createdTime?: Prisma.SortOrder
}

export type RequestLogAvgOrderByAggregateInput = {
  totalDurationMilliseconds?: Prisma.SortOrder
  totalTokens?: Prisma.SortOrder
  createdTime?: Prisma.SortOrder
}

export type RequestLogMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  logicalModelId?: Prisma.SortOrder
  protocol?: Prisma.SortOrder
  status?: Prisma.SortOrder
  totalDurationMilliseconds?: Prisma.SortOrder
  totalTokens?: Prisma.SortOrder
  createdTime?: Prisma.SortOrder
}

export type RequestLogMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  logicalModelId?: Prisma.SortOrder
  protocol?: Prisma.SortOrder
  status?: Prisma.SortOrder
  totalDurationMilliseconds?: Prisma.SortOrder
  totalTokens?: Prisma.SortOrder
  createdTime?: Prisma.SortOrder
}

export type RequestLogSumOrderByAggregateInput = {
  totalDurationMilliseconds?: Prisma.SortOrder
  totalTokens?: Prisma.SortOrder
  createdTime?: Prisma.SortOrder
}

export type RequestLogScalarRelationFilter = {
  is?: Prisma.RequestLogWhereInput
  isNot?: Prisma.RequestLogWhereInput
}

export type NullableIntFieldUpdateOperationsInput = {
  set?: number | null
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type RequestLogCreateNestedOneWithoutAttemptsInput = {
  create?: Prisma.XOR<Prisma.RequestLogCreateWithoutAttemptsInput, Prisma.RequestLogUncheckedCreateWithoutAttemptsInput>
  connectOrCreate?: Prisma.RequestLogCreateOrConnectWithoutAttemptsInput
  connect?: Prisma.RequestLogWhereUniqueInput
}

export type RequestLogUpdateOneRequiredWithoutAttemptsNestedInput = {
  create?: Prisma.XOR<Prisma.RequestLogCreateWithoutAttemptsInput, Prisma.RequestLogUncheckedCreateWithoutAttemptsInput>
  connectOrCreate?: Prisma.RequestLogCreateOrConnectWithoutAttemptsInput
  upsert?: Prisma.RequestLogUpsertWithoutAttemptsInput
  connect?: Prisma.RequestLogWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.RequestLogUpdateToOneWithWhereWithoutAttemptsInput, Prisma.RequestLogUpdateWithoutAttemptsInput>, Prisma.RequestLogUncheckedUpdateWithoutAttemptsInput>
}

export type RequestLogCreateWithoutAttemptsInput = {
  id: string
  logicalModelId: string
  protocol: string
  status: string
  totalDurationMilliseconds: number
  totalTokens?: number | null
  createdTime: bigint | number
}

export type RequestLogUncheckedCreateWithoutAttemptsInput = {
  id: string
  logicalModelId: string
  protocol: string
  status: string
  totalDurationMilliseconds: number
  totalTokens?: number | null
  createdTime: bigint | number
}

export type RequestLogCreateOrConnectWithoutAttemptsInput = {
  where: Prisma.RequestLogWhereUniqueInput
  create: Prisma.XOR<Prisma.RequestLogCreateWithoutAttemptsInput, Prisma.RequestLogUncheckedCreateWithoutAttemptsInput>
}

export type RequestLogUpsertWithoutAttemptsInput = {
  update: Prisma.XOR<Prisma.RequestLogUpdateWithoutAttemptsInput, Prisma.RequestLogUncheckedUpdateWithoutAttemptsInput>
  create: Prisma.XOR<Prisma.RequestLogCreateWithoutAttemptsInput, Prisma.RequestLogUncheckedCreateWithoutAttemptsInput>
  where?: Prisma.RequestLogWhereInput
}

export type RequestLogUpdateToOneWithWhereWithoutAttemptsInput = {
  where?: Prisma.RequestLogWhereInput
  data: Prisma.XOR<Prisma.RequestLogUpdateWithoutAttemptsInput, Prisma.RequestLogUncheckedUpdateWithoutAttemptsInput>
}

export type RequestLogUpdateWithoutAttemptsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  logicalModelId?: Prisma.StringFieldUpdateOperationsInput | string
  protocol?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  totalDurationMilliseconds?: Prisma.IntFieldUpdateOperationsInput | number
  totalTokens?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdTime?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
}

export type RequestLogUncheckedUpdateWithoutAttemptsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  logicalModelId?: Prisma.StringFieldUpdateOperationsInput | string
  protocol?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  totalDurationMilliseconds?: Prisma.IntFieldUpdateOperationsInput | number
  totalTokens?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdTime?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
}


/**
 * Count Type RequestLogCountOutputType
 */

export type RequestLogCountOutputType = {
  attempts: number
}

export type RequestLogCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  attempts?: boolean | RequestLogCountOutputTypeCountAttemptsArgs
}

/**
 * RequestLogCountOutputType without action
 */
export type RequestLogCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RequestLogCountOutputType
   */
  select?: Prisma.RequestLogCountOutputTypeSelect<ExtArgs> | null
}

/**
 * RequestLogCountOutputType without action
 */
export type RequestLogCountOutputTypeCountAttemptsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.RequestAttemptWhereInput
}


export type RequestLogSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  logicalModelId?: boolean
  protocol?: boolean
  status?: boolean
  totalDurationMilliseconds?: boolean
  totalTokens?: boolean
  createdTime?: boolean
  attempts?: boolean | Prisma.RequestLog$attemptsArgs<ExtArgs>
  _count?: boolean | Prisma.RequestLogCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["requestLog"]>

export type RequestLogSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  logicalModelId?: boolean
  protocol?: boolean
  status?: boolean
  totalDurationMilliseconds?: boolean
  totalTokens?: boolean
  createdTime?: boolean
}, ExtArgs["result"]["requestLog"]>

export type RequestLogSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  logicalModelId?: boolean
  protocol?: boolean
  status?: boolean
  totalDurationMilliseconds?: boolean
  totalTokens?: boolean
  createdTime?: boolean
}, ExtArgs["result"]["requestLog"]>

export type RequestLogSelectScalar = {
  id?: boolean
  logicalModelId?: boolean
  protocol?: boolean
  status?: boolean
  totalDurationMilliseconds?: boolean
  totalTokens?: boolean
  createdTime?: boolean
}

export type RequestLogOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "logicalModelId" | "protocol" | "status" | "totalDurationMilliseconds" | "totalTokens" | "createdTime", ExtArgs["result"]["requestLog"]>
export type RequestLogInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  attempts?: boolean | Prisma.RequestLog$attemptsArgs<ExtArgs>
  _count?: boolean | Prisma.RequestLogCountOutputTypeDefaultArgs<ExtArgs>
}
export type RequestLogIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type RequestLogIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $RequestLogPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "RequestLog"
  objects: {
    attempts: Prisma.$RequestAttemptPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    logicalModelId: string
    protocol: string
    status: string
    totalDurationMilliseconds: number
    totalTokens: number | null
    createdTime: bigint
  }, ExtArgs["result"]["requestLog"]>
  composites: {}
}

export type RequestLogGetPayload<S extends boolean | null | undefined | RequestLogDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$RequestLogPayload, S>

export type RequestLogCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<RequestLogFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: RequestLogCountAggregateInputType | true
  }

export interface RequestLogDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['RequestLog'], meta: { name: 'RequestLog' } }
  /**
   * Find zero or one RequestLog that matches the filter.
   * @param {RequestLogFindUniqueArgs} args - Arguments to find a RequestLog
   * @example
   * // Get one RequestLog
   * const requestLog = await prisma.requestLog.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends RequestLogFindUniqueArgs>(args: Prisma.SelectSubset<T, RequestLogFindUniqueArgs<ExtArgs>>): Prisma.Prisma__RequestLogClient<runtime.Types.Result.GetResult<Prisma.$RequestLogPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one RequestLog that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {RequestLogFindUniqueOrThrowArgs} args - Arguments to find a RequestLog
   * @example
   * // Get one RequestLog
   * const requestLog = await prisma.requestLog.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends RequestLogFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, RequestLogFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__RequestLogClient<runtime.Types.Result.GetResult<Prisma.$RequestLogPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first RequestLog that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RequestLogFindFirstArgs} args - Arguments to find a RequestLog
   * @example
   * // Get one RequestLog
   * const requestLog = await prisma.requestLog.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends RequestLogFindFirstArgs>(args?: Prisma.SelectSubset<T, RequestLogFindFirstArgs<ExtArgs>>): Prisma.Prisma__RequestLogClient<runtime.Types.Result.GetResult<Prisma.$RequestLogPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first RequestLog that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RequestLogFindFirstOrThrowArgs} args - Arguments to find a RequestLog
   * @example
   * // Get one RequestLog
   * const requestLog = await prisma.requestLog.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends RequestLogFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, RequestLogFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__RequestLogClient<runtime.Types.Result.GetResult<Prisma.$RequestLogPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more RequestLogs that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RequestLogFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all RequestLogs
   * const requestLogs = await prisma.requestLog.findMany()
   * 
   * // Get first 10 RequestLogs
   * const requestLogs = await prisma.requestLog.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const requestLogWithIdOnly = await prisma.requestLog.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends RequestLogFindManyArgs>(args?: Prisma.SelectSubset<T, RequestLogFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RequestLogPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a RequestLog.
   * @param {RequestLogCreateArgs} args - Arguments to create a RequestLog.
   * @example
   * // Create one RequestLog
   * const RequestLog = await prisma.requestLog.create({
   *   data: {
   *     // ... data to create a RequestLog
   *   }
   * })
   * 
   */
  create<T extends RequestLogCreateArgs>(args: Prisma.SelectSubset<T, RequestLogCreateArgs<ExtArgs>>): Prisma.Prisma__RequestLogClient<runtime.Types.Result.GetResult<Prisma.$RequestLogPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many RequestLogs.
   * @param {RequestLogCreateManyArgs} args - Arguments to create many RequestLogs.
   * @example
   * // Create many RequestLogs
   * const requestLog = await prisma.requestLog.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends RequestLogCreateManyArgs>(args?: Prisma.SelectSubset<T, RequestLogCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many RequestLogs and returns the data saved in the database.
   * @param {RequestLogCreateManyAndReturnArgs} args - Arguments to create many RequestLogs.
   * @example
   * // Create many RequestLogs
   * const requestLog = await prisma.requestLog.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many RequestLogs and only return the `id`
   * const requestLogWithIdOnly = await prisma.requestLog.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends RequestLogCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, RequestLogCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RequestLogPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a RequestLog.
   * @param {RequestLogDeleteArgs} args - Arguments to delete one RequestLog.
   * @example
   * // Delete one RequestLog
   * const RequestLog = await prisma.requestLog.delete({
   *   where: {
   *     // ... filter to delete one RequestLog
   *   }
   * })
   * 
   */
  delete<T extends RequestLogDeleteArgs>(args: Prisma.SelectSubset<T, RequestLogDeleteArgs<ExtArgs>>): Prisma.Prisma__RequestLogClient<runtime.Types.Result.GetResult<Prisma.$RequestLogPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one RequestLog.
   * @param {RequestLogUpdateArgs} args - Arguments to update one RequestLog.
   * @example
   * // Update one RequestLog
   * const requestLog = await prisma.requestLog.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends RequestLogUpdateArgs>(args: Prisma.SelectSubset<T, RequestLogUpdateArgs<ExtArgs>>): Prisma.Prisma__RequestLogClient<runtime.Types.Result.GetResult<Prisma.$RequestLogPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more RequestLogs.
   * @param {RequestLogDeleteManyArgs} args - Arguments to filter RequestLogs to delete.
   * @example
   * // Delete a few RequestLogs
   * const { count } = await prisma.requestLog.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends RequestLogDeleteManyArgs>(args?: Prisma.SelectSubset<T, RequestLogDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more RequestLogs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RequestLogUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many RequestLogs
   * const requestLog = await prisma.requestLog.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends RequestLogUpdateManyArgs>(args: Prisma.SelectSubset<T, RequestLogUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more RequestLogs and returns the data updated in the database.
   * @param {RequestLogUpdateManyAndReturnArgs} args - Arguments to update many RequestLogs.
   * @example
   * // Update many RequestLogs
   * const requestLog = await prisma.requestLog.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more RequestLogs and only return the `id`
   * const requestLogWithIdOnly = await prisma.requestLog.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends RequestLogUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, RequestLogUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RequestLogPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one RequestLog.
   * @param {RequestLogUpsertArgs} args - Arguments to update or create a RequestLog.
   * @example
   * // Update or create a RequestLog
   * const requestLog = await prisma.requestLog.upsert({
   *   create: {
   *     // ... data to create a RequestLog
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the RequestLog we want to update
   *   }
   * })
   */
  upsert<T extends RequestLogUpsertArgs>(args: Prisma.SelectSubset<T, RequestLogUpsertArgs<ExtArgs>>): Prisma.Prisma__RequestLogClient<runtime.Types.Result.GetResult<Prisma.$RequestLogPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of RequestLogs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RequestLogCountArgs} args - Arguments to filter RequestLogs to count.
   * @example
   * // Count the number of RequestLogs
   * const count = await prisma.requestLog.count({
   *   where: {
   *     // ... the filter for the RequestLogs we want to count
   *   }
   * })
  **/
  count<T extends RequestLogCountArgs>(
    args?: Prisma.Subset<T, RequestLogCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], RequestLogCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a RequestLog.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RequestLogAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends RequestLogAggregateArgs>(args: Prisma.Subset<T, RequestLogAggregateArgs>): Prisma.PrismaPromise<GetRequestLogAggregateType<T>>

  /**
   * Group by RequestLog.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RequestLogGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends RequestLogGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: RequestLogGroupByArgs['orderBy'] }
      : { orderBy?: RequestLogGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, RequestLogGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetRequestLogGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the RequestLog model
 */
readonly fields: RequestLogFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for RequestLog.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__RequestLogClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  attempts<T extends Prisma.RequestLog$attemptsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.RequestLog$attemptsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RequestAttemptPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the RequestLog model
 */
export interface RequestLogFieldRefs {
  readonly id: Prisma.FieldRef<"RequestLog", 'String'>
  readonly logicalModelId: Prisma.FieldRef<"RequestLog", 'String'>
  readonly protocol: Prisma.FieldRef<"RequestLog", 'String'>
  readonly status: Prisma.FieldRef<"RequestLog", 'String'>
  readonly totalDurationMilliseconds: Prisma.FieldRef<"RequestLog", 'Int'>
  readonly totalTokens: Prisma.FieldRef<"RequestLog", 'Int'>
  readonly createdTime: Prisma.FieldRef<"RequestLog", 'BigInt'>
}
    

// Custom InputTypes
/**
 * RequestLog findUnique
 */
export type RequestLogFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RequestLog
   */
  select?: Prisma.RequestLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RequestLog
   */
  omit?: Prisma.RequestLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RequestLogInclude<ExtArgs> | null
  /**
   * Filter, which RequestLog to fetch.
   */
  where: Prisma.RequestLogWhereUniqueInput
}

/**
 * RequestLog findUniqueOrThrow
 */
export type RequestLogFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RequestLog
   */
  select?: Prisma.RequestLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RequestLog
   */
  omit?: Prisma.RequestLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RequestLogInclude<ExtArgs> | null
  /**
   * Filter, which RequestLog to fetch.
   */
  where: Prisma.RequestLogWhereUniqueInput
}

/**
 * RequestLog findFirst
 */
export type RequestLogFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RequestLog
   */
  select?: Prisma.RequestLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RequestLog
   */
  omit?: Prisma.RequestLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RequestLogInclude<ExtArgs> | null
  /**
   * Filter, which RequestLog to fetch.
   */
  where?: Prisma.RequestLogWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RequestLogs to fetch.
   */
  orderBy?: Prisma.RequestLogOrderByWithRelationInput | Prisma.RequestLogOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for RequestLogs.
   */
  cursor?: Prisma.RequestLogWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RequestLogs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RequestLogs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of RequestLogs.
   */
  distinct?: Prisma.RequestLogScalarFieldEnum | Prisma.RequestLogScalarFieldEnum[]
}

/**
 * RequestLog findFirstOrThrow
 */
export type RequestLogFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RequestLog
   */
  select?: Prisma.RequestLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RequestLog
   */
  omit?: Prisma.RequestLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RequestLogInclude<ExtArgs> | null
  /**
   * Filter, which RequestLog to fetch.
   */
  where?: Prisma.RequestLogWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RequestLogs to fetch.
   */
  orderBy?: Prisma.RequestLogOrderByWithRelationInput | Prisma.RequestLogOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for RequestLogs.
   */
  cursor?: Prisma.RequestLogWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RequestLogs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RequestLogs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of RequestLogs.
   */
  distinct?: Prisma.RequestLogScalarFieldEnum | Prisma.RequestLogScalarFieldEnum[]
}

/**
 * RequestLog findMany
 */
export type RequestLogFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RequestLog
   */
  select?: Prisma.RequestLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RequestLog
   */
  omit?: Prisma.RequestLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RequestLogInclude<ExtArgs> | null
  /**
   * Filter, which RequestLogs to fetch.
   */
  where?: Prisma.RequestLogWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RequestLogs to fetch.
   */
  orderBy?: Prisma.RequestLogOrderByWithRelationInput | Prisma.RequestLogOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing RequestLogs.
   */
  cursor?: Prisma.RequestLogWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RequestLogs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RequestLogs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of RequestLogs.
   */
  distinct?: Prisma.RequestLogScalarFieldEnum | Prisma.RequestLogScalarFieldEnum[]
}

/**
 * RequestLog create
 */
export type RequestLogCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RequestLog
   */
  select?: Prisma.RequestLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RequestLog
   */
  omit?: Prisma.RequestLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RequestLogInclude<ExtArgs> | null
  /**
   * The data needed to create a RequestLog.
   */
  data: Prisma.XOR<Prisma.RequestLogCreateInput, Prisma.RequestLogUncheckedCreateInput>
}

/**
 * RequestLog createMany
 */
export type RequestLogCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many RequestLogs.
   */
  data: Prisma.RequestLogCreateManyInput | Prisma.RequestLogCreateManyInput[]
}

/**
 * RequestLog createManyAndReturn
 */
export type RequestLogCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RequestLog
   */
  select?: Prisma.RequestLogSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the RequestLog
   */
  omit?: Prisma.RequestLogOmit<ExtArgs> | null
  /**
   * The data used to create many RequestLogs.
   */
  data: Prisma.RequestLogCreateManyInput | Prisma.RequestLogCreateManyInput[]
}

/**
 * RequestLog update
 */
export type RequestLogUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RequestLog
   */
  select?: Prisma.RequestLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RequestLog
   */
  omit?: Prisma.RequestLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RequestLogInclude<ExtArgs> | null
  /**
   * The data needed to update a RequestLog.
   */
  data: Prisma.XOR<Prisma.RequestLogUpdateInput, Prisma.RequestLogUncheckedUpdateInput>
  /**
   * Choose, which RequestLog to update.
   */
  where: Prisma.RequestLogWhereUniqueInput
}

/**
 * RequestLog updateMany
 */
export type RequestLogUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update RequestLogs.
   */
  data: Prisma.XOR<Prisma.RequestLogUpdateManyMutationInput, Prisma.RequestLogUncheckedUpdateManyInput>
  /**
   * Filter which RequestLogs to update
   */
  where?: Prisma.RequestLogWhereInput
  /**
   * Limit how many RequestLogs to update.
   */
  limit?: number
}

/**
 * RequestLog updateManyAndReturn
 */
export type RequestLogUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RequestLog
   */
  select?: Prisma.RequestLogSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the RequestLog
   */
  omit?: Prisma.RequestLogOmit<ExtArgs> | null
  /**
   * The data used to update RequestLogs.
   */
  data: Prisma.XOR<Prisma.RequestLogUpdateManyMutationInput, Prisma.RequestLogUncheckedUpdateManyInput>
  /**
   * Filter which RequestLogs to update
   */
  where?: Prisma.RequestLogWhereInput
  /**
   * Limit how many RequestLogs to update.
   */
  limit?: number
}

/**
 * RequestLog upsert
 */
export type RequestLogUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RequestLog
   */
  select?: Prisma.RequestLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RequestLog
   */
  omit?: Prisma.RequestLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RequestLogInclude<ExtArgs> | null
  /**
   * The filter to search for the RequestLog to update in case it exists.
   */
  where: Prisma.RequestLogWhereUniqueInput
  /**
   * In case the RequestLog found by the `where` argument doesn't exist, create a new RequestLog with this data.
   */
  create: Prisma.XOR<Prisma.RequestLogCreateInput, Prisma.RequestLogUncheckedCreateInput>
  /**
   * In case the RequestLog was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.RequestLogUpdateInput, Prisma.RequestLogUncheckedUpdateInput>
}

/**
 * RequestLog delete
 */
export type RequestLogDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RequestLog
   */
  select?: Prisma.RequestLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RequestLog
   */
  omit?: Prisma.RequestLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RequestLogInclude<ExtArgs> | null
  /**
   * Filter which RequestLog to delete.
   */
  where: Prisma.RequestLogWhereUniqueInput
}

/**
 * RequestLog deleteMany
 */
export type RequestLogDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which RequestLogs to delete
   */
  where?: Prisma.RequestLogWhereInput
  /**
   * Limit how many RequestLogs to delete.
   */
  limit?: number
}

/**
 * RequestLog.attempts
 */
export type RequestLog$attemptsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RequestAttempt
   */
  select?: Prisma.RequestAttemptSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RequestAttempt
   */
  omit?: Prisma.RequestAttemptOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RequestAttemptInclude<ExtArgs> | null
  where?: Prisma.RequestAttemptWhereInput
  orderBy?: Prisma.RequestAttemptOrderByWithRelationInput | Prisma.RequestAttemptOrderByWithRelationInput[]
  cursor?: Prisma.RequestAttemptWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.RequestAttemptScalarFieldEnum | Prisma.RequestAttemptScalarFieldEnum[]
}

/**
 * RequestLog without action
 */
export type RequestLogDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RequestLog
   */
  select?: Prisma.RequestLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RequestLog
   */
  omit?: Prisma.RequestLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RequestLogInclude<ExtArgs> | null
}
