
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models'
export type * from './prismaNamespace'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  Provider: 'Provider',
  LogicalModel: 'LogicalModel',
  ModelBinding: 'ModelBinding',
  ProviderHealth: 'ProviderHealth',
  Settings: 'Settings',
  RequestLog: 'RequestLog',
  RequestAttempt: 'RequestAttempt'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const ProviderScalarFieldEnum = {
  id: 'id',
  name: 'name',
  apiKeyReference: 'apiKeyReference',
  timeoutMilliseconds: 'timeoutMilliseconds',
  enabled: 'enabled',
  createdTime: 'createdTime',
  updatedTime: 'updatedTime',
  deletedTime: 'deletedTime'
} as const

export type ProviderScalarFieldEnum = (typeof ProviderScalarFieldEnum)[keyof typeof ProviderScalarFieldEnum]


export const LogicalModelScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  enabled: 'enabled',
  createdTime: 'createdTime',
  updatedTime: 'updatedTime',
  deletedTime: 'deletedTime'
} as const

export type LogicalModelScalarFieldEnum = (typeof LogicalModelScalarFieldEnum)[keyof typeof LogicalModelScalarFieldEnum]


export const ModelBindingScalarFieldEnum = {
  id: 'id',
  logicalModelId: 'logicalModelId',
  providerId: 'providerId',
  protocol: 'protocol',
  upstreamUrl: 'upstreamUrl',
  upstreamModelId: 'upstreamModelId',
  priority: 'priority',
  enabled: 'enabled',
  customAuthHeader: 'customAuthHeader',
  createdTime: 'createdTime',
  updatedTime: 'updatedTime',
  deletedTime: 'deletedTime'
} as const

export type ModelBindingScalarFieldEnum = (typeof ModelBindingScalarFieldEnum)[keyof typeof ModelBindingScalarFieldEnum]


export const ProviderHealthScalarFieldEnum = {
  providerId: 'providerId',
  consecutiveFailures: 'consecutiveFailures',
  cooldownUntilTime: 'cooldownUntilTime',
  lastSuccessTime: 'lastSuccessTime',
  lastFailureTime: 'lastFailureTime',
  updatedTime: 'updatedTime'
} as const

export type ProviderHealthScalarFieldEnum = (typeof ProviderHealthScalarFieldEnum)[keyof typeof ProviderHealthScalarFieldEnum]


export const SettingsScalarFieldEnum = {
  id: 'id',
  listenHost: 'listenHost',
  listenPort: 'listenPort',
  accessTokenReference: 'accessTokenReference',
  logRetentionCount: 'logRetentionCount',
  cooldownBaseSeconds: 'cooldownBaseSeconds',
  cooldownMaxSeconds: 'cooldownMaxSeconds',
  consecutiveFailureThreshold: 'consecutiveFailureThreshold',
  idleTimeoutMilliseconds: 'idleTimeoutMilliseconds',
  updatedTime: 'updatedTime'
} as const

export type SettingsScalarFieldEnum = (typeof SettingsScalarFieldEnum)[keyof typeof SettingsScalarFieldEnum]


export const RequestLogScalarFieldEnum = {
  id: 'id',
  logicalModelId: 'logicalModelId',
  protocol: 'protocol',
  status: 'status',
  totalDurationMilliseconds: 'totalDurationMilliseconds',
  totalTokens: 'totalTokens',
  createdTime: 'createdTime'
} as const

export type RequestLogScalarFieldEnum = (typeof RequestLogScalarFieldEnum)[keyof typeof RequestLogScalarFieldEnum]


export const RequestAttemptScalarFieldEnum = {
  id: 'id',
  requestId: 'requestId',
  providerId: 'providerId',
  bindingId: 'bindingId',
  upstreamModelId: 'upstreamModelId',
  attemptIndex: 'attemptIndex',
  status: 'status',
  errorCode: 'errorCode',
  errorMessage: 'errorMessage',
  durationMilliseconds: 'durationMilliseconds',
  createdTime: 'createdTime'
} as const

export type RequestAttemptScalarFieldEnum = (typeof RequestAttemptScalarFieldEnum)[keyof typeof RequestAttemptScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]

